### ISSUE TITLE
Bug in QueryExpression evaluation

### ISSUE THREAD

**Issue by benArrayx** [jordimontana82/fake-xrm-easy#101]
Hi there, I'm writing tests using FakeXrmEasy (which is awesome by the way!). I've found an issue when passing multiple Order Expressions on a QueryExpression. I can see that the problem lies in XrmFakedContextQueries.cs line 298:

```
   //Sort results
   if (qe.Orders != null)
   {
       foreach (var order in qe.Orders)
       {
           if (order.OrderType == OrderType.Ascending)
               query = query.OrderBy(e => e.Attributes.ContainsKey(order.AttributeName) ? e.Attributes[order.AttributeName] : null, new XrmOrderByAttributeComparer());
           else
               query = query.OrderByDescending(e => e.Attributes.ContainsKey(order.AttributeName) ? e.Attributes[order.AttributeName] : null, new XrmOrderByAttributeComparer());
       }
   }
```

I believe that this code is always going to execute the sort according to the last order added, since it is not using 'ThenBy' or 'ThenByDescending' calls after the initial 'OrderBy' or 'OrderByDescending' clause.

I can't provide exact repro code since I have a little different setup from standard, but it goes something like this:

```
    var account5 = new Account() { Id = Guid.NewGuid(), Name = "5 Test", Address1_City = "1 City", Address1_StateOrProvince = "a1 State" };
    var account1 = new Account() { Id = Guid.NewGuid(), Name = "1 Test", Address1_City = "1 City", Address1_StateOrProvince = "a2 State" };
    var account3 = new Account() { Id = Guid.NewGuid(), Name = "3 Test", Address1_City = "2 City", Address1_StateOrProvince = "b1 State" };
    var account2 = new Account() { Id = Guid.NewGuid(), Name = "2 Test", Address1_City = "2 City", Address1_StateOrProvince = "b2 State" };
    var account6 = new Account() { Id = Guid.NewGuid(), Name = "6 Test", Address1_City = "3 City", Address1_StateOrProvince = "c1 State" };
    var account4 = new Account() { Id = Guid.NewGuid(), Name = "4 Test", Address1_City = "3 City", Address1_StateOrProvince = "c2 State" };

    List<Account> initialAccs = new List<Account>() {
        account1, account2, account3, account4, account5, account6
    };

    Context.Initialize(initialAccs);

    QueryExpression query = new QueryExpression()
    {
        EntityName = "account",
        ColumnSet = new ColumnSet(true),
        Orders =
        {
            new OrderExpression("address1_city", OrderType.Ascending),
            new OrderExpression("address1_stateorprovince", OrderType.Descending)
        }
    };

    EntityCollection ec = Service.RetrieveMultiple(query);
    
    //this Assert fails as the first entity in the returned collection is '4 Test', which is consistent with only the 2nd sort having been executed.
    Assert.IsTrue(ec.Entities.First().ToEntity<Account>().Name.Equals("1 Test"), "Test 4 failed");
```

Hope that this is enough info for you to make a fix? Let me know if not, I'll try to clarify...

**Comment by jordimontana82** [comment]
Hi @benArrayx !

Thx for your feedback! 

And yep you're right, it should be using .ThenBy and .ThenByDescending for subsequent calls after the first OrderBy / OrderByDescending.

We'll fix it for the next release of the NuGet package.

Cheers!

**Comment by benArrayx** [comment]
No problem :)

**Comment by jordimontana82** [comment]
Hi @benArrayx ,

That commit closes the issue. It will still be an issue if we have an array of >= 3 orderby's as I think we'll a problem references / memory... however, it should be ok as CRM only supports ordering by up to 2 attributes?

Cheers,

**Comment by benArrayx** [comment]
Hi Jordi, that commit seems to fix my issues. I did have some tests with 3 order bys but have removed these. I couldn’t find a reference to CRM only supporting ordering up to 2 attributes – do you have a link for this?

**Comment by jordimontana82** [comment]
It's limited in the UI itself, (i.e., when doing an advanced find you can only sort results by up to 2 columns). Also, the CRM LINQ driver implementation is limited to order records from the main entity, i.e., it is not supported to order by related columns, surprising, but true : )
