### ISSUE TITLE
Activitymimeattachment body retrieving

### ISSUE THREAD

**Issue by Vahagn1993** [jordimontana82/fake-xrm-easy#104]
When we retrieve multiple "ActivityMIMEAttachment" entities from OrganizationService of XRM we got only first 2000 characters of "Body" field. But when we retrieve it from fake-xrm-easy we got entire "Body". In my case it means that my tests was green but in fact when I register my plugin in XRM and try to decode "Body" via Convert.FromBase64String() I got exception.

**Comment by jordimontana82** [comment]
Hi @Vahagn1993 

That's interesting... you mean the org service returns the Body truncated to "2000" chars only?

**Comment by jordimontana82** [comment]
Could you post your test, please? What was the exception you got? Array index out of bounds?

**Comment by Vahagn1993** [comment]
@jordimontana82  I need time to prepare good one. I'll post it here.
Yes, real org service return truncated "Body". I'm newbie in XRM development and thought that it's my mistake. But when I googled it I found:
https://goo.gl/WhzOTj
https://goo.gl/B15NIu

**Comment by jordimontana82** [comment]
Did you try retrieving the DocumentBody property with a single Retrieve message? Example: https://msdn.microsoft.com/en-gb/library/gg328429.aspx

**Comment by Vahagn1993** [comment]
Hi, Jordi! Sorry for late. I'll write answer after couple of days

**Comment by Vahagn1993** [comment]
Hi again! Sorry for late. I reporoduced my presviuos situation but now it's okay. Seems like I did something wrong at that time and was confused by posts that I googled. Apparently I can't say with 100% confidence that led me to that situation. So I apologize for the inconvenience and if I reproduce the situation in which OrgService truncates "Body" to 2k chars I let you know.

**Comment by jordimontana82** [comment]
Ok no worries
