### ISSUE TITLE
Automate Build

### ISSUE THREAD

**Issue by DigitalFlow** [jordimontana82/fake-xrm-easy#11]
Hey Jordi,

how would you like it, if I created a FAKE (F# Make: https://github.com/fsharp/FAKE) Build Script that we could use for attaching this project into a CI and run builds and Nuget package creation automatically on each commit?

Kind Regards,
DigitalFlow

**Comment by jordimontana82** [comment]
Hi @DigitalFlow ,

Sounds good, I used to have a VM running daily CI builds on Jenkins,  it was running them using xbuild (linux port of msbuild), which , I think, it might be better for a Dynamics CRM audience, cause the chances are they'll be more familiar with msbuild than automated build scripts with F# maybe?

https://github.com/Microsoft/msbuild/tree/xplat

What do you think?

I'll be looking to setup the VM again.... :)

**Comment by DigitalFlow** [comment]
FAKE uses MSBuild for building, so it might still be an option?
An advantage is that we could use a free AppVeyor or TravisCI build and directly deploy to Nuget.

**Comment by DigitalFlow** [comment]
In addition to that, FAKE enables us to run all unit tests on each build and can restore nuget packages before each build.

**Comment by jordimontana82** [comment]
Sounds cool! :+1:  

I would worried about using Travis CI due to Windows support issues.

Re running tests on each build those could be also setup using Xunit, that's another option, and then being kicked off as part of the CI build process pipeline or from within Visual Studio, via the Test Explorer, if you wish.

 I never used FAKE before, I'll check it out. :)

**Comment by DigitalFlow** [comment]
Great! Theres XUnit support, too :)

**Comment by DigitalFlow** [comment]
Hey @jordimontana82,

just saw that you labeled this issue as enhancement.
Does this mean that you would like to have a FAKE build script for FakeXrmEasy?

Kind Regards

**Comment by jordimontana82** [comment]
Hi @DigitalFlow 

I was just classifying issues between bugs and enhancements / improvements... nothing else :)

Where would you put the script?

I'd like to setup a CI build in AppVeyor first

**Comment by jordimontana82** [comment]
Hey @DigitalFlow 

I've setup a CI build on AppVeyor for the project

**Comment by DigitalFlow** [comment]
Great, like it very much :+1:
