### ISSUE TITLE
InvalidCast Exception

### ISSUE THREAD

**Issue by amolotkov** [jordimontana82/fake-xrm-easy#114]
CRM 2011
The following query was working fine prior version 1.19.2
context.ContactSet.Where(c => c.statecode == 0).ToList().\
Any version after 1.19.1 throws "Invalid Cast" exception
The CRM Context is generated using following cmd line
crmsvcutil.exe /codeCustomization:"Microsoft.Xrm.Client.CodeGeneration.CodeCustomization, Microsoft.Xrm.Client.CodeGeneration" /url:http://[crm-server]/OrgName/XrmServices/2011/Organization.svc /out:GeneratedModels.cs /namespace:Crm.Models /servicecontextname:CrmContext

**Comment by jordimontana82** [comment]
How is your statecode property generated? Could you post a unit test to reproduce this please?

**Comment by jordimontana82** [comment]
Thx so much for fixing it @amolotkov !

**Comment by amolotkov** [comment]
Tx for Framework :) Lifesaver

**Comment by jordimontana82** [comment]
You're very welcome and glad you find it useful. Please could you share the awesomeness on Twitter using #FakeXrmEasy hashtag pls? :)
