### ISSUE TITLE
Ability to use serialised profile

### ISSUE THREAD

**Issue by rajyraman** [jordimontana82/fake-xrm-easy#118]
In the context of integration tests, it would be really awesome if serialised profile can be used to quickly populate the context either from the Plugin-profile entity or from the serialised xml. If I can wrote this code it will cutdown on some tests I write purely to replicate production bugs. e.g.

`var context = new XrmRealContext
            {
                ProxyTypesAssembly = typeof(LastNameUpperCasePlugin).Assembly,
                ConnectionStringName = "CRMOnline"
            };
var executionContext = context.GetPluginExecutionContextFromProfile("Update of account at 2017-02-02T06:37:44");
context.ExecutePluginWith<LastNameUpperCasePlugin>(executionContext);`

**Comment by jordimontana82** [comment]
Thx @rajyraman ! Indeed, that would be really handy :) 

I think we could start just deserializing the Profile -> Context -> PluginExecutionContext node from an xml and see how it goes.  Like, these properties match pretty much the plugin execution context class:

![image](https://cloud.githubusercontent.com/assets/3968950/22576145/3cbee57e-e9ba-11e6-9d99-9e1a439edb85.png)


Next step would be to have maybe a helper method where that xml is retrieved by just doing a .Retrieve() on the Plugin Profiler entity, like .GetPluginExecutionContextFromProfile(id) ?

There might be [differences in the xml schema](http://missdynamicscrm.blogspot.com.es/2014/05/debug-crm-2013-using-plugin-profiler.html) across CRM versions

**Comment by jordimontana82** [comment]
Hi Raj, this took longer than I initially thought but... with that commit there is a new method to deserialise the serialised plugin profile. So now we could just copy & paste the serialised profile field into a unit test and just run it against real or a fake context without even attaching to process or even using the plugin registration tool! :)

**Comment by bwmodular** [comment]
That's amazingly useful - thaks again!

**Comment by rajyraman** [comment]
That's fantastic Jordi. Great work 👍. Thank you.
