### ISSUE TITLE
"Value cannot be null" when executing Associate request

### ISSUE THREAD

**Issue by bwmodular** [jordimontana82/fake-xrm-easy#119]
I'm testing a plugin which creates a new record (entity = team) and then associates this with another pre-existing record (entity =role). 
All of the parameters of the Associate request look good to me, but I'm getting this error:
"Value cannot be Null. Parameter name: key"

I looked at the tests in the FakeXrmEasy Master solution, but couldn't see anything else that I should be doing.
I'm initializing the context with the role before invoking the plugin, and adding in the relationship (XrmFakedRelationship) between team and role.
Is there anything else you can think of that I'd need to do?

Thanks.

**Comment by jordimontana82** [comment]
Could you please commit a unit test so that I can reproduce? Cheers!

**Comment by bwmodular** [comment]
Thanks Jordi - I'll try and write a Unit test and post it.

**Comment by bwmodular** [comment]
My standalone unit test works fine without exception. which is good, because I can work back from there and see what I'm doing differently in the plugin test.....
I'll let you know...

**Comment by jordimontana82** [comment]
Ok nice one... let me know Ben

**Comment by jordimontana82** [comment]
Closing this one if you are happy, if not please reopen

**Comment by bwmodular** [comment]
Yes, just worked it out 5 mins ago! - I was initializing my XrmFakedRelationship badly - sorry about that!

**Comment by jordimontana82** [comment]
No prob Ben!
