### ISSUE TITLE
ConditionExpression with EntityName specification

### ISSUE THREAD

**Issue by mivra** [jordimontana82/fake-xrm-easy#120]
I've come across a failed test and after some research, I found that if you use a ConditionExpression with entity name specification the condition is not correctly evaluated. That ConditionExpression constructor was probably added in some of the versions of SDK higher than v5. Certainly, it is in version 8.

```
[Test]
public void ConditionExpression_Test()
{
	var firstContact = new Contact()
	{
		Id = Guid.NewGuid(),
		FirstName = "John",
		LastName = "Smith",
		EMailAddress1 = "SmiJo@witness.co.uk"
	};

	var secondContact = new Contact()
	{
		Id = Guid.NewGuid(),
		FirstName = "Mary",
		LastName = "Bloody"
	};


	var fakedContext = new XrmFakedContext();
	var fakedService = fakedContext.GetFakedOrganizationService();

	fakedContext.Initialize(new Entity[] { firstContact, secondContact });

	var query = new QueryExpression()
	{
		EntityName = Contact.EntityLogicalName,
		Criteria = new FilterExpression()
		{
			Conditions = {
				new ConditionExpression(Contact.EntityLogicalName /* without entityname test passes */, Contact.Fields.FirstName, ConditionOperator.Equal, "John")
			}
		}
	};

	var result = fakedService.RetrieveMultiple(query).Entities;

	Assert.AreEqual(1, result.Count());
}
```

Also in combination with LinkedEntity query, the exception is thrown.

> Result Message:	System.Exception : XrmFakedContext.FindReflectedAttributeType: Attribute listmember.listid not found for type DynamicsCrmIntegration.Types.ListMember

Example code for it can be:

```
var contactsQuery = new Microsoft.Xrm.Sdk.Query.QueryExpression(Contact.EntityLogicalName)
{
	ColumnSet = columns ?? new ColumnSet(true),
	LinkEntities =
	{
		new LinkEntity(Contact.EntityLogicalName, ListMember.EntityLogicalName, Contact.Fields.Id, ListMember.Fields.EntityId, JoinOperator.Inner)
		{
			LinkCriteria = new FilterExpression(LogicalOperator.And)
			{
				Conditions =
				{
					new ConditionExpression(ListMember.EntityLogicalName, ListMember.Fields.ListId, ConditionOperator.Equal, marketingList.Id),                                
				}
			}
		}
	}
};
```

Should it be supported scenario?

Thanks.
Michal

**Comment by jordimontana82** [comment]
Hi Michal, yep that entity name constructor and property was introduced after >= 2013. That's why you'll see many conditional compilation statements to cater for them for basically 2011 and all the others.

Did you ran this query against a real organisation service?

**Comment by jordimontana82** [comment]
That commit fixes the issue with the Condition Expression.

Now, I don't think the 2nd issue with Linked Entities is gonna be a problem. There was basically a fundamental change between CRM 2011 and CRM >= 2013. Essentially that EntityName attribute was introduced ( I imagine!) to save you from having to add nested linked entities, as you could have all of them at the root level and reference them by entity name or alias.

If you try to inspect how joins are translated into QueryExpressions by the CRM LINQ provider between different versions you'll see that. 

I personally use CRM LINQ whenever possible as using QueryExpressions directly is too much "verbose" for me :)
