### ISSUE TITLE
Where do my traces go?

### ISSUE THREAD

**Issue by bwmodular** [jordimontana82/fake-xrm-easy#121]
Sorry to ask such a basic question, but where does the output of the faked tracing service go?
Can I overwrite it in some way to send to the console?
I'm sure it's obvious, but I can't see where the trace output goes.

**Comment by jordimontana82** [comment]
They're appended [here](https://github.com/jordimontana82/fake-xrm-easy/blob/master/FakeXrmEasy.Shared/XrmFakedTracingService.cs), you could call DumpTrace to send it to whatever you need..

**Comment by bwmodular** [comment]
Sorry Jordi, still don't get it. And maybe I'm asking the wrong question.
If I instantiate a plugin with a default Plugin Context, can I see the output of any traces that I've added to the plugin code?
 
Ideally they'd be visible in the test results window, but I don't see anything there.

What do I need to do to instantiate the plugin with the Fake Tracing service, or to redirect the output of the Trace to the console.

**Comment by jordimontana82** [comment]
Sorry Ben, traces were indeed written in the fake tracing service fine but, as there wasn't anything to expose it after the plugin execution, there was no way for you to call DumpTrace, but now there is a .GetFakeTracingService() you could use to then do something like Console.Write(tracingService.DumpTrace()), for instance.

**Comment by bwmodular** [comment]
Thanks so much - FakeXrmEasy is so useful.

**Comment by jordimontana82** [comment]
You're very welcome Ben. Your feedback is always welcome :)

**Comment by bwmodular** [comment]
Hi Jordi,
that works wonderfully when the plugin passes and when no exceptions are thrown, but if the test fails, or if the test passes but with an expected exception, the tracing is not shown.

Here's the plugin - it invokes both Console.WriteLine and Tracing.Trace:

![image](https://cloud.githubusercontent.com/assets/1889586/22858621/c878ff9e-f0ba-11e6-8e9a-40dbfb92c69f.png)

Here are three tests - each of them calls DumpTrace at the end:
![image](https://cloud.githubusercontent.com/assets/1889586/22858628/fac684bc-f0ba-11e6-953a-5cb3f367446e.png)

The first test passes and the tracing is shown:

![image](https://cloud.githubusercontent.com/assets/1889586/22858634/1c70ecba-f0bb-11e6-8d1e-ef672859122a.png)


The second test also passes, but the plugin raises an expected exception. The tracing is not shown:

![image](https://cloud.githubusercontent.com/assets/1889586/22858651/4830c64a-f0bb-11e6-867e-a6842b2280fc.png)

The third test fails, and again no tracing is shown:

![image](https://cloud.githubusercontent.com/assets/1889586/22858662/73595ca6-f0bb-11e6-88a0-d8d3fb79a264.png)

Sorry to make a meal of this, but it's exactly when tests are failing, or when exceptions are thrown that being able to read the value of tracing becomes important when testing.

**Comment by DigitalFlow** [comment]
Hi Ben,

Try surrounding your Plugin execution with Try-Catch or assert that it throws an exception instead of using the function property.
Otherwise the exception will not be caught and lead to your logging not be called, since execution is aborted.

Kind Regards,
Florian

**Comment by jordimontana82** [comment]
Hi Ben, just try what Florian was suggesting. I follow the same approach. 

Florian , +1 to the OnTrace event ;)

**Comment by bwmodular** [comment]
OK, thanks both. Don't think either of those suggestions will work with the second example where the test fails. Try/Catch on the plugin won't help as the plugin does not fail. Assert.Throws will not help because no exception is raised by the plugin. Plugin runs successfully, but does not give the expected results.

**Comment by jordimontana82** [comment]
Hi Ben, if the plugin doesn't raise any exceptions you should be able still to do 

    ctx.GetFakeTracingService().DumpTrace()

Traces are written at the minute to the fake tracing service regardless of exceptions occuring or not.

**Comment by jordimontana82** [comment]
For the scenario where the plugin shouldn't fail you can also wrap the plugin into the Assert.DoesNotThrow(() => ctx.ExecutePluginWith...)

**Comment by bwmodular** [comment]
> Hi Ben, if the plugin doesn't raise any exceptions you should still be able to do
> 
> ctx.GetFakeTracingService().DumpTrace()
> 
> Traces are written at the minute to the fake tracing service regardless of exceptions occuring or not.

The issue was that I was asserting before using DumpTrace() so the test was failing before we got to DumpTrace(). Reversing the order fixes that issue, sorry about that.

**Comment by bwmodular** [comment]
Not sure that tracing is accessible within Workfow execution context.
This line:
Console.WriteLine(fakedContext.GetFakeTracingService().DumpTrace());
works fine after plugin execution, but fails after succesful completion of a workflow.

Can provide unit test if you like, but I think I'm correct as the workflow runs fine without that line, and this:
fakedContext.GetFakeTracingService() is evaluating as false.

**Comment by jordimontana82** [comment]
Reopening for codeactivities
