### ISSUE TITLE
Mode of PluginExecutionContext not set correctly when executing plugin with DefaultPluginContext

### ISSUE THREAD

**Issue by bwmodular** [jordimontana82/fake-xrm-easy#122]
If you set Message Name, Stage and Mode on a Default Plugin Context, when you get the values of these in the Plugin, the first two are set correctly, but the last is always set to 0.

I've created a very small solution with a single plugin and two tests.
The plugin checks the value of the pluginexecutioncontext's mode and throws an exception if it is 1.
In the two tests, I pass the mode as 0 in the first and 1 in the second. 
The exception is not thrown, and mode is always 0.

GitHub is not allowing me to upload a zip file, although it says these are supported, so here are some screenshots:

**The Plugin:**

![image](https://cloud.githubusercontent.com/assets/1889586/22842592/9ee635ea-efcd-11e6-8216-8838038348ac.png)

**The Tests:**
![image](https://cloud.githubusercontent.com/assets/1889586/22842537/70378e6a-efcd-11e6-92ae-793e57b47afb.png)

**The result of the first test:**
![image](https://cloud.githubusercontent.com/assets/1889586/22842366/dc73018c-efcc-11e6-9053-927aa57751d9.png)

**The result of the second test - should throw an exception but does not because the mode is 0:**
![image](https://cloud.githubusercontent.com/assets/1889586/22842382/ed5a52c0-efcc-11e6-8f9a-ec14ff7d8e67.png)

I can email the zip file if you want.

**Comment by jordimontana82** [comment]
Thx for spotting this. The above commit should fix it. If you find any other missing property, please let me know :) 

Will push a new version now after fixing many issues / new features

**Comment by bwmodular** [comment]
Thanks Jordi!

**Comment by jordimontana82** [comment]
Hi Ben, just saw you started editing a Wiki, which is great! :)  Just added a section where, personally, I only use FakeItEasy whenever I can't assert the desired output without querying the context. Updated the wiki with some examples when, for most of the things, just doing a query is a bit less verbose than trying to match the arguments of a queryexpression for example.
