### ISSUE TITLE
N:N relationship and FetchXMlQuery

### ISSUE THREAD

**Issue by reshmi-ravindran** [jordimontana82/fake-xrm-easy#125]
Hi Jordi,

I have another query,
I have created the N:N relationship between contact and customer address. However when I execute a Retrieve Multiple request, I get no results. I had a look at the context data. It has created records for Contact, Customer Address, Country & the N:N intersect entity: gbp_gbp_customaddress_contact. However when I look at contact.gbp_gbp_customaddress_contact and customerA.customerA  those are still null which explains why I have no results when I am retrieving the customer address through the linked entity gbp_gbp_customaddress_contact using the fetch XML. Not sure if that is an issue or if something which I am missing. Thanks for your help.

            Account account = new Account();
            account.Id = Guid.NewGuid();
            account.Name = "Goggle ltd";            

            Contact contact = new Contact();
            contact.Id = Guid.NewGuid();
            contact.FirstName = "Test";
            contact.LastName = "Contact 1";
            contact.ParentCustomerId = account.ToEntityReference();

            PhoneCall phonecall = new PhoneCall();
            phonecall.Id = Guid.NewGuid();
            phonecall.StateCode = PhoneCallState.Open;
            phonecall.to = ActivityParties.FromEntities(contact.ToEntityReference());
            phonecall.StatusCode = new OptionSetValue(1);
            phonecall.Subject = "Test phone call";

            gbp_globecountry Country = new gbp_globecountry()
            {
                Id = Guid.NewGuid(),
                gbp_name = "United Kingdom",
                gbp_code = "GB"
            };

            gbp_customaddress customerA = new gbp_customaddress()
            {
                gbp_customaddressId = Guid.NewGuid(),
                gbp_addresstype = new OptionSetValue(3),
                gbp_country = new EntityReference(gbp_globecountry.EntityLogicalName, Country.Id),
            };

            IMockDynamicsService mockContext = MockDynamicsServiceFactory.CreateDynamicsService();
            mockContext.AddRelationship("gbp_gbp_customaddress_contact_assosciation",
                "gbp_gbp_customaddress_contact",
                gbp_customaddress.EntityLogicalName,
                "gbp_customaddressid",
                Contact.EntityLogicalName,
                "contactid"
                );

            // add entities to the fake context
            mockContext.InitializeEntities(account, contact, phonecall, Country, customerA);
            var fakedService = mockContext.GetFakedOrganizationService();
            

            var request = new AssociateRequest()
            {
                Target = contact.ToEntityReference(),
                RelatedEntities = new EntityReferenceCollection()
                {
                    new EntityReference(gbp_customaddress.EntityLogicalName, customerA.Id),
                },
                Relationship = new Relationship("gbp_gbp_customaddress_contact_assosciation")
            };
            fakedService.Execute(request);

            string fetchQuery = string.Format(@"<fetch distinct='false' mapping='logical' output-format='xml-platform' version='1.0' >
                              <entity name='gbp_customaddress' >
                                <attribute name='gbp_country' />                                
                                <link-entity name='gbp_gbp_customaddress_contact' from='gbp_customaddressid' to='gbp_customaddressid' alias='NtoN' intersect='true' >
                                  <link-entity name='contact' from='contactid' to='contactid' alias='Contact' >
                                    <filter>
                                      <condition attribute='contactid' operator='eq' value='{0}' />
                                    </filter>
                                  </link-entity>
                                </link-entity>                                
                              </entity>
                            </fetch> ", contact.Id);
            EntityCollection result= fakedService.RetrieveMultiple(new FetchExpression(fetchQuery));

**Comment by jordimontana82** [comment]
Hi Reshmi,

Thanks for raising this.

Could you please post some of the early bound entities you are using just so that I can reproduce the issue in a unit test?

Cheers!

**Comment by reshmi-ravindran** [comment]
Hi Jordi,

Attached the proxy classses for all the entities used in fetch xml query. Please let me know if you would need any more info. Thanks!

Reshmi.
[Proxy.zip](https://github.com/jordimontana82/fake-xrm-easy/files/779637/Proxy.zip)

**Comment by jordimontana82** [comment]
Hi Reshmi,

Ok, was going a bit mad with this one... and issue was that in the AssociateRequest parameters were swapped causing the query to not return any results. I introduced a new validation in the AssociateRequest to raise an exception whenever this happens.
