### ISSUE TITLE
Possible bug in query with link entities

### ISSUE THREAD

**Issue by DigitalFlow** [jordimontana82/fake-xrm-easy#128]
Hey @jordimontana82,

Everything alright at your side?

I might have found a bug in querying records using QueryExpressions.
It seems that there are issues with queries containing link entities.
Basically I have incidents and want to retrieve all, that were created before a certain date and that also weren't target of any emails since then.
I attached a reproduction unit test in #127.
The query expression works fine against a real CRM server, however FakeXrmEasy does not return what I'd expect. When removing the LinkEntity from the query or the created on condition on incidents though, it returns what I want.

Kind Regards,
Florian

**Comment by jordimontana82** [comment]
Thanks Florian!

I'm good, you? I'll take a look at this whenever I have a chance.

Thanks!

**Comment by jordimontana82** [comment]
I took a look at this and the LeftOuter join part works fine, it just returns the Incident side of things even though there aren't emails, which is correct, but when it comes to process filters, it's gonna try to filter records using the email filters and hence result set is empty. Probably these nested filters should optional whenever the join is a left outer join.

Did you run this against a real CRM instance and works that way?

Thanks!

**Comment by DigitalFlow** [comment]
Yes, it works against the CRM.
Thanks for taking a look at it :)
