### ISSUE TITLE
Add support for integration tests

### ISSUE THREAD

**Issue by jordimontana82** [jordimontana82/fake-xrm-easy#13]
It would be ideal to run tests using a real organization service for integration testing purposes.

The connection string could be easily setup in the Web.config and we could add a custom test attribute to tell fake xrm easy that the test is actually an Integration test, and it will return a real organization service instance every time GetFakedOrganizationService is called (and every single method who calls this).

Something like this

    [Integration]
    public class MyIntegrationTests {
      [Fact]
      public void Test() {

      }
   }

Here is an example about adding custom trait attributes in XUnit:

http://dennymichael.net/2015/01/23/how-to-extendmigrate-traitattribute-to-xunit-v2-and-why-has-become-sealed/

The "tricky thing" would be that, the Initialize method could actually also "sync" our test entity records against the real organization service, for the purpose of the integration test, and then do a "cleanup" or "delete" of the records created during testing.

**Comment by teppolainio** [comment]
I'd think you shouldn't put too much onto responsibility of the single fake-xrm-easy NuGet package as unit testing and integration testing have quite different responsibilities. Another tests components as separate entities and another tests components as a part of the complete system.

I'd consider approach where current fake-xrm-easy functionality would be broken into two pars:
1. IOrganizationService simulation would be in one separate NuGet package and
2. Plugin and WF activity testing would be on separate NuGet package.

This would allow greater flexibility for community to build their own solution which might depend solely from IOrganizationService package. After these two are separated then I'd say integration tests could be implemented into separate NuGet package depending for example for those two.

**Comment by jordimontana82** [comment]
Thanks a lot for your feedback @teppolainio 

I get your point for integration testing and maybe is better to have a separete NuGet package for that. 

I do like having Plugin and Codeactivity mocks into the one fakexrmeasy NuGet package tho, to keep maintenance of the project itself easier, and also, from a point of view of unit testing solely, it's just easier to add a single reference than adding 2 per unit test project.

What do you want to add which depends solely on the IOrganizationService?

**Comment by teppolainio** [comment]
Situation I was thinking about where dependancy only to IOrganizationService would be sufficient was testing of standalone applications which query and/or write data from/to CRM but are not run within CRM. Examples would be different kind of integration services, web services, Windows services, command line application, desktop applications etc.

Also, if my assumption is correct IOrganizationService mockup is implemented using "pure code" which does not have dependency to FakeItEasy mockup library whereas plugin and code activity execution parts of fake-xrm-easy are done using mockups i.e. they have dependancy to FakeItEasy. If this assumption is correct then separate NuGet package for IOrganizationService mockup would also make it possible to integrate it into existing unit test solution which might be built using some other mockup libraries (like NSubstitute). Please correct me if my assumption about FakeItEasy dependancy was incorrect.

Nevertheless, current fake-xrm-easy implementation doesn't incur too much unnecessary features to cases where only IOrganizationService mockup is sufficient that we couldn't handle it but adding also integration tests into the same NuGet package could mitigate usefullness and easy approachability of the current fake-xrm-easy unit testing library.

**Comment by jordimontana82** [comment]
Dependency on FakeItEasy is at the core of FakeXrmEasy (in part, that was the reason it was named that way :) ).

If you look at [this](https://github.com/jordimontana82/fake-xrm-easy/blob/6ab2f57948256fae922e9d7ce864e88a09dac500/FakeXrmEasy.Shared/XrmFakedContext.Crud.cs) you'll see even really basic operations like CRUD, are also using FakeItEasy.

If you look at the codebase, the heavy work was around mocking the IOrganisationService, and the Plugin and CodeActivity mocks just add a little bit on top of that.

I totally agree though it doesn't make much sense to incorporate integration testing mocks here because in that case tests should be run against a real Organisation Service. I was thinking of initially adding them here to add some kind of helper logic to implement TearDown methods, which would clean all the testing data for you on the integration environment once the test is finished.

But after thinking a lot on it, I believe it is much more easier and safer to setup a VM environment where you will spin up a VM with a CRM integration test environment, execute integration tests, and stop it when done. 

By doing that there won't any interference or clashes between integration tests and therefore no need to worry about the data that was created there.

**Comment by jordimontana82** [comment]
Hi @teppolainio 

I´m going to close this if you are happy as it makes more sense to have a separate NuGet package for integration testing.
