### ISSUE TITLE
Stage is not populated correctly when using SerializedPluginProfile

### ISSUE THREAD

**Issue by rajyraman** [jordimontana82/fake-xrm-easy#130]
Actual stage is 20 (Pre), but when using "_GetContextFromSerialisedCompressedProfile_" stage seems stuck at 0.

From FakeXrmEasy:
![image](https://cloud.githubusercontent.com/assets/5035266/23148544/95329abe-f83a-11e6-81d0-762c24e1ee1f.png)

Actual:
![image](https://cloud.githubusercontent.com/assets/5035266/23148560/abb998aa-f83a-11e6-9515-8de0d415467b.png)

**Comment by jordimontana82** [comment]
Thx Raj!

Could you please copy & paste the compressed serialilsed string so that I could debug it pls?

**Comment by rajyraman** [comment]
The profile has data from production, so I will try to reproduce this issue on a trial instance and attach the profile.

**Comment by rajyraman** [comment]
Fixed this issue. Has to do with the order of the fields during deserialisation. Will submit PR soon.

**Comment by jordimontana82** [comment]
Awesome! Thx a mill Natraj
