### ISSUE TITLE
OrganizationServiceContext doesn't handle 'where' queries on Id // <entity>Id

### ISSUE THREAD

**Issue by LazerFX** [jordimontana82/fake-xrm-easy#133]
First off, I'm using the Entity proxies generated from [XrmToolkit](https://xrmtoolkit.com/).  These include the standard Dynamics CRM `Account` entity.  The entities all inherit from Entity, and include the normal features you expect to make them usable with Dynamics CRM Linq providers.

I've tried initialising using Initializer syntax (More entities elided for clarity, and `BaseFakedContext` is a property on a POCO, TestIds is a public static class, with nested public static classes and public static readonly Guid values), like:
```c#
    var BaseFakedContext = new XrmFakedContext();
    Entity hsAccount = new Account
    {
        Id = TestIds.Account.HS,
        // AccountId = TestIds.Account.HS,
        AccountName = "HS",
        AccountNumber = "CN-123456"
    }
    var initialisationData = new List<Entity>() {
        hsAccount
    };
    BaseFakedContext.Initialize(initializationData);
```
And by create, like:
```c#
    var BaseFakedContext = new XrmFakedContext();
    Entity hsAccount = new Account
    {
        Id = TestIds.Account.HS,
        // AccountId = TestIds.Account.HS,
        AccountName = "HS",
        AccountNumber = "CN-123456"
    }
    var initialisationData = new List<Entity>() {
        hsAccount
    };
    BaseFakedContext.Initialize(new List<Entity>());
    var orgService = BaseFakedContext.GetOrganizationService();
    foreach (var entity in initialisationData) {
        orgService.Create(entity);
    }
```
I then generate a plugin context, and run my plugin:
```c#
    var context = BaseFakedContext.GetDefaultPluginContext();
    context.InputParameters = new ParameterCollection
    {
        new KeyValuePair<string, object>("Target", target)
    };
    context.Stage = 40;
```
Target is an entity that I create in the process, using a BaseFakedContext.GetOrganizationService().Create(target) method call.  The custom entity has a 1:N reference to the Account entity, called Company, with an EntityReference pointed to the TestIds.Account.HS Account.  I populate this using the I then run the plugin:
```c#
    BaseFakedContext.ExecutePluginWithConfiguration<OnPostSaveTailoredTopUpRating>();
```
In the plugin, I have the following code:
```c#
    var companies = ctx.CreateQuery<Account>();
    var companiesWhere = companies.Where(a => a.AccountId.Equals(ttr.Company.Id));
    var companiesNames = companiesWhere.Select(a => a.AccountName);
    var companyName = companiesNames.First();
```
I broke it down to this level to enable me to identify where the issue was.  The first line, run in 'preview' shows that there exists an Account, and the Guid matches the global Guid set.  `ttr` is set to the Target, passed into the entity.  I can check in instant that the values of the a.AccountId and ttr.Company.Id match.

`companiesWhere`, when evaluated, gives "Enumeration yielded no results" when evaluated.

The issue is that if I add `ToList()` at the end of `ctx.CreateQuery<Account>()`, the whole thing evaluates correctly.

Where am I going wrong in setting up the context, or configuring the test?

**Comment by jordimontana82** [comment]
That's interesting, if you try using the equals operator rather than the method?

    a => a.AccountId == ttr.Company.Id

Does it work?

And... if you use the query syntax as opposed to the fluent one? i.e.

var ttrId = ttr.Company.Id;
var companyName = (from a in ctx.CreateQuery<Account>()
                                    where a.AccountId == ttrId
                                    select a).FirstOrDefault();

That one should work. 

Will have a look at it anyway whenever I get a chance :)

**Comment by LazerFX** [comment]
Equals operator was tried, and fluent syntax was what I started with when I noticed the issue.

I'm not in the office now, but tomorrow I'm going to try to put together a minimum reproduction solution, and submit it - if I can make a test case on fake-xrm-easy, I will do.

**Comment by LazerFX** [comment]
I've created tests for this in a cloned repository - sorry if I'm not doing this right, I'm not that familiar with github netiquette.  It's available at bfb3c64c166226d7e71aeefbeb7b86612d279535 

Please let me know if there's anything more I can provide.  The entities were generated with XrmToolkit, which is a paid-for Dynamics Crm Visual Studio integration provider (Easier JS integrations, plugin registration, cross-organisation transfer of plugins/files, etc.).  The entities don't depend on anything from XrmToolkit themselves.

**Comment by LazerFX** [comment]
I think I've found the issue - in `EntityExtensions.cs`, the function `public static Entity Clone(this Entity e, Type t)` iterates through all the attributes, and sets the Id of the Entity.  For some reason, however, the Crm Generated entities include an Id attribute in the Attributes list; however, the XrmToolkit entities specifically _remove_ those attributes.

I'll keep investigating why, and potentially raise a bug with them.  The issue appears to raise its head when it comes to generating the Lambda equivalent, it iterates on the `entityId` attribute, rather than the Id Entity value.

**Comment by LazerFX** [comment]
The difference is in the generated Entity Attribute ID getter/setter.  From the XrmToolkit:

```C#
///<summary>
///<para>Key Property (Uniqueidentifier)</para>
///<para>Logical Name: cosl_schemetypesid</para>
///</summary>
[AttributeLogicalNameAttribute("cosl_schemetypesid")]
public Guid SchemeTypesId
{
	get
	{
		return this.Id;
	}
	set
	{
		this.Id = value;
	}
}
```

From the Dynamics CRM generated entities:

```C#
/// <summary>
/// Unique identifier of the product specified in the order.
/// </summary>
[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("salesorderdetailid")]
public System.Nullable<System.Guid> SalesOrderDetailId
{
	get
	{
		return this.GetAttributeValue<System.Nullable<System.Guid>>("salesorderdetailid");
	}
	set
	{
		this.OnPropertyChanging("SalesOrderDetailId");
		this.SetAttributeValue("salesorderdetailid", value);
		if (value.HasValue)
		{
			base.Id = value.Value;
		}
		else
		{
			base.Id = System.Guid.Empty;
		}
		this.OnPropertyChanged("SalesOrderDetailId");
	}
}
```

I'm going to see if I can alter the XrmToolkit generated entities, however as these entities work with Dynamics CRM, is there anything that can be done to fake-xrm-easy to handle this format?

**Comment by jordimontana82** [comment]
Thanks for raising this.

Does this happen with the Id property only?

**Comment by LazerFX** [comment]
As far as I can tell, yes - all the others go into the attributes bag as expected.  I can't figure out why the xrm toolkit handles id so differently, but it seems to be the only attribute it does.

**Comment by jordimontana82** [comment]
Right, thx.

If it is only the .Id then that's fine. I would be concerned if the same happened to other attributes as it would introduce loads of breaking changes to cater for XrmToolkit... which is not the case :)

**Comment by LazerFX** [comment]
No, it's just Id, and to be fair, adding the Partial class as-above has resolved the issue for me.  I've raised this to the XrmToolkit team, as I personally believe that the values not being in the attribute bag is a bug... it just happens to function properly with Dynamics CRM :D

**Comment by jordimontana82** [comment]
I'll close this issue if you are happy as crmsvcutil generates the Id property as expected so it is not an issue. P
