### ISSUE TITLE
PluginContext.Stage not taken into account on Create?

### ISSUE THREAD

**Issue by benArrayx** [jordimontana82/fake-xrm-easy#134]
Hi Jordi, I usually set my plugin execution stage to Post-Operation, and thus I'm trying to replicate this in my unit tests. After having got the context with GetDefaultPluginContext, I'm setting the Stage value to 40. Inside my plugin, I'm expecting that the Target will have a valid Id attribute, since that's how CRM works. However, with Fake Xrm Easy, I see that the Target id attribute contains a Guid.Empty value.

Here's the code to test this:

`public class AccountCreate : IPlugin
        {
            public void Execute(IServiceProvider serviceProvider)
            {
                var context = (IPluginExecutionContext)serviceProvider.GetService(typeof(IPluginExecutionContext));

                var service = serviceFactory.CreateOrganizationService(context.UserId);
                Entity target = context.InputParameters["Target"] as Entity;
                Guid id = target.Id;
                if (id == Guid.Empty)
                    throw new Exception("Target Id is empty!");

                target["name"] = "Updated name";
                service.Update(target);
            }
        }

        [Fact]
        public void When_executing_a_post_operation_plugin_the_id_exists()
        {
            var context = new XrmFakedContext();

            var pluginContext = context.GetDefaultPluginContext();
            pluginContext.InputParameters = new ParameterCollection()
            {
                new KeyValuePair<string, object>("Target", new Entity("account"))
            };
            pluginContext.Stage = 40;

            context.ExecutePluginWith<AccountCreate>(pluginContext);
        }`

Regards, Ben

**Comment by jordimontana82** [comment]
Hi Ben,

I think the best option in this case is to assign the Guid yourself, cause for some scenarios it might need to match certain entities in-memory.

By default, the Entity constructor assigns a Guid.Empty.

I would just do this:

    [Fact]
    public void When_executing_a_post_operation_plugin_the_id_exists()
    {
        var context = new XrmFakedContext();

        var pluginContext = context.GetDefaultPluginContext();
        var account = new Entity("account");
        account.Id = Guid.NewGuid();
        pluginContext.InputParameters = new ParameterCollection()
        {
            new KeyValuePair<string, object>("Target", account)
        };
        pluginContext.Stage = 40;

        context.ExecutePluginWith<AccountCreate>(pluginContext);
    }`

**Comment by benArrayx** [comment]
Hi Jordi, I did do that initially but it doesn’t work in my case, given that the plugin changes some values of the entity and does a further update, however on the plugin update an error is thrown because the “entity with Id xxx does not exist”. Clearly, that would be a different possible solution to this – that FakeXrm saves the entity to its internal store before calling the plugin. Then I'd have no problem passing the Id.

Regards, Ben

**Comment by jordimontana82** [comment]
Hi Ben,

Ok I get you know :) 

I think for unit testing this scenario would be ideal to initialize the Account entity record via ctx.Initialize(), and then pass the same entity in the Target.

This is because stage 40 is a post-operation, so whenever CRM gets to call your plugin the record already exists in the  because something else already created it. So rather than force the plugin execution to create the record, the plugin execution would assume the record exists previously (via .Initialize).

**Comment by benArrayx** [comment]
Hi Jordi, OK I see the logic. While the use of ctx.Initialize() is obvious to me when testing Updates, this confused me in the case of Creates. I take your point that ‘something’ else has created the record before the plugin is fired in the case of Stage 40 – I was expecting that ‘something’ to be the FakeXrmEasy internals in the case of a Create message, but the ‘something’ is actually me via ctx.Initialize() – makes perfect sense, thanks for taking the time to explain!

**Comment by jordimontana82** [comment]
No worries, you're very welcome :)

**Comment by ilyasgndz** [comment]
Even though it makes sense to create the target and add it to the context, it should be nice to if fakexrm creates the entity when plugin message is create

**Comment by jordimontana82** [comment]
Hi @ilyasgndz, I definitely see that feature for whenever you want to run the context with Pipeline Simulation mode enabled, cause enabling it by default would introduce regressions. 

In that scenario (Pipeline simulation enabled) you might want to have different plugins registered on different messages and therefore it would be nice to react on those messages. 

From a unit testing perpestive (unit testing logic in a single plugin), it is just cleaner to have it switched off and just test the Target entity is modified / updated as desired after the plugin is executed.
