### ISSUE TITLE
FakeXRMEasy stores references to entity variables instead of copies of entity variables

### ISSUE THREAD

**Issue by benArrayx** [jordimontana82/fake-xrm-easy#135]
Hi Jordi, something that's come up for me while writing unit tests is the observation that when you do a service.Create(entity) call, FakeXrmEasy is storing a reference to the entity variable passed to that call, and that later changes to that variable are therefore reflected when the entity is retrieved from the service, even if those changes have not been saved to the service. Obviously, this is not as per CRM behaviour.

Here's an example:

`
[Fact]
        public void FakeXrmEasy_doesnt_store_references_to_variables()
        {
            var context = new XrmFakedContext();
            var service = context.GetFakedOrganizationService();

            //create an account and then retrieve it with no changes
            Entity newAccount = new Entity("account");
            newAccount["name"] = "New Account";

            newAccount.Id = service.Create(newAccount);

            Entity retrievedAccount = service.Retrieve("account", newAccount.Id, new Microsoft.Xrm.Sdk.Query.ColumnSet(true));
            Assert.True(retrievedAccount.Attributes.Contains("name"));

            //do the same as above, but this time clear the attributes - see that when retrieved, the retrieved entity does not contain the name attribute
            Entity newAccount1 = new Entity("account");
            newAccount1["name"] = "New Account1";

            newAccount1.Id = service.Create(newAccount1);
            newAccount1.Attributes.Clear();

            Entity retrievedAccount1 = service.Retrieve("account", newAccount1.Id, new Microsoft.Xrm.Sdk.Query.ColumnSet(true));
            Assert.True(retrievedAccount1.Attributes.Contains("name"));

            //third time around, change the name to something new, the retrieved entity should not reflect this change
            Entity newAccount2 = new Entity("account");
            newAccount2["name"] = "New Account2";

            newAccount2.Id = service.Create(newAccount2);
            newAccount2["name"] = "Changed name";

            Entity retrievedAccount2 = service.Retrieve("account", newAccount2.Id, new Microsoft.Xrm.Sdk.Query.ColumnSet(true));
            Assert.True(retrievedAccount2["name"].ToString() == "New Account2", $"'{retrievedAccount2["name"]}' was not the expected result");
        }`

Sorry that I can't get the editor to format all the code properly! Not sure what I'm doing wrong there.

Regards, Ben

**Comment by jordimontana82** [comment]
Hi Ben,

Good point. Yeah, definetely we could change it to use a .Clone extension method which also use for queries, which also return copies of the entities in/memory.

Thx for raising this.

**Comment by benArrayx** [comment]
Hi Jordi, after this update I'm not seeing the default attributes added to the entity on save which were there before, eg. createdon, createdby, modifiedon, modifiedby, statecode. I can see that you have a method to create these in XrmFakedContext.AddEntityDefaultAttributes(), I assume that after this change it's not the same entity getting returned as that which has the default attributes added?

**Comment by benArrayx** [comment]
Just to confirm, if I revert to version 1.22.1 I can see that those default attributes are added, therefore this must be a regression from this Issue.

**Comment by jordimontana82** [comment]
Hi Ben,

That's weird, I'll double check

**Comment by jordimontana82** [comment]
Hi Ben,

Just added 2unit tests. This looks good to me with latest.

**Comment by benArrayx** [comment]
Sorry Jordi, my bad on this one. I was previously testing for these values after having completed a save, since before you made the changes to clone the entity instead of storing a reference, these fields were present. Now, as I see from your tests, and as is reasonable given the change, one has to retrieve the entity from storage to see those fields! I will update my tests…
