### ISSUE TITLE
Crahs running test on TFS Server Build

### ISSUE THREAD

**Issue by EduAragon** [jordimontana82/fake-xrm-easy#137]
Hi Jordi.
I am fan of fake-xrm -easy !!  I am working to add a new test on plugins

Anyway, this is not an issue for fake-xrm-easy is a feedback because i have experienced a weird delays (I mean hours) when i try to check in my test on TFS Server.
Our build in TFS  is setting to run and validate the TEST before the checkin.
I waste a lot of time  "test-error methodology", after all.  I remove the nuget  Xunit.runner.visualstudio   and the test runs perfectly on my project and on tfs.

Any Idea about this?

My best, Eduardo

**Comment by jordimontana82** [comment]
Hi Edu!

Awesome! :+1: 

Are you using xunit.runner.visualstudio version 2.1.0 or 2.2.0? 

2.2.0 was released last month and had issues with it too. So just try referencing version 2.1.0 in the packages.config and see how it goes.

Hope this helps!

**Comment by EduAragon** [comment]
Jordi, 

I got xunit.runner.visualstudio.2.1.0. I Guess TFS become mad cause is a TEST proyect but without any testmethod.

I  run all test with Microsoft VisualStudio.

Thanks.

**Comment by jordimontana82** [comment]
Oki! Any questions let me know.
