### ISSUE TITLE
Using Pligns that use BasePlugin with ExecutePluginWithTarget<> does not work

### ISSUE THREAD

**Issue by rjarquin** [jordimontana82/fake-xrm-easy#138]
When using context = XrmFakedContext()
and then context,ExcutePluginWithTarget<Plugin>(target);
When Plugin inherits from a BasePlugin it gives me an error.

must be a non-abstract type with a public parameter-less constructor in order to use its parameter 'T'

**Comment by jordimontana82** [comment]
Please, just add a parameter-less constructor to your plugin as it suggests.


Ex, if your plugin is called 

    public class MyAmazingPlugin: BasePlugin

And BasePlugin in turn implements IPlugin

Then the only thing you need is

    public class MyAmazingPlugin: BasePlugin {
        public MyAmazingPlugin() {

        }
    }

**Comment by rjarquin** [comment]
Awesome thanks, I wasn't sure where to add it.

**Comment by rjarquin** [comment]
Just as a note, I also had to add an empty constructor to the BasePlugin Class.
If not the MyAmazinPlugin Class woud give an error.
So I added:

public BasePlugin(){
}
