### ISSUE TITLE
2013 and 2015 NuGet Packages are missing Assemblies

### ISSUE THREAD

**Issue by DigitalFlow** [jordimontana82/fake-xrm-easy#14]
Hey @jordimontana82,

I just tried adding the new NuGet packages for CRM 2013 and 2015 to a project and found, that those NuGet packages don't include the FakeXrmEasy Assembly.
They should be added for those packages to be used.

Kind Regards

**Comment by DigitalFlow** [comment]
Great! Thanks @jordimontana82 :)

**Comment by jordimontana82** [comment]
Welcome!
