### ISSUE TITLE
How to get the OrganizationServiceProxy

### ISSUE THREAD

**Issue by leeh14** [jordimontana82/fake-xrm-easy#140]
I noticed that the GetOrganizationServiceProxy was commented out. Is there no other way to grab a mock of the OrganizationServiceProxy. Is there a better way to mock the OrganizationServiceProxy? Or is there a hidden way to convert an IOrganizationService to an OrganizationServiceProxy ?

**Comment by jordimontana82** [comment]
It was removed on purpose as OrganizationServiceProxy already implements IOrganizationService. 

Basically it is a best practice approach to refactor your code using references to IOrganizationService only. 
Doing it that way, you could pass the fake organizationservice from ctx.GetOrganizationService() project to your Unit tests, or a real OrganizationServiceProxy in the project which is unit tested, either manually or via dependency injection.
