### ISSUE TITLE
Implementing RetrieveOptionSetMetadataRequest Propert Set issues.

### ISSUE THREAD

**Issue by chuckmag** [jordimontana82/fake-xrm-easy#144]
My team ran into an issue with not being able to mock a RetrieveOptionSetMetadataRequest, since it hasn't been implemented yet, so I thought why not contribute to this great library!

Problem I am having now is finding out it is hard to work with the RetrieveOptionSetMetadataResponse class and setting the OptionSetMetadata property.  That property doesn't seem to have any setter at all and I could not use other Reflection tricks to set it.

Something like this,

`
            var response = new RetrieveOptionSetResponse();
            response.GetType().GetProperty("OptionSetMetadata").SetValue(response, optionSetMetadata, null);`

Throws this : System.ArgumentException : Property set method not found.

I got this line of code from some googling and seeing that it seemed this was already used with success for a similar use case, in the RetrieceEntityRequestExecutor.Execute method

`
                //AttributeMetadata is internal set in a sealed class so... just doing this
                entityMetadata.GetType().GetProperty("Attributes").SetValue(entityMetadata, computedAttributeMetadataList.ToArray(), null);`

Is there something I am missing?

**Comment by jordimontana82** [comment]
Hi @chuckmag 

Thanks for your feedback, much appreciated.

Please could you try wrapping the property via a ParameterCollection first rather just assigning it directly to the response as shown [here](https://github.com/jordimontana82/fake-xrm-easy/blob/a43cb03fdd1a3e2d7d8a519bd835f5f1ab5133a9/FakeXrmEasy.Shared/FakeMessageExecutors/RetrieveEntityRequestExecutor.cs#L131-L139) ?

**Comment by chuckmag** [comment]
That did it! I couldn't find anything explaining that magic, I was really close to just trying it though and should have.

Thanks for the help and expect a pull request soon.
