### ISSUE TITLE
Invalid Cast Exception

### ISSUE THREAD

**Issue by benArrayx** [jordimontana82/fake-xrm-easy#147]
Hi Jordi, I've detected a really weird bug which happened between version 1.19.1 and 1.19.2. The bug can be seen with the following test:

`        [Fact]
        public void InvalidCastTest()
        {
            XrmFakedContext context = new XrmFakedContext();
            context.ProxyTypesAssembly = Assembly.GetAssembly(typeof(Account));
            IOrganizationService service = context.GetFakedOrganizationService();

            Account a1 = new Account() { Id = Guid.NewGuid(), Name = "a1" };
            Account a2 = new Account() { Id = Guid.NewGuid(), Name = "a2" };
            Account a3 = new Account() { Id = Guid.NewGuid(), Name = "a3" };

            Contact c1 = new Contact() { Id = Guid.NewGuid(), FirstName = "c1", ParentCustomer = a1 };
            Contact c2 = new Contact() { Id = Guid.NewGuid(), FirstName = "c2", ParentCustomer = a2 };
            Contact c3 = new Contact() { Id = Guid.NewGuid(), FirstName = "c3", ParentCustomer = a3 };
            
            context.Initialize(new List<Entity>() {
                c1, c2, c3, a1, a2, a3
            });

            QueryExpression query = new QueryExpression()
            {
                EntityName = "contact",
                ColumnSet = new ColumnSet(true),
                Criteria = new FilterExpression()
                {
                    FilterOperator = LogicalOperator.And,
                    Conditions =
                    {
                        new ConditionExpression("parentcustomerid", ConditionOperator.Equal, a2.Id)
                    }
                }
            };

            EntityCollection ents = service.RetrieveMultiple(query);
            Assert.Equal(1, ents.Entities.Count);
        }`

The exception thrown is:

`[xUnit.net 00:00:01.9549889]       System.InvalidCastException : Specified cast is not valid.
[xUnit.net 00:00:01.9571513]       Stack Trace:
[xUnit.net 00:00:01.9579099]            at lambda_method(Closure , Entity )
[xUnit.net 00:00:01.9585915]            at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
[xUnit.net 00:00:01.9591532]            at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
[xUnit.net 00:00:01.9597298]            at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
[xUnit.net 00:00:01.9602174]            at FakeXrmEasy.FakeMessageExecutors.RetrieveMultipleRequestExecutor.Execute(OrganizationRequest req, XrmFakedContext ctx)
[xUnit.net 00:00:01.9607926]            at FakeXrmEasy.XrmFakedContext.<>c__DisplayClass89_0.<FakeRetrieveMultiple>b__0(QueryBase req)
[xUnit.net 00:00:01.9613049]            at FakeItEasy.ReturnValueConfigurationExtensions.<>c__DisplayClassd`2.<ReturnsLazily>b__c(IFakeObjectCall call)
[xUnit.net 00:00:01.9618745]            at FakeItEasy.Configuration.RuleBuilder.ReturnValueConfiguration`1.<>c__DisplayClass8.<ReturnsLazily>b__7(IInterceptedFakeObjectCall x)
[xUnit.net 00:00:01.9624698]            at FakeItEasy.Configuration.BuildableCallRule.Apply(IInterceptedFakeObjectCall fakeObjectCall)
[xUnit.net 00:00:01.9630865]            at FakeItEasy.Core.FakeManager.ApplyRule(CallRuleMetadata rule, IInterceptedFakeObjectCall fakeObjectCall)
[xUnit.net 00:00:01.9636305]            at FakeItEasy.Core.FakeManager.FakeItEasy.Core.IFakeCallProcessor.Process(IWritableFakeObjectCall fakeObjectCall)
[xUnit.net 00:00:01.9641386]            at FakeItEasy.Creation.CastleDynamicProxy.CastleDynamicProxyGenerator.ProxyInterceptor.Intercept(IInvocation invocation)
[xUnit.net 00:00:01.9646140]            at Castle.DynamicProxy.AbstractInvocation.Proceed()
[xUnit.net 00:00:01.9650945]            at Castle.Proxies.ObjectProxy.RetrieveMultiple(QueryBase query)`

This bug only happens when using a ProxyTypesAssembly - with plain entities I could not replicate it. I am using the GeneratedCode.cs file I pulled from your solution as the ProxyTypes.

The bug occurs in versions 1.19.2 and above, in 1.19.1 there is no problem. This is weird, as I checked your 1.19.2 release and it seemed to be an update of version numbers only, I can't see any code changes.

I am using FakeItEasy 1.25.3.

**Comment by jordimontana82** [comment]
Hi Ben, 

I think you need to setup the lookup as an entityreference.

I.e.

Rather than this:

    Contact c1 = new Contact() { Id = Guid.NewGuid(), FirstName = "c1", ParentCustomer = a1 };

Just do this

    Contact c1 = new Contact() { Id = Guid.NewGuid(), FirstName = "c1", ParentCustomer = a1.ToEntityReference() };

**Comment by benArrayx** [comment]
Hi Jordi, actually I see that I hadn't set the ProxyAssembly to correctly use the classes in the GeneratedCode.cs file. If I switch the ProxyAssembly to use that file then everything works OK. I am using custom generated entity files, the ParentCustomer property takes an Entity argument and assigns the EntityReference itself inside the property setter.

I can see that there was a commit 'Changing type comparison to be based on the left hand side type of the expression if using ProxyTypesAssembly' on the 14/12/2016 (Commit ad2019d0) which I'm pretty sure is causing this issue, since the Exception is thrown on line 26 of RetrieveMultipleRequestExecutor.cs (the line is `var list = linqQuery.ToList();`). Just before this, `XrmFakedContext.TranslateQueryExpressionToLinq` is called which was substantially changed in the commit mentioned.

I'm unsure about how to dig into this any further and get more specific info to debug this issue. Clearly there is something happening regarding the ProxyAssembly and the changes in the commit mentioned since the version 1.19.1 works without problems.

Any tips?

**Comment by jordimontana82** [comment]
Hi Ben,

Indeed, there were quite a lot of changes to support type checking from that version onwards. Before that types were just "guessed" based on the values you had in your entity records rather than looking at the property getters/setters. This had issues like trying to convert values like "12.1" into date time values where in fact they were plain strings.

So, when using early bound entities (via ProxyTypesAssembly or by just calling .Initialize with early bound types), type checking will be based on the left hand side of the expression, meaning it should match the property.

This issue has more to do with the way crmsvcutil / the developer toolkit generates types. What crmsvcutil version do you use? For example, in CRM 2015 that property was being generated as an entity reference rather than as an Entity. Which makes total sense to me. This property is a lookup, not an entity itself.

I know there were buggy versions of the developer tooltik / crmsvcutil generating other types (and types that weren't even compiling so... :P )

So the best option would be to fix it in the generated file, and check if that is a bug in the generated code itself.

    [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentcustomerid")]
		public Microsoft.Xrm.Sdk.**EntityReference** ParentCustomerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("parentcustomerid");
			}
			set
			{
				this.OnPropertyChanging("ParentCustomerId");
				this.SetAttributeValue("parentcustomerid", value);
				this.OnPropertyChanged("ParentCustomerId");
			}
		}

**Comment by jordimontana82** [comment]
Or fix it like you are doing in your fork :)

**Comment by benArrayx** [comment]
Done!

**Comment by jordimontana82** [comment]
Excellent! Well done!
