### ISSUE TITLE
Out of the box CRM functionality emulation

### ISSUE THREAD

**Issue by AleksandrRogov** [jordimontana82/fake-xrm-easy#149]
Hi Jordi,

Do you think it's a good idea to add OOTB functionality emulation in fake-xrm-easy or it will be over the top for a mock project?
For example, there is an invoice in CRM and the plug-in adds invoice details to it. When the process of adding details finished it retrieves and saves somewhere else a total amount from the invoice which was automatically calculated in CRM.
Right now, this scenario cannot be simulated in fake-xrm-easy, so the developer will have to write stubs which will be triggered in a specific moment and return the value that will have to be calculated inside the test. And this calculation will generally be exactly the same as CRM does it. 
In my opinion, most logical way will be to add a calculation inside fake-xrm-easy. At least, it will be much easier than to write mega advanced stubs for IOrganizationService in test classes.

Please let me know what you think.

Thanks for your time,
Aleksandr

P.S. I've already added that invoicedetail-invoice calculation inside my local repository and it works perfectly.
What I did is this:
`XrmFakedContext.Crud.cs`
```c#
protected internal void AddEntityWithDefaults(Entity e)
{
    var clone = e.Clone(e.GetType());
    AddEntityDefaultAttributes(clone);
    AddEntity(clone);
    //it will be better to move to a separate class
    EmulateOutOfTheBoxFunctionality(clone);
}

/// <summary>
/// Emulates OOTB functionality
/// </summary>
/// <param name="e">Entity</param>
protected internal void EmulateOutOfTheBoxFunctionality(Entity e)
{
    //this switch is a quick and dirty solution    
    switch (e.LogicalName)
    {
        case "invoicedetail":
            {
                //business process...
                break;
            }
        case "invoice":
            {
                //these kind of things could be saved somewhere in app.config
                e["invoicenumber"] = "INV-" + DateTime.Now.Ticks;
                break;
            }
    }
}
```

**Comment by jordimontana82** [comment]
Hi Aleksandr,

Nice idea. Yeah, it would be good to have this I think. I would put it to a separate class though and make it configurable possibly via a settingin the app.config (this might not be needed for plain custom entities for example).

Also, how were you thinking of adding custom code like "INV-" + DateTime.Now.Ticks. Surely that is a simple example but there will be initialisations a bit more complex for sure so...

Another option is to make the method virtual so anyone can override it to their needs?

What do you think?

**Comment by AleksandrRogov** [comment]
Hi Jordi,

Yes, this must be in a separate file (even in a separate folder), the one that I did is a quick'n'dirty solution for my needs, that's why I did not include it in a PR. I am not sure yet how to design it, so it will be a nice and extendable solution, we need to brainstorm it.
DateTime.Now.Ticks is just for fun there. I would maybe try to do auto-numbering by adding rules in app.config. But before doing that there is a good question if the project needs to have this feature. I do not know if anyone checks what auto-number generated in their plug-ins.

Thanks

**Comment by jordimontana82** [comment]
Hi Aleksandr,

Yeah no worries. I think the easiest and most extandable solution would to give the option to inject a "data initialisation service", something that would just take an entity record as an input and it will populate with as many attributes as you wanted. But it's up to whoever is injecting that service to decide how to populate those. 

I would not go for the app.config route as could end up with many many rules for the OOB entities and it might be difficult to maintain / read.

The same data initialisation service could be use to automatically populate an entity record based on the default values from metadata, for example (i.e. use 919787000 for this option set value field whenever .Create is called) without having to specify it on every unit test, cause that is what would happen in a real CRM database / app.

**Comment by jordimontana82** [comment]
Hi Aleksandr!

I refactored the entity initialisation logic into a separate class. Now it should be open enough to be easily replaced by any custom initialisation service to replace the default initialisation by injecting another implementation of IEntityInitializerService into the context.

**Comment by AleksandrRogov** [comment]
Hi Jordi,
So, does it make sense to implement OOTB functionality in that `DefaultEntityInitializerService` in the fake-xrm-easy project? Or do you want everyone to add initializers that they need inside their testing projects?

**Comment by AleksandrRogov** [comment]
I see one problem here though. If the logic needs to be added into `DefaultEntityInitializerService`, then it needs to have an access to already existing `Data` set using `XrmFakedContext.Initialize` method, or to the `FakedService`, because some attributes for some entities are populated based on other entities. For example, all amounts in `invoicedetail` depend on `productpricelevel`  and `uom`; all amounts in `invoice` depend on related `invoicedetail` amounts and so on...
Here's an example that emulates CRM behaviour that happens when `invoicedetail` created and attached to the `invoice`:

```c#
var quantity = e.GetAttributeValue<decimal>("quantity");
if (quantity <= 0m)
    return;

var pricePerUnit = e.GetAttributeValue<Money>("priceperunit");
if (pricePerUnit == null || pricePerUnit != null && pricePerUnit.Value == 0m)
    return;

decimal extendedAmount = Math.Round(pricePerUnit.Value * quantity, 2);

//e - is an invoicedetail object passed to the method as an input parameter
e["amount"] = new Money(extendedAmount);

var manualDiscount = e.GetAttributeValue<Money>("manualdiscountamount");
if (manualDiscount != null)
    extendedAmount -= manualDiscount.Value;

var tax = e.GetAttributeValue<Money>("tax");
if (tax != null)
    extendedAmount += tax.Value;

e["extendedamount"] = new Money(extendedAmount);

var invoiceReference = e.GetAttributeValue<EntityReference>("invoiceid");
if (invoiceReference != null)
{
    //as you can see here it needs to have an access to the existing invoice that set in
    //"invoiceid" lookup field
    var invoice = Service.Retrieve(invoiceReference.LogicalName, invoiceReference.Id, new ColumnSet(true));
    var totalAmount = invoice.GetAttributeValue<Money>("totalamount");
    if (totalAmount == null)
        totalAmount = new Money(0m);

    totalAmount.Value += ((Money)e["extendedamount"]).Value;

    invoice["totalamount"] = totalAmount;
    Service.Update(invoice);
}
```
And this is an example when the attribute `ispriceoverridden` in `invoicedetail` set to `true` (so, the price set manually). When it is set to `false` the code will be more complicated because it calculates all amounts based on the `product`, `pricelevel` and `uom`.

**Comment by jordimontana82** [comment]
Hi Aleksandr!

The intention was to move that to a separate service to keep it easy to maintain, and also to leave it open for everybody to initialise the records on their own.  So yeah, the intention was to leave users to use the initializers they want ( I personally don't need them right now cause I'm mainly working with custom entities, that's why).

However, it would be amazing if you would like to add a new OOTB initializer, similar to the Default one, but with the logic like you shown above. One initializer can also have a reference to another initializer, so say the OOTB could call the Default one on .Initialize. That is to keep them modular as opposed to a gigantic single implementation. 

We could extend the definition to pass the XrmFakedContext as a parameter on the .Initialize method, and you could use that to get any data and/or get a reference to the fake service again.

Sounds good? :)

**Comment by AleksandrRogov** [comment]
Hi Jordi,
Of course it sounds good! (Moreover, you're an architect here :), I will do as you say).

One thing is not clear for me yet, how to call a corresponding initializer for a specific entity when we do it your way? I assume, in order to keep modularity, there should be initializers for each entity, for example `InvoiceDetailInitializer` that will perform OOTB logic for `invoicedetail` entity; but how can it be called in `DefaultEntityInitializerService`? 

Maybe we can do it the same way as you do it for FakeMessageExecutors? Then, we will need to introduce a similar method `GetResponsibleRequestType` in the Initializer Interface that will check the entity name and run a corresponding Initilizer.

**Comment by jordimontana82** [comment]
Hi Aleksander,

Sorry for the delay. The entity instance has a LogicalName property which is the entity name, so, for instance, from the DefaultEntityInitializer we could call InvoiceDetailInitializer and others based on that?

**Comment by AleksandrRogov** [comment]
There are multiple ways to call other initializers. For example, DefaultEntityInitializer could have a dictionary with keys that represent entity names and values with initializers; or simply DefaultEntityInitializer could have `switch...case...`. Which one do you prefer?

**Comment by jordimontana82** [comment]
+1 to the Dictionary. Also I would just use the default if there was no initializer for a given entity name?

**Comment by jordimontana82** [comment]
Hi @AleksandrRogov !

Just wondering if you had any progress on this? :)

**Comment by AleksandrRogov** [comment]
Hi @jordimontana82,

I've just covered a small portion of ootb logic for invoices. Just to start with something, I may add a pull request if you'd like, maybe other developers will extend it further.

Thanks

**Comment by jordimontana82** [comment]
Thanks Aleksander,

Yeah, if you coud issue a PR it would be good 👍 

Thanks!

**Comment by jordimontana82** [comment]
@AleksandrRogov  this PR has been open for 2 years so closing it... let me know if you want to reopen it. Thanks!
