### ISSUE TITLE
Unable to cast object of type 'Microsoft.Xrm.Sdk.AliasedValue' to type 'System.String' in LinkEntity query

### ISSUE THREAD

**Issue by benArrayx** [jordimontana82/fake-xrm-easy#157]
Hi Jordi, you can find a test for this problem here: https://github.com/benArrayx/fake-xrm-easy/commit/e4cfc91194b79fd26dfc8d9d229c14abe5f64fbf

Basically, I'm trying to run a QueryExpression using conditions on LinkEntities and getting the error 'Unable to cast object of type 'Microsoft.Xrm.Sdk.AliasedValue' to type 'System.String''.

I can see that in your method TranslateConditionExpressionLike() in XrmFakedContextQueries.cs, on line 1011 you are not using the same call to GetAppropiateCastExpressionBasedOnType() which you use in other 'Translate*' methods, I can see that GetAppropiateCastExpressionBasedOnType() has a handler for AliasedValue and therefore I'm wondering if this is an oversight?

**Comment by jordimontana82** [comment]
Hi Ben,

Good catch. I fixed it now.
