### ISSUE TITLE
fakeContext.Initialize vs fakeOrgService.Create

### ISSUE THREAD

**Issue by craigseymour** [jordimontana82/fake-xrm-easy#162]
Jordi,

Just reviewing some code from one of my team, and I saw that she'd used the Create on the OrgService rather than the Initialize on the FakeXrmContext.  It seemed to work OK.  Is Initialize a sort of CreateMultipleRequest, or does it do other stuff for us too?

Craig

**Comment by jordimontana82** [comment]
Hi Craig!

Indeed kind of! It does some extra things:

1) Handy to initialize many records in one go as opposed to do many create's
2) It enforces that every record must have a non empty Id property, whereas with .Create this is not required.
3) If the entities you are using are early bound entities, it also assigns the revelant ProxyTypesAssembly for you (so no need to do ProxyTypesAssembly = Assembly.GetAsembly(typeof (Account)), on every test, it happens internally.

.Initialize is meant to be used to setup the initial state of your unit test with some data records.

**Comment by craigseymour** [comment]
Thanks!  It might be worth a note to this effect in https://dynamicsvalue.com/get-started/your-first-test?  Just to help the slow ones like me :-)

**Comment by jordimontana82** [comment]
No worries Craig.

Yeah! Good idea.
