### ISSUE TITLE
Ho to mock external service calls inside a plugin?

### ISSUE THREAD

**Issue by crisfervil** [jordimontana82/fake-xrm-easy#164]
Hi, 

This is more a question than an Issue, but I'll leave it here in case it can be useful for someone else. 

I have a plugin that makes a call to an external service, and I'd like to mock the call to that service too.

My plugin would be something like this:
``` cs
plugin class MyPlugin : IPlugin {

    public void Execute(IServiceProvider serviceProvider)
    {

        IMyCustomServiceProxy myExternalService = GetExternalService();

        // do something with the external service
        myExternalService.CallSomeMethod();
    }

    private IMyCustomServiceProxy GetExternalService(){
        // return an instance to my external service
    }
}
```
And the testing  code for this would be:
``` cs
[TestMethod]
public void My_Test_Case_With_External_Service_Call(){

    var context = new XrmFakedContext();

    ParameterCollection inputParameters = new ParameterCollection();
    inputParameters.Add("Target", email);

    var plugCtx = context.GetDefaultPluginContext();

    plugCtx.MessageName = "Send";
    plugCtx.Stage = 20;
    plugCtx.InputParameters = inputParameters;

    context.ExecutePluginWith<MyPlugin>(plugCtx);

    // Some Assertions
}
```

Question is: How would you Mock the call call to the external service *Inside* the plugin?

My solution to this is to add a mocked instance of the service as an input parameter, but I don't like the idea of having to add logic in the plugin only for testing purposes. Besides, I'm adding stuff in the plugin context, and I'm afraid that could potentially be interfering with something else.

This is how I did it.

Plugin Code:
``` cs
plugin class MyPlugin : IPlugin {

    public void Execute(IServiceProvider serviceProvider)
    {

        var pluginContext = (IPluginExecutionContext)serviceProvider.GetService(typeof(IPluginExecutionContext));

        IMyCustomServiceProxy myExternalService;

        // Get a mocked reference from the context, and If not available, create one for my own
        if (pluginExecutionContext.InputParameters.Contains("MyExternalMockedService")){
            myExternalService = (IMyCustomServiceProxy)pluginExecutionContext.InputParameters["MyExternalMockedService"];
        }
        else
        {
            myExternalService = GetExternalService();
        }
        
        // do something with the external service
        myExternalService.CallSomeMethod();
    }

    private IMyCustomServiceProxy GetExternalService(){
        // return an instance to my external service
    }
}
```
Testing Code
``` cs
[TestMethod]
public void My_Test_Case_With_External_Service_Call(){

    var context = new XrmFakedContext();

    // Mock the external service 
    var myServiceMock = new Mock<IMyCustomServiceProxy>();
    myServiceMock.Setup(x => x.CallSomeMethod());


    ParameterCollection inputParameters = new ParameterCollection();
    inputParameters.Add("Target", email);

    // Add a reference to the mocked service
    inputParameters.Add("MyExternalMockedService", myServiceMock.Object);

    var plugCtx = context.GetDefaultPluginContext();

    plugCtx.MessageName = "Send";
    plugCtx.Stage = 20;
    plugCtx.InputParameters = inputParameters;

    context.ExecutePluginWith<MyPlugin>(plugCtx);

    // Some Assertions
}
```

As I said, I don't like the fact that I'm using the input parameters for this purpose. 
IMO, the best way to do this would be being able to pass an instance of my plugin to the ExecutePluginWith method, where I can inject all the dependencies I need. 

Something like this:
``` cs
    var myPluginInstance = new MyPlugin(myServiceMock.Object);
    context.ExecutePluginWith(myPluginInstance,plugCtx);

```

Any Ideas about how to best do this?

Would it be ease to add a new overload to the ExecutePluginWith method?

Thanks

**Comment by jordimontana82** [comment]
Hi Cris,

That method [already](https://github.com/jordimontana82/fake-xrm-easy/blob/14024cf79878676d11cce742e74db62272f0662a/FakeXrmEasy.Shared/XrmFakedContext.Plugins.cs#L73) exists :)

So you could inject a mock into your instance and call the executepluginwith with your instance of the plugin with whatever extra mocks you need.

**Comment by crisfervil** [comment]
That's awesome!! Thanks Jordi!!

**Comment by jordimontana82** [comment]
No worries! Will close the issue then :+1:

**Comment by FixRM** [comment]
Hello all,

@crisfervil, can you share how you flight is going with it? :) I recently find myself thinking on the same problem. I personally don't like the idea of passing external service client into constructor or as property but what are the alternatives? I've been thinking of using abstract members or extension methods (with compiler directives) or even passing type as unsecure config and activate in plugin itself.

I understand that there is no ideal solution for that as we don't have OOB option to extend IServiceProvider so I just like to know your ideas and experience.

The problem spreads further than testing. It also be cool to be able to stub some staff for dev/test environments such as integration calls
