### ISSUE TITLE
QueryExpression Default Link Entity Alias Differs From CRM Functionality

### ISSUE THREAD

**Issue by rbnswartz** [jordimontana82/fake-xrm-easy#165]
When you create a query expression with a linked entity and don't give the linked entity an EntityAlias the default alias that CRM gives you is the entity name with a number appended to it whereas fake xrm easy returns just the entity name. 

This also creates a problem when the same entity is linked more then once. Since they have the same alias the second linked entity value overwrites the first.

Here is a test to demonstrate the issue.

```
        [Fact]
        public void TestMultipleUnaliasedJoins()
        {
            XrmFakedContext context = new XrmFakedContext();
            IOrganizationService service = context.GetOrganizationService();

            Entity account = new Entity("account");
            account.Id = Guid.NewGuid();
            account["firstname"] = "Test";

            Entity secondAccount = new Entity("account");
            secondAccount.Id = Guid.NewGuid();
            secondAccount["firstname"] = "secondTest";

            Entity contact = new Entity("contact");
            contact.Id = Guid.NewGuid();
            contact["parent"] = account.ToEntityReference();
            contact["otherparent"] = secondAccount.ToEntityReference();

            context.Initialize(new List<Entity>() { account, secondAccount, contact });

            QueryExpression query = new QueryExpression("contact");

            LinkEntity firstLink = new LinkEntity("contact", "account", "parent", "accountid", JoinOperator.LeftOuter);
            firstLink.Columns = new ColumnSet("firstname");
            query.LinkEntities.Add(firstLink);

            LinkEntity secondLink = new LinkEntity("contact", "account", "otherparent", "accountid", JoinOperator.LeftOuter);
            secondLink.Columns = new ColumnSet("firstname");
            query.LinkEntities.Add(secondLink);

            var result = service.RetrieveMultiple(query);
            Entity resultingEntity = result.Entities[0];
            Assert.Equal(resultingEntity.Attributes.Count, 2);
            Assert.Equal("Test",((AliasedValue)resultingEntity["account1.firstname"]).Value);
            Assert.Equal("secondTest",((AliasedValue)resultingEntity["account2.firstname"]).Value);
            
        }
```
This problem doesn't occur if you specify an alias for the LinkEntity

**Comment by rbnswartz** [comment]
I have a deadline fast approaching and I don't have time to fix it so I'm submitting an issue and not a pull request to fix it. Perhaps when I have time I can fix it.

**Comment by eNeRGy164** [comment]
I'm diving into this, and made it work inside the query engine by adding unique aliases to the query. Giving the expected results.
I had to remove the uniqueness from the deprecated ExecuteFetch results, because those *do* contain duplicate attribute names 😩 (but those didn't show up before because they would get overwritten in the query engine before)

I'll have to write more unit tests to get more coverage, but it seems to work nicely. Hope to get the PR out this afternoon.
