### ISSUE TITLE
Need Permissions infrastructure

### ISSUE THREAD

**Issue by benArrayx** [jordimontana82/fake-xrm-easy#166]
Hi Jordi, I need to implement tests for the GrantAccessRequest, RevokeAccessRequest, RetrievePrincipalAccessRequest and RetrieveSharedPrincipalsAndAccessRequest. This needs some simple storage in the form of a Dictionary<Entity, Microsoft.Crm.Sdk.Messages.AccessRights>, associated with a specific owning Entity. The Entity of the dictionary will be a systemuser or team entity, associated with a specific type of AccessRight. Each User or Team could have more than 1 AccessRight per Entity.

I'm happy to implement the Message Executors, however what I'm not clear on is the best place to hold the permissions data, given that there is no matching IOrganizationService method that can be used. Maybe these should be methods on the Context, ie. Context.GrantAccess, Context.RevokeAccess, Context.RetrievePrincipalAccess and Context.RetrieveSharedPrincipalsAndAccess.

Do you agree?

**Comment by jordimontana82** [comment]
Hi Ben,

I think it would be best a Dictionary like <Entity, PrincipalAccess> where entity is the target used in each message (pls check Examples section [in here](https://msdn.microsoft.com/en-us/library/microsoft.crm.sdk.messages.grantaccessrequest.aspx)), and PrincipalAccess can contain both a security principal (user or team) and also the associated AccessRights for that principal.

So one entity record can have many PrincipalAccess records, giving the possibility to add many users and rights to a single record (like when you share one record with multiple users or teams).

As the XrmFakedContext class is getting bigger, I would put this under something like FakeXrmEasy.Shared\Permissions\IAccessRightsRepository

(interface + an implementation)

With the methods you mentioned, GrantAccess, RevokeAccess, etc

Which could be then consumed by the fake message executors.

Thoughts?

**Comment by benArrayx** [comment]
Hi Jordi, yes sounds good to me :) Do you want to do this, shall I? Maybe better for you to do the interface etc and I'll do the executors?

On 13 Apr 2017 20:13, Jordi <notifications@github.com> wrote:

Hi Ben,

I think it would be best a Dictionary like <Entity, PrincipalAccess> where entity is the target used in each message (pls check Examples section in here<https://msdn.microsoft.com/en-us/library/microsoft.crm.sdk.messages.grantaccessrequest.aspx>), and PrincipalAccess can contain both a security principal (user or team) and also the associated AccessRights for that principal.

So one entity record can have many PrincipalAccess records, giving the possibility to add many users and rights to a single record (like when you share one record with multiple users or teams).

As the XrmFakedContext class is getting bigger, I would put this under something like FakeXrmEasy.Shared\Permissions\IAccessRightsRepository

(interface + an implementation)

With the methods you mentioned, GrantAccess, RevokeAccess, etc

Which could be then consumed by the fake message executors.

Thoughts?

**Comment by jordimontana82** [comment]
Oki! I'll do the interface

**Comment by jordimontana82** [comment]
Hi Ben,

I added a new interface with some of the method we might need. I'm busy all this week so feel free to start the implementation yourself if you need to.

The dictionary will hold a list of PrincipalAccess records to simulate the fact many users might have access to the same record (EntityReference) at any one time.

Hope this helps

**Comment by benArrayx** [comment]
Hi Jordi, thanks for this. I haven’t had chance to look at this yet, and not sure I’ll be able to this week, next week I’m away on holiday so it will probably be a couple of weeks before I can get to it. As soon as I can, I will – definitely need it for a next phase of client development!

Regards, Ben

**Comment by jordimontana82** [comment]
Hi Ben,

Cool! No rush at all.... :+1:

**Comment by jordimontana82** [comment]
I'll close this one as it has been implemented
