### ISSUE TITLE
Getting Error while creating one N:N Relationship record

### ISSUE THREAD

**Issue by keshari-bikram** [jordimontana82/fake-xrm-easy#171]
Hi,

First of all thank you for writing such an easy to implement framework for Dynamics CRM code testing.

Here is my issue. I followed the instruction for creating N:N Relationships and it works perfectly for the relationships those are with default schema names like "systemuserroles" or "new_new_broker_contact" or "new_new_localpolicy_new_country". As we know CRM concatenates Target and Referencing entity names to give names to these intersecting tables. This however, doesn't work with the ones where the schema names are altered to look something like "new_countriesofquotes". This always gives me the error "Relationship XXX does not exist in the metadata cache" while running test codes. Logically, this shouldn't be the case.

Any help will be highly appreciated.

Thanks,
Bikram

**Comment by jordimontana82** [comment]
Hi Bikram,

Thanks for your feedback! 

You can pass any relationship name when adding the relationship, which will be used then by the Associate / Disassociate requests for instance.

[Here's an example](https://github.com/jordimontana82/fake-xrm-easy/blob/f3730a4d183c81a5ad2a66606657d6aff7a3232b/FakeXrmEasy.Tests/FakeContextTests/RetrieveMultiple/QueryLinkEntityTests.cs#L37-L54)

In the above example, "systemuserroles_association" could be anything like "my_own_fake_relationship_name" for instance.

**Comment by jordimontana82** [comment]
Gonna close this one, if you still have further questions please reopen it :)

**Comment by keshari-bikram** [comment]
Thanks Jordi for confirming that. Found that the relationship name is case sensitive.

**Comment by keshari-bikram** [comment]
Thanks Jordi for confirming that. Found that the relationship name is case sensitive. I was doing this mistake by declaring the relationship with it's name as "new_countriesofquotes" and while creating the relationship record, was mentioning the relationship as "new_CountriesOfQuotes". Obviously both are not same when matched as string.
