### ISSUE TITLE
Exactly FakeItEasy 3.2.0?

### ISSUE THREAD

**Issue by mivra** [jordimontana82/fake-xrm-easy#177]
Hi Jordi, is there a reason why FakeXrmEasy requires FakeItEasy library exactly in version 3.2.0? Version 3.3.2 was released recently. Just asking ;) Thx.

**Comment by jordimontana82** [comment]
Hi @mivra 

There were some people just having compatibility issues with later versions just fixed that version for now.

**Comment by jordimontana82** [comment]
Hi @Enielezi ,

Not in the short term, there were uncompatibility issues that's why nuspec was updated to force a specific version 3.2.0.  But, if you want to try to upgrade locally and see the impacted changes are not massive we can always reconsider it .

**Comment by BackToTheCrm** [comment]
Hi @jordimontana82,

Just checking if your position on the fixed version of FakeItEasy has changed.
The current version is 6.0.0 so the v3.2.0 is quite old.

Anyway, thank you for your amazing job on FakeXrmEasy, it's very useful !

**Comment by jordimontana82** [comment]
@BackToTheCrm 

Thanks! Indeed it changed, this is covered in PR #464 now.

The only reason to retain 3.2.0 was that fake-xrm-easy-js needed a patch version to talk FakeXrmEasy's .net project via edge.js.  But fake-xrm-easy-js has been rewritten in .ts and so there is no such dependency anymore.

**Comment by BackToTheCrm** [comment]
Hi @jordimontana82 !

I'm glad to hear that this issue was covered :)
However, it seems that the update is not on nuget.org as you can see in this screenshot :
![image](https://user-images.githubusercontent.com/15627943/83504004-3d775f00-a4c4-11ea-9091-74a006605b20.png)

Again, thank you for your job and the job done by the other contributors :)

**Comment by jordimontana82** [comment]
Hi Clément!

Let me check

**Comment by BackToTheCrm** [comment]
Thank you ! I'll try it as soon as possible and I'll come back to you.

**Comment by BackToTheCrm** [comment]
It works 😄 ! Thank you !

**Comment by jordimontana82** [comment]
Awesome! You're welcome!
