### ISSUE TITLE
Some of the CRM requests are not implemented (yet)

### ISSUE THREAD

**Issue by rebulanyum** [jordimontana82/fake-xrm-easy#178]
Hello @jordimontana82 .

I was trying your library (installed it from nuget) and it was good so far. However, I come with an exception: The exception message is 

> An exception of type 'FakeXrmEasy.PullRequestException' occurred in Microsoft.Xrm.Sdk.dll but was not handled in user code

> Additional information: Exception: The organization request type 'Microsoft.Xrm.Sdk.Messages.RetrieveRelationshipRequest' is not yet supported... but we DO love pull requests so please feel free to submit one! :). This functionality is not available yet. Please consider contributing to the following Git project https://github.com/jordimontana82/fake-xrm-easy by cloning the repository and issuing a pull request.

I get this exception with the following code

```csharp
var contact = new Contact(Guid.NewGuid());
var context = new XrmFakedContext();
context.ProxyTypesAssembly = typeof(Contact).Assembly;
context.Initialize(new Entity[] { contact });
var service = context.GetOrganizationService();
using (var crmContext = new CrmContext(service))
{
    var firstContact = (from contact in crmContext.ContactSet
                        select contact).First();
    crmContext.LoadProperty(firstContact, "business_unit_contacts");
}
```
The exception is thrown on `crmContext.LoadProperty(firstContact, "business_unit_contacts");`. And I couldn't find any test methods using this method in MinClientContext.cs. I hope you can fix it soon.

On the other hand, when I try to open the solution it gives me the following error. It is about the DevToolkitSamples project. (Looks like I hit two issues with this one.)

![image](https://cloud.githubusercontent.com/assets/1245382/25950686/652630d4-3664-11e7-9507-646981fd1549.png)

So I don't care about the second one, but the first one, the implementation of RetrieveRelationshipRequest is important. I hope you can fix it soon.

**Comment by jordimontana82** [comment]
Hi @rebulanyum 

The first issue means that request is not yet implemented. It wouldn't be a big deal to implement a fake message executor which returns relationship metadata . You can take examples from the XrmFakedContext.AddRelationship method and the other Associate / Dissasociate fake messages.

In relation to the second issue, you'll need to install the latest 365 developer toolkit.

Hope this helps!

**Comment by rebulanyum** [comment]
Well @jordimontana82 . There are tons of messages [here](https://msdn.microsoft.com/en-us/library/gg309482.aspx). It really is not important for only RetrieveRelationshipRequest. I'll try to do that but you should continue to implement the others too.

**Comment by jordimontana82** [comment]
Hi Izzat,

Sorry just reading this. Indeed, there are tons of requests there, and, to be honest, didn't need those yet and so didn't have to implement them.  The framework is open enough to be extended to your own needs (you could add any missing messages via context.AddFakeMessageExecutor, for instance). However, if you do it, please also submit a PR with these missing messages.

GitHub is a crowdsourcing, collaborative platform. That means the more contributions we have from the community the sooner we'll have these messages and other features available for everybody.

I also have my focus on the Javascript side of things now as well as participating in community events which takes me quite a lot of time.  

So feel free to add it and please do ask any questions if you are stuck with anything.

Cheers!

**Comment by jordimontana82** [comment]
Any luck with this @rebulanyum ?

**Comment by rebulanyum** [comment]
No. Sorry.

**Comment by xairrick** [comment]
I submitted a pull request https://github.com/jordimontana82/fake-xrm-easy/pull/276 that has this fix in it.   In order to user .LoadProperty()  you WILL have to provide an relationship to the XrmFakedContext via AddRelationship

**Comment by jordimontana82** [comment]
Closing this one now. Thx for this @xairrick
