### ISSUE TITLE
Upgrading to VS 2015 or 2017?

### ISSUE THREAD

**Issue by imranakram** [jordimontana82/fake-xrm-easy#179]
Hi,
I noticed that the solution is for VS 2013. Could you please upgrade it to 2015 or 2017?
Thanks,
Imran

**Comment by jordimontana82** [comment]
Thanks, I would upgrade it to V 2015 only for now.

**Comment by imranakram** [comment]
Thanks, I managed to do that yesterday and had to remove the DevToolkitSamples project from the solution. I can make a pull request if you haven't done that already :)

**Comment by jordimontana82** [comment]
Cool, thx Imran.

VS2015 Community or Enterprise? I have both but wouldn't like to force people into Enterprise if they don't have licences for it.

Cheers!

**Comment by imranakram** [comment]
You're welcome, I have VS 2015 Professional. I think it should work with Community version as well.
