### ISSUE TITLE
Add associate / disassociate fake messages implementation

### ISSUE THREAD

**Issue by jordimontana82** [jordimontana82/fake-xrm-easy#18]
Although we can fake 1:N and N:1 relationships by just using EntityReference attributes with the current version of the framework, N:N relationships are created using a special Associate / Disassociate message from the OrganizationService and we don't have fake methods for these yet.

In order to keep it simple, we could just store an array of relationships in the XrmFakedContext, so that we could initialize the minimum set of relationships for each test.

```csharp

public class XrmFakedContext {
...
   public Dictionary<string, XrmFakedRelationship> Relationships {get; set;}
   
   
...
}


public class XrmFakedRelationship {
   public string SchemaName {get;set;}
   public string EntityName {get;set;}  //of the many to many intersect entity
   
   //Entity name and attribute of the first entity participating in the relationship
   public string ReferencedEntityName1 {get;set;}   
   public string ReferencedEntityName2 {get;set;}

   //Entity name and attribute of the first entity participating in the relationship
   public string ReferencedAttributeName1 {get;set;}
   public string ReferencedAttributeName2 {get;set;}
}

```

So that when an Associate message is called, it needs to create new entries in the context for the EntityName involved in the N:N relationship as well as it needs to populate Entity References to the relevant entities.  XrmFakedRelationship will be used to know which fields need to be updated.

**Comment by DigitalFlow** [comment]
Hey @jordimontana82,

Will have a look on this :)
I was thinking about adding support for this the same day that you created the issue :+1:

**Comment by jordimontana82** [comment]
Hah! @DigitalFlow 

I started actually working on that on a local branch which I didn't push yet.... I could push the changes and you could take it from there?

**Comment by DigitalFlow** [comment]
@jordimontana82: Sure!

**Comment by jordimontana82** [comment]
Sorry! I got confused for a while... I started working on a new branch for integration support. Feel free to add this stuff! :)

**Comment by jordimontana82** [comment]
Hey @DigitalFlow,

Wondering if you had a chance to look at this? :)

**Comment by DigitalFlow** [comment]
Hey @jordimontana82,

I started some work on my fork, not ready for merge yet though.
Had not much time until now, but hopefully I'll be able to finish it soon.

**Comment by jordimontana82** [comment]
That's cool! Thank you!

**Comment by jordimontana82** [comment]
@DigitalFlow  thx a lot for the contribution!

I added a call to your Associate/Disassociate Request Executors from the service.Associate and service.Disassociate methods too.

**Comment by DigitalFlow** [comment]
Thx, forgot that as it seems. I submitted a new pull request though, which has some slight refactorings to the intersect entity schema name.

**Comment by jordimontana82** [comment]
No problem at all :+1:
