### ISSUE TITLE
Dynamics CRM Plugin test case is getting failed. 

### ISSUE THREAD

**Issue by sateeshkalva** [jordimontana82/fake-xrm-easy#189]
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;

using FakeItEasy;
using FakeXrmEasy;

using Xunit;
using Microsoft.Crm.Sdk.Samples;
using Microsoft.Xrm.Sdk;

using earlybound;

namespace UnitTestProject1
{
    public class MyTests
    {
        [Fact]
        public void When_the_account_number_plugin_is_executed_it_adds_a_random_number_to_an_account_entity()
        {
            var fakedContext = new XrmFakedContext();

            var account = new Account() { Id = Guid.NewGuid() };

            //Execute our plugin against a target that doesn't contains the accountnumber attribute
            var fakedPlugin = fakedContext.ExecutePluginWithTarget<AccountNumberPlugin>(account);

            //Assert that the target contains a new attribute
            Xunit.Assert.True(account.Attributes.ContainsKey("accountnumber"));
        }

        [Fact]
        **public void When_the_account_number_plugin_is_executed_with_account_number_attribute_exception_is_raised()**
        {
            var fakedContext = new XrmFakedContext();

            var account1 = new Account() { Id = Guid.NewGuid(), AccountNumber = "123456"};

            //Execute our plugin against a target that doesn't contains the accountnumber attribute
            var fakedPlugin = fakedContext.ExecutePluginWithTarget<AccountNumberPlugin>(account1);

            //Assert that the target contains a new attribute
            Xunit.Assert.Throws<InvalidPluginExecutionException>(() => fakedContext.ExecutePluginWithTarget<AccountNumberPlugin>(account1));
        }
    }
}

Second test method is getting failed with the exception message from Account number plugin "Account number can only set by the system."
For this test I've followed the process from 
Youtube link "https://www.youtube.com/watch?v=Kav1dy1ss7g"

--Thank you

**Comment by jordimontana82** [comment]
What's the issue? The plugin indeed [raises an exception](https://github.com/jordimontana82/fake-xrm-easy/blob/f3730a4d183c81a5ad2a66606657d6aff7a3232b/FakeXrmEasy.Tests/PluginsForTesting/AccountNumberPlugin.cs) on purpose when there is an accountnumber so it is working as expected?

**Comment by sateeshkalva** [comment]
yes.. the plugin is working as expected. But in that youtube video link, at the end both the tests have been passed. but in my case, the second test is getting failed. 
![1](https://user-images.githubusercontent.com/29273312/26967264-361da196-4d1b-11e7-8506-623adfe2eb90.jpg)

**Comment by jordimontana82** [comment]
Oh I get you now.

You only need the line Assert.Throws<> ... .  It is failing in the previous .ExecutePluginWith method. Basically you are running the same plugin twice, that's the issue.
