### ISSUE TITLE
GetFakedOrganizationServiceProxy commented out

### ISSUE THREAD

**Issue by Ceribia** [jordimontana82/fake-xrm-easy#190]
I found #37 and was happy to see it had already been implemented. However GetFakedOrganizationServiceProxy was commented out in 6ab2f57948256fae922e9d7ce864e88a09dac500. Should it still be functional?

**Comment by jordimontana82** [comment]
OrganizationServiceProxy already implements IOrganizationService so there was no need to mock that one, as there is .GetOrganisationService(). 

You code should just reference IOrganizationService, but then production code would inject an instance of OrganizationServiceProxy (i.e. if you use a DI container) and, from your unit tests, your fake service.


Closing as it is similar to other issues. 

Please have a look at issues #140 and #174

**Comment by jordimontana82** [comment]
Hi @Ceribia 

Did you post a question on SO around setting a default state / status for an entity by any chance? :)

This should work, there is a default entity initializer which sets some properties automatically by default, but it shouldn't override the ones you pass:

```cs
    specialization["statecode"] = new OptionSetValue(0);
    specialization["statuscode"] = new OptionSetValue(1);
    fakeContext.Initialize(new List<Entity> {
        specialization
    });
```

Would you like to raise another issue if have further questions?

**Comment by Ceribia** [comment]
Hi Jordi, I did!

Though instantly deleted it as I noticed a typo that could have been causing the whole problem. Unfortunately my code is at work so I can't check, but I'm pretty sure that I was setting the statecode and statuscode before the initialization but the query was still consistently seeing the opposite activation status. Testing the query directly against the crm has been working fine so don't think it's a query issue. My current plan is on Monday to make a simplest possible test for it and see when the issue starts to crop up; I'll let you know how it turns out :)

Btw, thanks for FakeXrmEasy! Being able to unit test code has made learning crm way nicer.

**Comment by jordimontana82** [comment]
Great! Let me know how it goes then :)

And thanks so much for your feedback.... looking forward your pull requests! ;)

**Comment by Ceribia** [comment]
It all went fine. Issue was partially on my end, partially #191 (thanks for the fast fix!), and all got sorted. Ended up being a strong example for our group using FakeXRMEasy going forward. 

No pull requests as yet but hopefully we'll need something you haven't already implemented eventually :)

**Comment by jordimontana82** [comment]
Nice one!
