### ISSUE TITLE
RetrieveMultiple retrieves more than 5000 results without paging

### ISSUE THREAD

**Issue by Ceribia** [jordimontana82/fake-xrm-easy#195]
I hit a bug in my code where I had used RetrieveMultiple without a paging loop so results beyond the first 5000 were ignored. In trying to write a unit test for this I found that RetrieveMultiple on a fake context returns all results without paging. This is certainly handy, but it would be nice to duplicate the real version functionally.

This unit test shows the problem.

```
        public void FiveThousandOneContacts()
        {
            // Set up 5001 contacts
            var context = new XrmFakedContext();
            var service = context.GetOrganizationService();
           
            var contextInitalizeList = new List<Entity>();
            for (int i = 0; i < 5001; i++)            
            {
                var contact = new Contact()
                {
                    ContactId = Guid.NewGuid(),
                };

                contextInitalizeList.Add(contact);
            }
            context.Initialize(contextInitalizeList);

            // Retreive them all
            QueryExpression queryContact = new QueryExpression
            {
                EntityName = "contact",
                ColumnSet = new ColumnSet("contactid"),
            };

            var contactResults = service.RetrieveMultiple(queryContact);

            // Should receive only 5000 of them and have to page for the other 1
            Assert.AreEqual(5000, contactResults.Entities.Count());
        }
```

**Comment by jordimontana82** [comment]
Thanks for raising this.

So there is pagination in place [there](https://github.com/jordimontana82/fake-xrm-easy/blob/master/FakeXrmEasy.Shared/XrmFakedContext.Queries.cs#L359-L370)... but we could possibly default the TopCount setting to 5000 if none was used? 

That setting might differ for On-Premise though, I think it is based on a regedit / MSCRM config database parameter.

**Comment by jordimontana82** [comment]
I would put it in a variable like MaxRetrieveCount or similar
