### ISSUE TITLE
RetrieveVersionRequest throws

### ISSUE THREAD

**Issue by rappen** [jordimontana82/fake-xrm-easy#208]
Just like #206 and #207 it is not possible to get the "faked" version using ``RetrieveVersionRequest``.

https://msdn.microsoft.com/en-us/library/microsoft.crm.sdk.messages.retrieveversionrequest.aspx

**Comment by jordimontana82** [comment]
Hi Jonas!

It is indeed possible to add any missing request with your own fake messages by just calling ctx.AddFakeMessageExecutor<RequestType>(new InstanceOfAFakeMessageExecutorInehritingFromIFakeMessageExecutor).

Example:

    var ctx = new XrmFakedContext()
    ctx.AddFakeMessageExecutor<RetrieveVersionRequest>(new RetrieveVersionFakeMessageExecutor());

This will add a custom RetrieveVersionFakeMessageExecutor to the repository of implemented messages.

You could also wrap these custom ones in a custom context class (inheriting from XrmFakedConext) which does all the same initialisations every time.

[Example of RetrieveAttributeRequestExecutor](https://github.com/jordimontana82/fake-xrm-easy/blob/19e155a9245ef7d0762eedbe8145d93be290a051/FakeXrmEasy.Shared/FakeMessageExecutors/RetrieveAttributeRequestExecutor.cs)

**Comment by rappen** [comment]
Thanks!

**Comment by jordimontana82** [comment]
No worries Jonas!

Thanks to Dave who submitted this as part of a masterclass exercise! :)
