### ISSUE TITLE
Initializing ManyToMany relationship entities has issues

### ISSUE THREAD

**Issue by eNeRGy164** [jordimontana82/fake-xrm-easy#212]
2 issues I found:

When there is a Proxy Types Assembly you can't initialize a Many to Many entity because they are not part of the generated code.

When not using a Proxy Types Assembly you can initialize the entity, but it gets many default attributes like `createdon` which are not present in Many to Many entities.

Fix will be submitted shortly.

**Comment by jordimontana82** [comment]
Mmm I'm not sure on that one.

I have many to many entities generated in the GeneratedCode.cs so it should be possible to pass them to the .Initialize().

**Comment by eNeRGy164** [comment]
You're right, it seems our CrmSvcUtil extensions are trimming my M2M from the resulting code. Thanks for pointing that issue out. 😄

I adjusted the PR. So the default properties won't be added to the M2M entities
