### ISSUE TITLE
Throw exception when trying to update an inactive record

### ISSUE THREAD

**Issue by jordimontana82** [jordimontana82/fake-xrm-easy#214]
It shouldn't be possible to update a record in inactive status. This could be added to the UpdateRequestExecutor to mimic this CRM behavior.

**Comment by mivra** [comment]
But the true CRM (at least CRM Online 2015, 2016, 365) allows updating Inactive records. I've just tried Contact and one custom entity to be sure. We actively use it in our solution. I believe it can be restricted only to some entity types like Order or Opportunity.

**Comment by jordimontana82** [comment]
Thanks for pointing this out @mivra 

Will revisit this and get back to you

**Comment by jordimontana82** [comment]
It should be possible to update inactive QueueItems:

    try { 
    var state = new SetStateRequest { 
           State = new OptionSetValue((int) QueueItem.eStatus.Active), 
           Status = new OptionSetValue((int) QueueItem.eStatusReason.Active_Active), 
           EntityMoniker = queueItem 
     }; 
    OrganizationService.Execute(state); 
      } 
    catch (Exception exception) { throw new InvalidPluginExecutionException($"An error has occurred 
    {exception.Message}"); }

**Comment by mivra** [comment]
Hi Jordi, is it really closed? Of course, you can reactivate an entity by calling SetStateRequest. However, why do another call if CRM allows updating an inactive entity. It works if the update request does not contain entity state/status fields. So if you don't tell the CRM, the update will go through :)
