### ISSUE TITLE
NuGet dependencies should be lowest version possible

### ISSUE THREAD

**Issue by eNeRGy164** [jordimontana82/fake-xrm-easy#219]
The dependencies on CrmSdk should be lowest possible, only using later versions if technically required. Otherwise you are forcing people to upgrade their dependencies just by using FakeXrmEasy.

So for dynamics 365 the nuspec should say 8.2.

**Comment by jordimontana82** [comment]
Agree on this, provided downgrading doesn't introduce breaking changes, however this could be resolved by using binding redirects as suggested in this other issue #432  as well.

**Comment by jordimontana82** [comment]
Looks like this was resolved in #273 but the issue remained open so closing now.
