### ISSUE TITLE
InitializeEntityMetadata, I need initialize attributes

### ISSUE THREAD

**Issue by ClaraOrtiMoles** [jordimontana82/fake-xrm-easy#224]
How can I initialize an EntityMetadata with Attributes? Attributes is a private field of entitymetadata. 

Awesome framework! 

Thank you  @jordimontana82   :)

**Comment by jordimontana82** [comment]
Hi Clara,

Thanks and glad you like it! 

You can call [.SetAttributeCollection()](https://github.com/jordimontana82/fake-xrm-easy/blob/19e155a9245ef7d0762eedbe8145d93be290a051/FakeXrmEasy.Shared/Extensions/EntityMetadataExtensions.cs#L11) from the extensions namespace to set the attributes.

If you are interested, topics like this and many many others are included as part of the [FakeXrmEasy masterclass](https://dynamicsvalue.com/training) ! :)

**Comment by eNeRGy164** [comment]
If you need a guest lecturer for my code additions, I won't mind visiting Barcelona 😉
