### ISSUE TITLE
AddListMembersListRequest throws Additional information: Entity sdkmessageprocessingstep does not exist in the metadata cache

### ISSUE THREAD

**Issue by minohimself** [jordimontana82/fake-xrm-easy#229]
Im Trying to test my Plugin that works with Marketing lists when Calling AddListMembersListRequest i get the error

**Comment by jordimontana82** [comment]
Same issue as #227  :)

**Comment by eNeRGy164** [comment]
Seems more people are using Generated Code without all system entities then expected :)

**Comment by jordimontana82** [comment]
I do use early bound myself too !  :)

I'd like to keep the pipeline as an optional feature. It is great, but having it enabled by default forces people to inject message processing steps as part of the .Initialize step.

So... something for version 1.34.1

**Comment by eNeRGy164** [comment]
I've a pull request ready that should solve the current problems by making the framework a bit more relaxed with a hybrid of early bound with dynamic types

**Comment by minohimself** [comment]
I have solved it by downgrading to 1.33.1
