### ISSUE TITLE
PartialGenerated namespace missing in the project

### ISSUE THREAD

**Issue by AleksandrRogov** [jordimontana82/fake-xrm-easy#234]
Hi Jordi,
Weird issue, but the project is missing `PartialGenerated` namespace and therefore it's impossible to build. Do you know where it comes from?

![image](https://user-images.githubusercontent.com/1893650/29417522-7107dcde-8337-11e7-98a2-3c8b51353b0b.png)

Thanks

**Comment by eNeRGy164** [comment]
That is part of #230 , which isn't merged with the master.

**Comment by AleksandrRogov** [comment]
Ok. The tests are merged though! I will simply comment it in my project for now.

**Comment by AleksandrRogov** [comment]
Ok, I figured it out. It's my fault.
