### ISSUE TITLE
Need few CRM Requests

### ISSUE THREAD

**Issue by Sejoslaw** [jordimontana82/fake-xrm-easy#235]
Hi @jordimontana82 

Do You think it would be easy to implement any of these Requests ?

WinOpportunityRequest
QualifyLeadRequest
SendEmailRequest
LoseOpportunityRequest

**Comment by jordimontana82** [comment]
Hi Sejoslaw, it shouldn't be a big deal. They primarily change statuses of opportunities, leads, and emails.

If you have time, would be great if you could add those if you take the [SetStateRequestExecutor](https://github.com/jordimontana82/fake-xrm-easy/blob/6f909ba025087ab03af6551baed689647eb36378/FakeXrmEasy.Shared/FakeMessageExecutors/SetStateRequestExecutor.cs) and [SetStateRequestTests](https://github.com/jordimontana82/fake-xrm-easy/blob/6f909ba025087ab03af6551baed689647eb36378/FakeXrmEasy.Tests.Shared/FakeContextTests/SetStateRequestTests/SetStateRequestTests.cs) as an example?
