### ISSUE TITLE
ConditionOperator.On and Today don't ignore time

### ISSUE THREAD

**Issue by fedejousset** [jordimontana82/fake-xrm-easy#237]
Hi all,

I'm having some issues with some queries that use the ConditionOperator.**On** (I haven't checked with OnOrAfter and OnOrBefore yet but they also take into account only the Date part) which is not ignoring the time part and therefore is not returning the right records. 

I've confirmed this issue changing the FetchXml_Operator_On_Execution test (FakeXrmEasy.Tests.FakeContextTests.FetchXml):
<img width="405" alt="test_failed" src="https://user-images.githubusercontent.com/20836210/29723721-98d5dedc-89bd-11e7-9469-e22620a47901.PNG">

I've also check the Today operator and it seems that it has the same issue (just replaces DateTime.Today with DateTime.Now which includes time):
<img width="390" alt="test_today_failed" src="https://user-images.githubusercontent.com/20836210/29724209-85a7fef6-89bf-11e7-8b55-e40f709257d0.PNG">

I forked the branch so I'll try to submit a PR if I can find time over the weekend but just in case I leave this issue here. 

Thank you!

**Comment by jordimontana82** [comment]
Hi Fede,

Thanks for spotting this.... version 1.35.1 should fix this issue :)

**Comment by fedejousset** [comment]
Thanks Jordi, it's fixed indeed :)
