### ISSUE TITLE
Give access to the fake IServiceProvider

### ISSUE THREAD

**Issue by Dremor** [jordimontana82/fake-xrm-easy#241]
Hi,

I'm trying to make an unit test covering the Execute method of a custom plugin, using a custom execution context, based on XrmUtils. Thus, I need to make a fake custom context, and for this, I need to get a fake IServiceProvider. Is there a way to get it? If not, could it be possible to add a way to do it ?

Best regards,

Dremor

**Comment by jordimontana82** [comment]
Hi @Dremor 

Right now the [GetFakedServiceProvider](https://github.com/jordimontana82/fake-xrm-easy/blob/master/FakeXrmEasy.Shared/XrmFakedContext.Plugins.cs#L220-L263) is not public, only used internally to automatically inject pretty much everything from a [XrmFakedPluginExecutionContext](https://github.com/jordimontana82/fake-xrm-easy/blob/6f909ba025087ab03af6551baed689647eb36378/FakeXrmEasy.Shared/XrmFakedPluginExecutionContext.cs) class.

So in theory all you need to do is pass an instance of XrmFakedPluginExecutionContext with whatever context properties your plugin needs.

**Comment by Dremor** [comment]
I tried, but unfortunately, it seems that need to give a IServiceProvider to my plugin [(see here)](https://github.com/emerbrito/XrmUtils-PluginExtensions/blob/d180a83aded792100f7f5311bc56623446b1b67b/src/XrmUtils.Plugins.Extensions/Plugins/PluginBase.cs#L35).

**Comment by jordimontana82** [comment]
Not really, should be enough by calling ctx.ExecutePluginWith<YourPlugin>(xrmfakedpluginexecutioncontext).

That method will execute your plugin passing an already mocked IServiceProvider, even it is a subclass of IPlugin.  XrmUtils also implements IPlugin so it should be the same thing...

Check [this example](https://github.com/jordimontana82/fake-xrm-easy/blob/f3730a4d183c81a5ad2a66606657d6aff7a3232b/FakeXrmEasy.Tests/FakeContextTests/FakeContextTestPlugins.cs#L211-L215) which is a very simple example for testing [MyPlugin](https://github.com/jordimontana82/fake-xrm-easy/blob/f3730a4d183c81a5ad2a66606657d6aff7a3232b/FakeXrmEasy.Tests/PluginsForTesting/InheritedPlugin.cs)

**Comment by jordimontana82** [comment]
Closing this one.... if you still have questions please do let me know.

**Comment by FixRM** [comment]
@jordimontana82, there is use case then access to IServiceProvider is better option then XrmFakedPluginExecutionContext. Visual Studio Code Coverage tool as well as Live Unit Testing expect that IPlugin.Execute will be called directly. At the moment I have zero coverage :( Would you mind a PR for that?

**Comment by FixRM** [comment]
False alarm, it's Live Unit Testing issue
