### ISSUE TITLE
Passing null attributes to TargetEntity

### ISSUE THREAD

**Issue by minohimself** [jordimontana82/fake-xrm-easy#242]
Hi Guys,

I'm trying to pass attribute value null to the plugin, my plugin check if the target entity contains the Field when i run my plugin in CRM he react and sees that the value was changed and is null. 
When i write test for it and something like 
    inputParameters.Add("Target", new Account() {AccountId = account.Id, CompanyStatus = null});
my plugin will not see the change on CompanyStatus field and wont be fired.

**Comment by minohimself** [comment]
This Problem occured because of how my early bind classes are hanled. Im using former Solution manager to generate my Early bind Classes. 

This works : 
            var accountToBeUpdated = new Account() {AccountId = account.Id};
            accountToBeUpdated[Account.Properties.CompanyStatus] = null;

**Comment by jordimontana82** [comment]
Nice! Glad you found it :)
