### ISSUE TITLE
Autopopulate EntityMetadata by ProxyTypesAssembly

### ISSUE THREAD

**Issue by DigitalFlow** [jordimontana82/fake-xrm-easy#247]
Hey Jordi,

how are you doing? :smile:

I noticed the EntityMetadata feature and like it a lot.
In addition to to the current implementation, I think it would be nice, if as much as possible was automatically added to the EntityMetadata list.
For this I think we could use the ProxyTypesAssembly, as this will contain all entity logical names, object type codes and field names. This is not currently done, correct?

I'll start working on the implementation as soon as possible and submit a PR.

Kind Regards,
Florian

**Comment by eNeRGy164** [comment]
I already have an implementation for that somewhere, I think :)

**Comment by eNeRGy164** [comment]
This was an experiment to read the assembly into a metadata layer for usage by alle the metadata methods. Never finished it though. Could be a good starting point for you:
https://github.com/eNeRGy164/fake-xrm-easy/blob/EX-Metadata/FakeXrmEasy.Shared/Metadata/MetadataLayer.cs

**Comment by DigitalFlow** [comment]
@eNeRGy164: Thanks, I'll take a look at it

**Comment by jordimontana82** [comment]
Hi Florian,

I'm good thanks! You?

I was doing something slightly different, injecting metadata from a serialised xml from a crm organisation. Although being able to generate it from the ProxyTypesAssembly would be handy too. Busy this week with [Directions EMEA](http://www.directionsemea.com) but will catch up after guys ;)
