### ISSUE TITLE
Trying to set record back to Draft (ACTIVE) results in thrown error Ln152 in the CRUD file

### ISSUE THREAD

**Issue by clc136** [jordimontana82/fake-xrm-easy#248]
Trying to set record back to Draft (ACTIVE) results in thrown error Ln152 in the CRUD file

**Comment by rbnswartz** [comment]
@clc136 What error are you getting exactly? An example of the test you are running would also be useful in figuring out what is up.

**Comment by jordimontana82** [comment]
Hi @clc136 

Are you still getting this error? A unit test example would be handy as @rbnswartz suggested.

**Comment by jordimontana82** [comment]
Closing this one as no reply in about 2 years.
