### ISSUE TITLE
Your First Test throws below error

### ISSUE THREAD

**Issue by bipinshan** [jordimontana82/fake-xrm-easy#251]
System.IO.FileLoadException : Could not load file or assembly 'FakeItEasy, Version=4.0.0.0, Culture=neutral, PublicKeyToken=eff28e2146d5fd2c' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
[xUnit.net 00:00:01.4396057]       ---- System.IO.FileLoadException : Could not load file or assembly 'FakeItEasy, Version=3.2.0.0, Culture=neutral, PublicKeyToken=eff28e2146d5fd2c' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
[xUnit.net 00:00:01.4424875]       Stack Trace:
[xUnit.net 00:00:01.4435781]            at FakeXrmEasy.XrmFakedContext.GetFakedOrganizationService(XrmFakedContext context)
[xUnit.net 00:00:01.4440260]            at FakeXrmEasy.XrmFakedContext.GetOrganizationService()
[xUnit.net 00:00:01.4444171]         E:\UnitTestProjectFakeXrmEasy\UnitTest1.cs(66,0): at UnitTestProjectFakeXrmEasy.UnitTest1.TestMethod1()

--Code

using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;

using Xunit;
using FakeItEasy;
using FakeXrmEasy;

using System.Collections.Generic;
using Microsoft.Xrm.Sdk;
using System.Linq;
using System.Reflection;

namespace UnitTestProjectFakeXrmEasy
{
    public class UnitTest1
    {
        [Fact]
        public void TestMethod1()
        {
            //Ok, this is going to be our test method body

            //But before doing anything...

            //  FakeXrmEasy is based on the state-based testing paradigm, 
            //  which is made of, roughly, 3 easy steps:

            //1) We define the initial state of our test.

            //2) Then, we execute the piece of logic which we want to test, 
            //   which will produce a new state, the final state.

            //3) Finally, we verify that the final state is the expected state (assertions).

            //Let's implement those now

            // 1) Define the initial state
            // -----------------------------------------------------------------------

            //  Our initial state is going to be stored in what we call a faked context:

            var context = new XrmFakedContext();

            //You can think of a context like an Organisation database which stores entities In Memory.

            //We can also use TypedEntities but we need to tell the context where to look for them, 
            //this could be done, easily, like this:

            context.ProxyTypesAssembly = Assembly.GetAssembly(typeof(Account));

            //We have to define our initial state now, 
            //by calling the Initialize method, which expects a list of entities.

            var account = new Account() { Id = Guid.NewGuid(), Name = "My First Faked Account yeah!" };

            context.Initialize(new List<Entity>() {
                account
            });

            //With the above example, we initialized our context with a single account record

            // 2) Execute our logic
            // -----------------------------------------------------------------------
            //
            // We need to get a faked organization service first, by calling this method:

            var service = context.GetOrganizationService();

            // That line is the most powerful functionality of FakeXrmEasy
            // That method has returned a reference to an OrganizationService 
            // which you could pass to your plugins, codeactivities, etc, 
            // and, from now on, every create, update, delete, even queries, etc
            // will be reflected in our In Memory context

            // In a nutshell, everything is already mocked for you... cool, isn't it?

            // Now... 

            // To illustrate this...

            // Let's say we have a super simple piece of logic which updates an account's name

            // Let's do it!

            var accountToUpdate = new Account() { Id = account.Id };
            accountToUpdate.Name = "A new faked name!";

            service.Update(accountToUpdate);

            // Done!

            //We have successfully executed the code we want to test..

            // Now...

            // The final step is...

            // 3) Verify final state is the expected state
            // -----------------------------------------------------------------------
            //

            //We are going to use Xunit assertions.

            var updatedAccountName = context.CreateQuery<Account>()
                                    .Where(e => e.Id == account.Id)
                                    .Select(a => a.Name)
                                    .FirstOrDefault();

            //And finally, validate the account has the expected name
            Microsoft.VisualStudio.TestTools.UnitTesting.Assert.Equals("A new faked name!", updatedAccountName);

            // And we are DONE!

            // We have successfully implemented our first test!

        }
    }
}

**Comment by durgaprasadkatari** [comment]
Hi @jordimontana82, 
I am getting this error on initializing the fakedxrmcontext.  Could you please help to understand what exactly causing this issue.
System.Reflection.ReflectionTypeLoadException: 'Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.'

at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at FakeXrmEasy.XrmFakedContext..ctor()
   at
