### ISSUE TITLE
Method Not found

### ISSUE THREAD

**Issue by bipinshan** [jordimontana82/fake-xrm-easy#252]
Method not found: 'FakeItEasy.Configuration.IAfterCallSpecifiedWithOutAndRefParametersConfiguration FakeItEasy.ReturnValueConfigurationExtensions.ReturnsLazily(FakeItEasy.Configuration.IReturnValueConfiguration`1<!!0>, System.Func`4<!!1,!!2,!!3,!!0>)'.

--Code
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;

using Xunit;
using FakeItEasy;
using FakeXrmEasy;

using System.Collections.Generic;
using Microsoft.Xrm.Sdk;
using System.Linq;
using System.Reflection;

namespace UnitTestProjectFakeXrmEasy
{
    public class UnitTest1
    {
        [Fact]
        public void TestMethod1()
        {
            //Ok, this is going to be our test method body

            //But before doing anything...

            //  FakeXrmEasy is based on the state-based testing paradigm, 
            //  which is made of, roughly, 3 easy steps:

            //1) We define the initial state of our test.

            //2) Then, we execute the piece of logic which we want to test, 
            //   which will produce a new state, the final state.

            //3) Finally, we verify that the final state is the expected state (assertions).

            //Let's implement those now

            // 1) Define the initial state
            // -----------------------------------------------------------------------

            //  Our initial state is going to be stored in what we call a faked context:

            var context = new XrmFakedContext();

            //You can think of a context like an Organisation database which stores entities In Memory.

            //We can also use TypedEntities but we need to tell the context where to look for them, 
            //this could be done, easily, like this:

            context.ProxyTypesAssembly = Assembly.GetAssembly(typeof(Account));

            //We have to define our initial state now, 
            //by calling the Initialize method, which expects a list of entities.

            var account = new Account() { Id = Guid.NewGuid(), Name = "My First Faked Account yeah!" };

            context.Initialize(new List<Entity>() {
                account
            });

            //With the above example, we initialized our context with a single account record

            // 2) Execute our logic
            // -----------------------------------------------------------------------
            //
            // We need to get a faked organization service first, by calling this method:

            var service = context.GetOrganizationService();

            // That line is the most powerful functionality of FakeXrmEasy
            // That method has returned a reference to an OrganizationService 
            // which you could pass to your plugins, codeactivities, etc, 
            // and, from now on, every create, update, delete, even queries, etc
            // will be reflected in our In Memory context

            // In a nutshell, everything is already mocked for you... cool, isn't it?

            // Now... 

            // To illustrate this...

            // Let's say we have a super simple piece of logic which updates an account's name

            // Let's do it!

            var accountToUpdate = new Account() { Id = account.Id };
            accountToUpdate.Name = "A new faked name!";

            service.Update(accountToUpdate);

            // Done!

            //We have successfully executed the code we want to test..

            // Now...

            // The final step is...

            // 3) Verify final state is the expected state
            // -----------------------------------------------------------------------
            //

            //We are going to use Xunit assertions.

            var updatedAccountName = context.CreateQuery<Account>()
                                    .Where(e => e.Id == account.Id)
                                    .Select(a => a.Name)
                                    .FirstOrDefault();

            //And finally, validate the account has the expected name
            Microsoft.VisualStudio.TestTools.UnitTesting.Assert.Equals("A new faked name!", updatedAccountName);

            // And we are DONE!

            // We have successfully implemented our first test!

        }
    }
}

**Comment by jordimontana82** [comment]
Hi, could you try uninstalling FakeItEasy and reinstalling the same version referenced by FakeXrmEasy?

**Comment by jordimontana82** [comment]
FakeXrmEasy has a strict dependency on FakeItEasy v 1.3.2, from the nuspec file:

    <dependency id="FakeItEasy" version="[3.2.0]" />

**Comment by bipinshan** [comment]
Yes, I did uninstall and reinstall fakes assembly.

PFA files.

I am facing issue with Assemble update using Nuget packages, Even if I update the assemble it still says to update.

Thanks
![image](https://user-images.githubusercontent.com/3380476/31713420-d171c034-b41b-11e7-8867-29f4ac775715.png)
![capture](https://user-images.githubusercontent.com/3380476/31713434-e0601320-b41b-11e7-9eed-3790dc404ecc.PNG)

**Comment by eNeRGy164** [comment]
@jordimontana82 maybe FakeItEasy should be ILmerged as internal into FakeXrmEasy so we don't have this dependency version pain?

**Comment by jordimontana82** [comment]
@bipinshan  Looks like the issue here is that you where downgranding via Updates from v1.37.1 to v.1.23.0 at least based on the log? Is that correct? Please uninstalling, and then installing latest versions, not via an Update if you had a previous version already installed. And when installing, you only need to install FakeXrmEasy, FakeItEasy will be resolved automatically.

@eNeRGy164  These issues happen cause earlier versions of FakeXrmEasy didn't enforce FakeItEasy 3.2.0 whereas later version do that. Updates from 1.37.3 onwards should be ok.

**Comment by jordimontana82** [comment]
That version 3.2.0 was actually enforced from FakeXrmEasy version 1.25.0 onwards, so that's why you have these issues when upgrading from 1.23.0 <= 1.25.0

**Comment by eNeRGy164** [comment]
@jordimontana82 if you have the time, you might watch this video: https://www.youtube.com/watch?v=hswLqvv3kdw
Might give you some ideas about handling dependencies. (that's also my inspiration about the nuspec versions I changed recently)

**Comment by jordimontana82** [comment]
@eNeRGy164  that was a nice session :)  Got some nice ideas for future versions

**Comment by jordimontana82** [comment]
@bipinshan closing this specific issue as I didn't hear back anything... any questions let me know.
