### ISSUE TITLE
Adding metadata for N:1 relationship

### ISSUE THREAD

**Issue by MartinZ42** [jordimontana82/fake-xrm-easy#254]
Hi all
I'm having trouble creating a record with an N:1 relationship. The test below will throw an exception: 

> Relationship account_primary_contact does not exist in the metadata cache

```
[Fact]
public void CreateRecordWithNewRelatedRecord()
{
    var newContact = new Contact
    {
        Id = Guid.Parse("8AD0AA54-80C0-E711-80F3-00155D0AB600"),
        EntityState = EntityState.Unchanged,
    };

    var newAccount = new Account
    {
        Name = "Test account",
        account_primary_contact = newContact
    };

    var fakeXrm = new XrmFakedContext { ProxyTypesAssembly = Assembly.GetAssembly(typeof(Account)) };
    var service = fakeXrm.GetFakedOrganizationService();

    var accountId = service.Create(newAccount);
}
```
I've found out how to add metadata for a 1:N relationship:
```
fakeXrm.AddRelationship("account_primary_contact", new XrmFakedRelationship("entity1Attribute", "entity2Attribute", "entity1Name", "entity2Name"));
```
This will make the AssociateRequestExecutor class update the contact like this:
```
entityToUpdate[fakeRelationShip.Entity2Attribute] = associateRequest.Target;
```
That seems reasonable for a 1:N relationship and while it will not throw an exception for an N:1 relationship it looks like the wrong thing to do.
Can anyone tell me the correct way to add metadata for an N:1 relationship? Is it supported?

**Comment by jordimontana82** [comment]
Hi Martin,

Thanks for raising this. That's interesting, I believe "account_primary_contact" is the 1:N relationship, not the N:1 one correct? 

If you want to set the account's primary contact then there is this N:1 property instead:

     PrimaryContactId

    var newAccount = new Account
    {
        Name = "Test account",
        PrimaryContactId = newContact
    };

**Comment by jordimontana82** [comment]
Hi @MartinZ42 

This issue has been open for a while without hearing anything back so closing it.

Let me know if you are still having issues with it please.
