### ISSUE TITLE
IsDisabled field on SystemUser

### ISSUE THREAD

**Issue by Kraviecc** [jordimontana82/fake-xrm-easy#257]
Hi,

in a plugin, I'm checking whether a user is disabled or not (via IsDisabled field) so I need this field on SystemUser to be properly filled out in unit tests but unfortunately, it's always null. SetStateRequest works correctly but there is still no value in the field after executing this request.

**Comment by rbnswartz** [comment]
You could technically just set the isDisabled field directly. Unless your code is relying on SetStateRequest setting the value.

**Comment by Kraviecc** [comment]
Not really - this field is read only.

**Comment by jordimontana82** [comment]
Hi @Kraviecc ,

You can also populate read only fields by accessing the Attributes dictionary directly using the brackets notation.  I.e.

    ["isdisabled"] = {some value}  
    ["createdon"] = DateTime.UtcNow.

This "hack" works even for early bound entities, cause the attributes are nothing but Property accessors to the internal dictionary of key value pairs.

**Comment by Kraviecc** [comment]
Hi @jordimontana82,

I've tried this before and it was like `["IsDisabled"] = false`. After your comment I typed `["isdisabled"] = false` and it's working perfectly. Thank you and have a nice day :)

**Comment by jordimontana82** [comment]
No worries, yeah, all the internal properties use lower case naming convention, although the generated properties from crmsvcutil might be a combination of uppercase / lowercase :)
