### ISSUE TITLE
InsertOptionValueRequest not supported yet?

### ISSUE THREAD

**Issue by kmjones77** [jordimontana82/fake-xrm-easy#26]
Hi guys,

I am trying to use Context.Execute to execute an InsertOptionValueRequest but I am getting an error casting the OrganizationResponse that comes back to an InsertOptionValueResponse. Error below:

Unable to cast object of type 'Microsoft.Xrm.Sdk.OrganizationResponse' to type 'Microsoft.Xrm.Sdk.Messages.InsertOptionValueResponse'.

Any ideas?

Cheers,

Ken

**Comment by DigitalFlow** [comment]
Hi Ken,

which version of FakeXrmEasy are you using?
The InsertOptionValueRequest is not yet implemented and the newest version of FakeXrmEasy should even throw an exception when the request, that should be executed, was not implemented.

Kind Regards,
Florian

**Comment by kmjones77** [comment]
Hi there, I am using FakeXrmEasy 1.8.4.

**Comment by jordimontana82** [comment]
I need to push latest version into NuGet.. I couldn't yet. That version should indeed raise a PullRequestException

**Comment by jordimontana82** [comment]
Hey @kmjones77 

This is now implemented. There are other messages related to this like UpdateOptionSetValue, OrderOptionSetValue, and DeleteOptionSetValue. They would follow an approach similar to what I did for InsertOptionValueRequest.

Would you like to have a look? : )

**Comment by kmjones77** [comment]
Nice one!
