### ISSUE TITLE
How can I pass an EntityReferenceCollection to ExecutePluginWith<> method?

### ISSUE THREAD

**Issue by phamiltonwhitecapcanada** [jordimontana82/fake-xrm-easy#269]
Hi,

Does anyone know how I can pass an "EntityReferenceCollection" to a PlugIn from FakeXrmEasy? From what I understand, delete operations contain an EntityReferenceCollection as opposed to an EntityImageCollection when used within a PlugIn. The ExecutePluginWith<> method within FakeXrmEasy only accepts EntiyImageCollection. As a result, I haven't found a way to test delete operations using FakeXrmEasy.

I have a sample of my PlugIn code below.  As indicated, when an entity record is deleted, the Image Collection is an EntityReferenceCollection, and I had to branch my code accordingly:

			// Obtain the organization service reference.
				IOrganizationServiceFactory serviceFactory = (IOrganizationServiceFactory) serviceProvider.GetService(typeof(IOrganizationServiceFactory));
				IOrganizationService service = serviceFactory.CreateOrganizationService(context.UserId);

				Guid productGroupSubmissionID_Guid = new Guid();

				if (context.InputParameters.Contains("Target"))
				{
					if (context.InputParameters["Target"] is Entity)  //Create and Update statements have Entity objects....
					{
						tracingService.Trace("Target is an Entity...");
						tracingService.Trace(string.Format("There are {0} items in context.PostEntityImages", context.PostEntityImages.Count));

						tracingService.Trace("Creating postImage object");
						new_productnpd postEntityRecord = context.PostEntityImages["postImage"] as new_productnpd;

						if (postEntityRecord is null)
							tracingService.Trace("'postEntityRecord' is null...");
						else
							tracingService.Trace("'postEntityRecord' object created...");

						tracingService.Trace("Prior to tracing 'postEntityRecord' new_name");
						tracingService.Trace("'new_name' = : " + postEntityRecord.new_name);

						productGroupSubmissionID_Guid = postEntityRecord.new_products_npdid.Id; //Lookup parent Guid
						tracingService.Trace("'productGroupSubmissionID_Guid' = " + productGroupSubmissionID_Guid.ToString());
					}
					else if (context.InputParameters["Target"] is EntityReference) //This is a delete operation, we need to use EntityReference....
					{
						tracingService.Trace("Target is an EntityReference...");
						tracingService.Trace(string.Format("There are {0} items in context.PreEntityImages - the Logical name of the PreEntityImage is '{1}'", context.PreEntityImages.Count, context.PreEntityImages["deletedImage"].LogicalName));

						tracingService.Trace("Creating deletedImage object");
						new_productnpd preEntityRecord = context.PreEntityImages["deletedImage"] as new_productnpd;

						if(preEntityRecord is null)
							tracingService.Trace("'preEntityRecord' is null...");
						else
							tracingService.Trace("'preEntityRecord' object created...");

						productGroupSubmissionID_Guid = preEntityRecord.new_products_npdid.Id;
					}
				}

**Comment by eNeRGy164** [comment]
I use this extension method:

````csharp
        [DebuggerStepThrough]
        public static IPlugin ExecutePluginWithTargetReference<T>(this XrmFakedContext context, EntityReference target, string messageName = "Delete", int stage = 40)
            where T : IPlugin, new()
        {
            var pluginExecutionContext = context.GetDefaultPluginContext();
            pluginExecutionContext.InputParameters.Add(new KeyValuePair<string, object>("Target", target));
            pluginExecutionContext.MessageName = messageName;
            pluginExecutionContext.Stage = stage;

            return context.ExecutePluginWith<T>(pluginExecutionContext);
        }
````

Have a bunch more that I should submit some day

**Comment by phamiltonwhitecapcanada** [comment]
Thanks.  I will need some time to look into this and will reply back when I have it working.

**Comment by jordimontana82** [comment]
+1 on the extension method suggested by Michaël.

We could add it to the framework too.

**Comment by eNeRGy164** [comment]
Just did with #270

**Comment by eNeRGy164** [comment]
This can be closed?

**Comment by phamiltonwhitecapcanada** [comment]
Yes...we can close this.  Thank you so much!

**Comment by jordimontana82** [comment]
Thank you guys.
