### ISSUE TITLE
System.Exception: Entity some_entity does not exist in the metadata cache

### ISSUE THREAD

**Issue by kmjones77** [jordimontana82/fake-xrm-easy#27]
Hello,

I am getting the above error when trying to query the context for the entity some_entity when I haven't injected any dummy instances of some_entity into the context.

Any ideas how to get around this?

Ken

Using FakeXrmEasy 1.8.4

**Comment by DigitalFlow** [comment]
Hi Ken,

if you are developing early bound. then introduce your types to FakeXrmEasy like this:

```CSharp
context.ProxyTypesAssembly = Assembly.GetAssembly(typeof(some_entity));
```

Otherwise you would have to use dummy instances.

Kind Regards,
Florian

**Comment by jordimontana82** [comment]
Thx @DigitalFlow :+1: 

Indeed, that's what the framework supports for now. 

I was originally thinking on incorporating a list of entity metadata's which follow the Metadata specification from CRM when I first designed this... but I thought it was just overcomplicated.

**Comment by kmjones77** [comment]
This works and is fine for me! No need to change anything!

**Comment by kmjones77** [comment]
Hi,

@jordimontana82 @DigitalFlow how do associate multiple entitties?

Ken

**Comment by kmjones77** [comment]
Only a single is needed as long as they are in the same assembly.

**Comment by tjahnks23** [comment]
I have added the 'ProxyTypesAssembly' and still get this error
