### ISSUE TITLE
Retrieving statuscode Optionset values for an attribute?

### ISSUE THREAD

**Issue by bwmodular** [jordimontana82/fake-xrm-easy#278]
I've been trying to work out if I can retrieve optionset values for the statuscode attribute using a RetrieveAttributeRequest, but I can't get it working.

I've initialised the metadata, and fake option set values have been successful added to the context.

However, when I carry out a RetrieveAttributeRequest, the resulting RetrieveAttributeResponse does not contain the optionset data. With a real CRM instance, I can cast the RetrieveAttributeResponse as either StatusAttributeMetadata or EnumAttributeMetadata and iterate through the OptionSet.Options, but these don't exist in the faked version. I get 'Object reference not set to an instance of an object' when trying to list the OptionSet Options.

Am I missing something?

Here's some sample code:

`void Main()
{
	XrmFakedContext fakedContext = new XrmFakedContext
	{
		ProxyTypesAssembly = (Assembly.GetAssembly(typeof(bsp_trv_insuranceapplication)))
	};

	string attributeName = "statuscode";
	string label = "A faked label";

	var entityMetadata = new EntityMetadata()
	{
		LogicalName = "bsp_trv_insuranceapplication"
	};
	
	StatusAttributeMetadata enumAttribute = new StatusAttributeMetadata() { LogicalName = attributeName };

	entityMetadata.SetAttributeCollection(new List<AttributeMetadata>() { enumAttribute });

	var req = new InsertOptionValueRequest()
	{
		EntityLogicalName = bsp_trv_insuranceapplication.EntityLogicalName,
		AttributeLogicalName = attributeName,
		Label = new Label(label, 0)
	};

	fakedContext.InitializeMetadata(entityMetadata);

	var fakedService = fakedContext.GetFakedOrganizationService();
	fakedService.Execute(req);
	

	//Check the optionsetmetadata was updated
	var key = string.Format("{0}#{1}", bsp_trv_insuranceapplication.EntityLogicalName, attributeName);

	Assert.IsTrue(fakedContext.OptionSetValuesMetadata.ContainsKey(key));

	var option = fakedContext.OptionSetValuesMetadata[key].Options.FirstOrDefault();
	
	Assert.AreEqual(label, option.Label.LocalizedLabels[0].Label);

	// Get a list of Option Set values for the Status Reason fields from its metadata
	RetrieveAttributeRequest attReq = new RetrieveAttributeRequest();
	attReq.EntityLogicalName = "bsp_trv_insuranceapplication";
	attReq.LogicalName = "statuscode";
	attReq.RetrieveAsIfPublished = true;

	RetrieveAttributeResponse attResponse =  (RetrieveAttributeResponse)fakedService.Execute(attReq);

	// Cast as StatusAttributeMetadata
	StatusAttributeMetadata statusAttributeMetadata = (StatusAttributeMetadata)attResponse.AttributeMetadata;

	// This gives us Object reference not set to an instance of an object.
	foreach (var statusOption in statusAttributeMetadata.OptionSet.Options)
	{
		Console.WriteLine("Key " + statusOption.Value + "                    Value: " + statusOption.Label.UserLocalizedLabel.Label);
	}

	// Cast as EnumAttributeMetadata
	EnumAttributeMetadata enumAttributeMetadata = (EnumAttributeMetadata)attResponse.AttributeMetadata;
	// This gives us Object reference not set to an instance of an object.
	foreach (OptionMetadata enumOption in enumAttributeMetadata.OptionSet.Options)
	{
		Console.WriteLine("Key " + enumOption.Value + "                    Value: " + enumOption.Label.UserLocalizedLabel.Label);
	}
}`

Happy to work on this if it needs doing and is possible....

**Comment by jordimontana82** [comment]
Hi Ben,

I'll take a look at this whenever I'm back from London :)

**Comment by bwmodular** [comment]
Looked like CRMSaturday was a great success. Let me know if I can help with this one - happy to do some work on it if you point me in the right direction....
