### ISSUE TITLE
[Not]EqualBusinessId operator implementation.

### ISSUE THREAD

**Issue by fallasd** [jordimontana82/fake-xrm-easy#285]
I am completely new to Dynamics CRM but have inherited some legacy code and am adding unit tests when it becomes clear that a change or bug fix is required. Searching found FakeXrmEasy which has proven to be a great tool - many thanks!

One class that I now need to unit-test uses the eq-businessid operator in some FetchExpression constructs. When presented to FakeXrmEasy in unit tests, a PullRequestException is thrown.

In order to allow me to proceed, I have forked the project and added a few lines to XrmFakedContext.cs, XrmFakedContext.CodeActivities.cs and XrmFakedContext.Queries.cs (see attached). The thrust of the changes is to enable a unit test to explicitly set the BusinessUnit EntityReference which is then used for comparison by the eq-businessunitid operator.

I have written a couple of unit tests (see attached) following a similar pattern to that being used for eq-userid.

I would be grateful if you could comment on these additions.

Attachments:
[FakeXrmContextTests..cs.txt](https://github.com/jordimontana82/fake-xrm-easy/files/1738559/FakeXrmContextTests.cs.txt)
[XrmFakedContext.CodeActivities.cs.txt](https://github.com/jordimontana82/fake-xrm-easy/files/1738562/XrmFakedContext.CodeActivities.cs.txt)
[XrmFakedContext.cs.txt](https://github.com/jordimontana82/fake-xrm-easy/files/1738563/XrmFakedContext.cs.txt)
[XrmFakedContext.Queries.cs.txt](https://github.com/jordimontana82/fake-xrm-easy/files/1738564/XrmFakedContext.Queries.cs.txt)

**Comment by jordimontana82** [comment]
@fallasd   Thx a mill for this!  It would be a lot easier to review what has changed if you push your changes to your fork and then issue a Pull Request so I can review?

Thanks!

**Comment by jordimontana82** [comment]
Closing as it is available in 1.40.0 now.
