### ISSUE TITLE
AddUserToRecordTeamRequest Fake executer is generating StackOverflowExceptions

### ISSUE THREAD

**Issue by mathiasbl** [jordimontana82/fake-xrm-easy#289]
See implementation

https://github.com/jordimontana82/fake-xrm-easy/blob/master/FakeXrmEasy.Shared/FakeMessageExecutors/AddUserToRecordTeamRequest.cs

**Comment by jordimontana82** [comment]
Looks like this fake message executor was introduced by @jjarmuzekadm  but he's no longer a github user....  Anyway, the message implementation shouldn't call itself (hence the StackOverflowException), it should probably populate the intersect entity between teams and users instead.

**Comment by Kraviecc** [comment]
@jordimontana82 He is still valid github user, just commits aren't associated with this account (jarmoosh).

If no one is taking care of this one I'll take a look in spare time.
