### ISSUE TITLE
System.TypeLoadException 'Microsoft.Crm.Sdk.Messages.RemoveFromQueueRequest'

### ISSUE THREAD

**Issue by nickbrandl** [jordimontana82/fake-xrm-easy#291]
Hi,
I'm working on a CRM 2013 implementation and when trying to run a test, I receive the following exception:
System.TypeLoadException : No se puede cargar el tipo **'Microsoft.Crm.Sdk.Messages.RemoveFromQueueRequest' del ensamblado'Microsoft.Crm.Sdk.Proxy, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.**
Stack Trace:
     en FakeXrmEasy.FakeMessageExecutors.RemoveFromQueueRequestExecutor.GetResponsibleRequestType()
     en FakeXrmEasy.XrmFakedContext.<>c.<.ctor>b__116_2(IFakeMessageExecutor t)
     en System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
          en System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
            en FakeXrmEasy.XrmFakedContext..ctor()
            en CRM.WorkflowsTests.EmailableCustomerControllerTests.IsUserEmailableValid()

I've checked my referenced assembly versions and updated to 6.0.0 version, but the issue is still there.

**Comment by rbnswartz** [comment]
@nickbrandl What version of FakeXrmEasy are you using?

**Comment by nickbrandl** [comment]
Hi @rbnswartz , sorry for the delay. I'm using FakeXrmEasy.2013 version 1.40.0.
My IDE is VS2013 community, targeting .net 4.5 and Dynamics CRM 6.0.0 assemblies.

**Comment by jordimontana82** [comment]
Looks like that message was added in a service pack 1 in 2013. Could you try upgrading your nuget package to a higher minor version and see if works?

https://msdn.microsoft.com/en-us/library/microsoft.crm.sdk.messages.removefromqueuerequest(v=crm.6).aspx

Maybe try with 6.1.2 to make sure you are on the really latest:

https://www.nuget.org/packages/Microsoft.CrmSdk.CoreAssemblies/6.1.2

**Comment by jordimontana82** [comment]
Any luck with this Nick?  Will close the issue, otherwise please tell me and will reopen

**Comment by teppolainio** [comment]
I faced this same issue today when adding reference to newest version (1.54.0) of FakeXrmEasy.2013 into a project where it wasn't yet referenced. 

FakeXrmEasy.2013 seems to state dependency as `Microsoft.CrmSdk.CoreAssemblies (>= 6.0.0 && < 7.0.0)` even though Microsoft.Crm.Sdk.Messages.RemoveFromQueueRequest is introduced on Microsoft.CrmSdk.CoreAssemblies version 6.1.0.

I think dependency should be corrected to be `Microsoft.CrmSdk.CoreAssemblies (>= 6.1.0 && < 7.0.0)`.
