### ISSUE TITLE
Question: Missing implementation for WorkflowMode

### ISSUE THREAD

**Issue by fallasd** [jordimontana82/fake-xrm-easy#295]
Testing with FakeXrmEasy was going well until today. I now get an exception which halts everything in its tracks:
Message: System.AggregateException : One or more errors occurred.
---- System.TypeLoadException : Method 'get_WorkflowMode' in type 'FakeXrmEasy.XrmFakedWorkflowContext' from assembly 'FakeXrmEasy, Version=1.38.0.0, Culture=neutral, PublicKeyToken=d91a65dda907a34f' does not have an implementation.

I am using a forked FakeXrmEasy which I build locally (there are a couple of reasons for this which I will expand on at a later date). I note that the implementation of XrmFakedWorkflowContext.WorkflowMode is preceded by an #if pragma which I assume is affecting this.

How do I correctly build my locally forked solution so that the WorkflowMode implelentation becomes 'visible'?

**Comment by fallasd** [comment]
I think I have answered my own question. If I add a reference to the FakeXrmEasy library in FakeXrmEasy.9, my tests are working again. I think I lost that link when I tried to install version 1.40 from NuGet.
So, for the moment I will stick to my forked solution. 
Again, thanks for the library - sure takes some of the pain out of testing CRM

**Comment by durgaprasadkatari** [comment]
Hi, I am facing the same issue. Getting the below error when I am trying to run my unit test cases. Could you please help to resolve this issue.
Method 'get_WorkflowMode' in type 'FakeXrmEasy.XrmFakedWorkflowContext' from assembly 'FakeXrmEasy, Version=1.51.1.0, Culture=neutral, PublicKeyToken=d91a65dda907a34f' does not have an implementation.

**Comment by jordimontana82** [comment]
@durgaprasadkatari could you please double check if you're usign the right version of FakeXrmEasy for the CRM SDK version you're using? Some properties are only available in certain version of the CRM SDK. This is probably the cause like @fallasd was suggesting...

**Comment by durgaprasadkatari** [comment]
@jordimontana82 I have removed all the references and installed FakeXrmEasy.9 from nuget which solved the issue. Thank you.
