### ISSUE TITLE
Difference between fake-xrm-easy and easy repro

### ISSUE THREAD

**Issue by mjillella** [jordimontana82/fake-xrm-easy#296]
Hi,

We are trying to automate DCRM product and have been using easyrepro provided by microsoft. I came across this and want to know the difference between this repro and the easy repro, Can you help me understand please. And will this work with the new unified Interface as well? 

Thanks

**Comment by eNeRGy164** [comment]
Fake Xrm Easy tests your plugin code in isolation without an actual CRM server/instance

Easy Repo is to test CRM via the UI, of an actual running server/instance. Which underneath might trigger your plugin code as well. But also many other things like security, scripting, forms, etc.

**Comment by jordimontana82** [comment]
They apply at 2 different stages of the overall test automation process. FakeXrmEasy is meant to be used for unit testing so you can use it to run it before you even deploy your changes to CRM.  

With EasyRepro you need to deploy all your changes before you can start testing anything, it's generally for integration / UI test automation.

2 different tools for 2 different tasks.

**Comment by jordimontana82** [comment]
Closing this one, if you still have questions please ask and will reopen :)
