### ISSUE TITLE
Microsoft.Xrm.Sdk.OptionSetValueCollection is not supported

### ISSUE THREAD

**Issue by VolodymyrTrishyn** [jordimontana82/fake-xrm-easy#297]
Hi,

Please do support of data type Microsoft.Xrm.Sdk.OptionSetValueCollection in "FakeXrmEasy.9" version="1.40.0" 

Now we have to write wrappers for serialization and deserialization of data of this type in FakeXrmEasy.

It would be good if this type of data is supported FakeXrmEasy natively.

Thanks

**Comment by rbnswartz** [comment]
@VolodymyrTrishyn What exactly are you trying to do? Can you submit a code sample?

**Comment by VolodymyrTrishyn** [comment]
Sample:
In method 

FakeXrmEasy.Extensions.EntityExtensions.CloneAttribute(object attributeValue)

The attributeValue can be of the type Microsoft.Xrm.Sdk.OptionSetValueCollection

But its support is not in the code.

I think in this place something should be in style like:

else if (type == typeof(OptionSetValueCollection))
{
	var original = (attributeValue as OptionSetValueCollection);
	return new OptionSetValueCollection(original.Value);
}

and so in other parts of the code, for example in the class
FakeXrmEasy.Extensions.FetchXml.XmlExtensionsForFetchXml

**Comment by jordimontana82** [comment]
HI @VolodymyrTrishyn , is this to support multiple option set values (i.e. >= v9 multi option set)?

**Comment by jordimontana82** [comment]
Hi @pedropaulovc, !

You started working on some changes in your fork for adding support for the new multiple option set value field.  Is that still in progress? Would you like to create a new PR?

**Comment by pedropaulovc** [comment]
@jordimontana82 Thanks for checking in. I should confess that I haven't worked on this feature in a while. The last time I worked on it, I realized that I need to spend more time getting familiar with the code that generates query expressions in FakeXrmEasy. Also, I need to review how an actual Dynamics server responds to different queries operators using multiselect optionsets, which is time consuming. My apologies for the delay!

**Comment by pedropaulovc** [comment]
@jordimontana82 I finally got some time to spare and managed to raise PR #351 🎉🎉🎉. It's a sizable changeset so please let me know if there's something I can do to help you reviewing it. I appreciate your effort maintaining this project, it's awesome!

**Comment by jordimontana82** [comment]
Hi @pedropaulovc !

This is awesome, I'll reviewing during the next couple of days (go live this week :P ) and get back to you as soon as possible. 👍 

Cheers,

**Comment by jordimontana82** [comment]
This has been merged and pushed to the latest version 1.38.0

Still some improvements to be made which have been moved to #354
