### ISSUE TITLE
Improvement: Be able to fallback to injected metadata whenever ProxyTypesAssembly is null

### ISSUE THREAD

**Issue by jordimontana82** [jordimontana82/fake-xrm-easy#303]
This would provide precise type checking in queries for late bound entities (or more precisely, when no early bound assembly is used), and so it would remove arithmetic exceptions.

**Comment by rbnswartz** [comment]
Would really appreciate this. I have a couple cases where I can't test things because  it is using early bound entities. Maybe when I hit that code again I'll give it a shot.

**Comment by jordimontana82** [comment]
Hi Reuben,

Would you like to spend some time on this? It would be basically retrieving types from the metadata that was passed to InitializeMetadata() whenever the early bound attribute wasn't found in [FindReflectedAttributeType method](https://github.com/jordimontana82/fake-xrm-easy/blob/756307c6baff21c1752e3cf5399d9b49c263b329/FakeXrmEasy.Shared/XrmFakedContext.Queries.cs#L62)

**Comment by jordimontana82** [comment]
Hi @rbnswartz !

I've pushed an initial implementation for this cause I needed it....  it would be amazing if you could add some extra tests for each crm data type so code coverage will go a little bit cause I really didn't have a chance.....
:)

**Comment by rbnswartz** [comment]
@jordimontana82 Yeah I'll give it a shot when I get a spare moment.
