### ISSUE TITLE
fakeCRMContext not working

### ISSUE THREAD

**Issue by JonCot** [jordimontana82/fake-xrm-easy#306]
Hi Jordi

I am trying to use the FakeCRMContext in my unit tests. Next to the UsePipeleSimulation (false) I tried adding the ProxyTypesAssembly
 => context.ProxyTypesAssembly = Assembly.GetAssembly(typeof(Context)); 
When running the rest it fails on retrieving data stored in the Context. the exact errormessage is: 

◢ | $exception | {"Entity 'research' is not found in the metadata cache"} | System.Exception

Is there a possible solution or workaround for this?

**Comment by jordimontana82** [comment]
Hi Jonathan,

Could you try passing the early bound type instead?  

    context.ProxyTypesAssembly = Assembly.GetAssembly(typeof(Research)) 

(assuming research is the entity class generated by crmsvcutil).

In addition, it's generally enough to pass the entities as part of the .Initialize() method only, and it will pick the ProxyTypesAssembly automatically.

You'll need to call that explicitly when not using .Initialize really.

Will close this issue now, please let me know and I'll reopen if you still have issues :)

**Comment by JonCot** [comment]
retrieving an object of the Entity research isn't a problem, the problem during the test is retrieving the attributenames of that specific entity whilst using XrmFakedContext()

this part of code throws the error:

```
RetrieveEntityRequest researchRequest = new RetrieveEntityRequest()
            {
                LogicalName = Research.EntityLogicalName,
                EntityFilters = EntityFilters.Attributes,
                RetrieveAsIfPublished = true
            };

RetrieveEntityResponse researchAttributes = (RetrieveEntityResponse)crmDataService.Execute(researchRequest);
```
I need to do this for multiple types of entities.

**Comment by neilgibert1234** [comment]
@JonCot  Did you get this working? I'm having the same issue.

**Comment by jordimontana82** [comment]
Right, did you try injecting metadata with .InitializeMetadata to see if it makes a difference?

**Comment by neilgibert1234** [comment]
@jordimontana82 - Yes got this working thanks
Just need to create a new EntityMetadata and add it to the InitializeMetadata collection

**Comment by jordimontana82** [comment]
Closing this issue so... thx!
