### ISSUE TITLE
Expose faked IServiceEndpointNotificationService

### ISSUE THREAD

**Issue by synesthesia** [jordimontana82/fake-xrm-easy#308]
Follow on to PR #107 

I'm writing a couple of plugins that post an augmented execution context (with various shared variables) to a ServiceEndpoint. To test this I need to access the same faked instance of IServiceEndpointNotificationService that is returned to the plugin code by [GetFakedServiceProvider](https://github.com/jordimontana82/fake-xrm-easy/blob/master/FakeXrmEasy.Shared/XrmFakedContext.Plugins.cs#L262)

~~I was hoping to make this work by sub-classing XrmFakedContext, but the deeper I get into the code the more I realise I am going to have to port across to my sub-class because of the lack of virtual methods.~~

I _have_ managed to make this work by subclassing XrmFakedContext, but I did need approx 100 lines from the base class to deal with lack of virtuals. Almost all of this is copy and paste apart from a couple of line changes in GetFakedServiceProvider.

I think the change should just be a matter of adding an attribute to hold the fake, and exposing a Getter. If that makes sense @jordimontana82  So I'm (Still) happy to put together a pull request - what do you think?

**Comment by jordimontana82** [comment]
Thanks Julian.

Yep, feel free to submit a PR and I'll take a look.

Cheers!
