### ISSUE TITLE
XrmRealContext constructor with a pure connection string

### ISSUE THREAD

**Issue by AlexanderGurinov** [jordimontana82/fake-xrm-easy#311]
Recently I shoot into my leg because of not very clear of the name of a variable in this constructor

https://github.com/jordimontana82/fake-xrm-easy/blob/756307c6baff21c1752e3cf5399d9b49c263b329/FakeXrmEasy.Shared/XrmRealContext.cs#L38

I think that better name for this variable should be "connectionStringName".
As a workaround I am used another constructor with IOrganizationService in which I pass a charged instance of CrmServiceClient.

For backward compatibility, it would be great to add a not mandatory constructor parameter. Thus constructor will be looking like this

```
public XrmRealContext(string connectionString, bool isExplicit = false)
{
    // Logic here
}
```
Thank you :)

**Comment by jordimontana82** [comment]
Thx Alexander!

Agree it might be misleading.... 

Would you like to change it connectionStringName and submit a PR? :)
