### ISSUE TITLE
Must be a non-abstract type with a public parameterless constructor in order to use it as parameter 'T' in the generic type or method 'XrmFakedContext.ExecutePluginWith<T>(XrmFakedPluginExecutionContext)'

### ISSUE THREAD

**Issue by AndrewYueLiu** [jordimontana82/fake-xrm-easy#319]
I am trying to apply unit to a plugin, which is created by the latest Microsoft Dynamics 365 Developer Toolkit. Because my plugin is based from the PluginBase class instead of IPlugin class, so I got the error message when I try try the mothed "ExecutePluginWith". The error is "must be a non-abstract type with a public parameterless constructor in order to use it as parameter 'T' in the generic type or method 'XrmFakedContext.ExecutePluginWith<T>(XrmFakedPluginExecutionContext)'". 

Even I removed the abstract keyword from `  public abstract class PluginBase : IPlugin` at the PluginBase.cs file, and rebuild my plugin, but in unittest it is still not working. 

Any help? 
Thanks

**Comment by bwmodular** [comment]
You just need to add a parameterless constructor to your plugin. so if your plugin is called 'PreUpdateContact' you just need to add a constructor like this:
        public PreUpdateContact() : base(typeof(PreUpdateContact))
        {
        }

Should work fine after that. (Put the PluginBase class back to how it was before).

**Comment by jordimontana82** [comment]
That's exactly it :)
