### ISSUE TITLE
Implement Create and Delete Request

### ISSUE THREAD

**Issue by DigitalFlow** [jordimontana82/fake-xrm-easy#32]
Hey Jordi,

Since the Organization Service Context also sends Create and Delete requests when doing those actions, those requests should be implemented.
Will do that and send a PR.

Kind Regards,
Florian

**Comment by jordimontana82** [comment]
Great. You could reuse the CRUD implementation already done isn't? just wrap / refactor what's there into 2 different requests: CreateRequest and DeleteRequest.

**Comment by DigitalFlow** [comment]
Yes, that was the plan.
