### ISSUE TITLE
Trace will fail if JSON is attempted to be traced

### ISSUE THREAD

**Issue by TarogStar** [jordimontana82/fake-xrm-easy#331]
There appears to be a current issue with Console.WriteLine that causes JSON strings to give an error: [System.Console.WriteLine(JSON.stringify(...)) does not work](https://github.com/sebastienros/jint/issues/244)

This causes Testing to fail.  Would you like a pull request with an option to disable Console.Writeline?  Or possibly check for "{" (bracket) and either remove the bracket or do something else to cause it not to fail?  It is successful if I replace my brackets with parenthesis, but that makes it not quite as easy to directly use the json data elsewhere.

**Comment by jordimontana82** [comment]
Any updates on this? Did it work with Output encoding?

**Comment by jordimontana82** [comment]
Any updates re this?

**Comment by 209458** [comment]
I just happen to get the same problem and have an ongoing fix.

**Comment by jordimontana82** [comment]
Great!
