### ISSUE TITLE
Update version 1.46.1 fail

### ISSUE THREAD

**Issue by phuocle** [jordimontana82/fake-xrm-easy#333]
My plugin reference to ```Microsoft.CrmSdk.CoreAssemblies``` version ```9.0.2.4```.

Now, I try update to version ```1.46.1``` and it fail with the following message
```
Attempting to resolve dependencies for package 'FakeXrmEasy.365.1.46.1' with DependencyBehavior 'Lowest'
Unable to resolve dependencies. 'Microsoft.CrmSdk.CoreAssemblies 9.0.2.4' is not compatible with 'FakeXrmEasy.365 1.46.1 constraint: Microsoft.CrmSdk.CoreAssemblies (>= 8.2.0.1 && < 9.0.0)'.
```

**Comment by jordimontana82** [comment]
Hi @phuocle , you're using nuget package "FakeXrmEasy.365", try using FakeXrmEasy.9 for v9 instead. This is in the readme. Given there will be more and more updates, we're changing the package naming convention to match the major version:

![image](https://user-images.githubusercontent.com/3968950/44201962-8b31a480-a142-11e8-8b3c-df9112170761.png)

Hope this helps

**Comment by amwayDarshana** [comment]
VS 2017 and FakeXRMEasy.365 .

**Comment by amwayDarshana** [comment]
My Dynamics 365 environment has upgraded to v9 recently, And I cannot use this FakeXRMEaasy anymore. Could you please tell me when you can release a new version that with new CRM update?

**Comment by FixRM** [comment]
@amwayDarshana,

please use other v9 NuGet package instead of D365: https://github.com/jordimontana82/fake-xrm-easy/issues/333#issuecomment-413490016.

**Comment by amwayDarshana** [comment]
I tried to user FakeXrmEasy.2016 and it s also not align with Dynamics 365. It gives the same error that I posted in this thread. Could you suggest me which nuget package can I try to mock my CRM custom plugins and workflows....
![image](https://user-images.githubusercontent.com/42367701/51163057-6ef18980-18d3-11e9-93c0-f6b783557bd5.png)

**Comment by FixRM** [comment]
@amwayDarshana,

Please use FakeXrmEasy.v9. Version history is: 2011 -> 2013 -> 2016 -> D365 -> v9.

**Comment by amwayDarshana** [comment]
@FixRM. Thanks for the quick update. I will try with this.
