### ISSUE TITLE
Multiple simultaneous early-bound assemblies aren't supported

### ISSUE THREAD

**Issue by teppolainio** [jordimontana82/fake-xrm-easy#334]
Hi,

We've had for some time issues on unit testing some of our services with fake-xrm-easy because in our service is multiple assemblies specifying their own sets of early-bound classes. Entities defined by these classes aren't overlapping. SDK libraries handle well this kind of setup and there's even a method [OrganizationServiceProxy.EnableProxyTypes(Assembly)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.client.organizationserviceproxy.enableproxytypes) for manually tweaking with assemblies if those aren't resolved correctly automatically.

Current version of fake-xrm-easy supports only single assembly of reading early-bound classes. This has prevented us from doing unit testing. I've prototyped a bit bit and if you don't mind I'd like to introduce method XrmFakedContext.EnableProxyTypes(Assembly) which allows one to use early-bound classes from multiple assemblies in tests:

`using DAO1 = Some.Assembly.DAO;`
`using DAO2 = Another.Assembly.DAO;`
`var faked = new FakeXrmEasy.XrmFakedContext();`
`faked.EnableProxyTypes(typeof(DAO1.prefix_CustomEntity).Assembly);`
`faked.EnableProxyTypes(typeof(DAO2.SystemUser).Assembly);`
`faked.Initialize(crmDb);`

**Comment by jordimontana82** [comment]
Hi Teppo,

This would be a nice addition indeed. And it shouldn't be a big deal to extend the existing methods FindReflectedType and FindReflectedAttribute to search through a list of assemblies instead of just one.

Would you like to spend some time on this and submit a PR?

**Comment by teppolainio** [comment]
Yes, it didn't seem to be too big deal to implement. I think changes are needed only within FindReflectedType.

I'll submit a PR within few days.

**Comment by jordimontana82** [comment]
Closed after merging #335
