### ISSUE TITLE
Entity metadata not found

### ISSUE THREAD

**Issue by nealrobben** [jordimontana82/fake-xrm-easy#338]
I am using FakeXrmEasy version 1.37.2

In one of my unit tests I call a function that tries to get the EntityTypeCode for a certain entity.

However, everytime this code runs I get an exception saying: "Entity 'xxx' is not found in the metadata cache".

The following call goes wrong:

            var retrieveEntityResponse = (RetrieveEntityResponse)(await _context.XrmContext.ExecuteAsync(
                    new RetrieveEntityRequest
                    {
                        LogicalName = entity,
                        EntityFilters = EntityFilters.Attributes
                    }));

            return retrieveEntityResponse.EntityMetadata;

I have pointed my context to the assembly with my classes:

            var context = new XrmFakedContext
            {
                ProxyTypesAssembly = Assembly.GetAssembly(typeof(cgkcol_planningitemdetail))
            };

I also have made sure to initialize my context with at least one record of the type for which I want to retrieve the EntityTypeCode.

Is there anything more I need to do to be able to get the EntityTypeCode when running my unit test?

**Comment by jordimontana82** [comment]
Hi Neal,

That version is a bit too old at this stage... can you try with 1.47.0 first and see if it makes any difference?

**Comment by jordimontana82** [comment]
HI Neal,

Did you try using .InitializeMetadata()? 

Or else could try posting a full unit test so we can reproduce?

**Comment by nealrobben** [comment]
Jordi,

I already had some code in my test to initialize my set of entities:

            context.Initialize(new List<Entity> {
                ...
            });

I thought that was all I needed. After your comment I also added the following (before the code above):

            context.InitializeMetadata(new EntityMetadata
            {
                LogicalName = MyEntity.EntityLogicalName 
            });
After adding this, my code no longer throws an exception when retrieving the EntityTypeCode for "MyEntity", but just returns null which is enough to make my test actually run.

If I understand correctly, the initialization of the entities in my context and the metadata have to be done separately?
So if I need my entity metadata somewhere in my code I have to explicitly initialize the entity metadata in my unit test?

**Comment by jordimontana82** [comment]
Correct. If you need to unit tests that need metadata (like RetrieveEntityRequest) you'll need to use .InitializeMetadata.

There are helper methods like .SetAttributeCollection() to inject attribute metadata for one entity. 

[Here's one example](https://github.com/jordimontana82/fake-xrm-easy/blob/b05fffaffb9fa86aeda0abb969677c4632b8154f/FakeXrmEasy.Tests.Shared/FakeContextTests/RetrieveAttributeRequestTests/RetrieveAttributeRequestTests.cs#L17-L28)

I'm closing this isssue, if you have any other questions please do let me know.
