### ISSUE TITLE
Add support for Alternate Keys

### ISSUE THREAD

**Issue by BetimBeja** [jordimontana82/fake-xrm-easy#344]
Hi,
since Dynamics CRM Online 2015 Update 1 there is the possibility to use alternate keys for entities as specified [here](https://docs.microsoft.com/en-us/previous-versions/dynamicscrm-2015/developers-guide/dn933045%28v%3dcrm.7%29).
This framework seem to ignore the existence of the alternate keys. They are required if we need to test plugins which make use of alternate keys (and if we want to implement UpsertRequest).
Also the RetrieveRequest is implemented as [IOrganizationService.Retrieve](https://github.com/jordimontana82/fake-xrm-easy/blob/ecf66fb1e83d6d6d97577cd5f0d868d7a93437ad/FakeXrmEasy.Shared/FakeMessageExecutors/RetrieveRequestExecutor.cs#L26) and probably would have been better to do the other way around since IOrganizationService.Retrieve works only by id but you can retrieve an Entity by using alternate keys with the RetrieveRequest.

Best regards,
Betim Beja.

**Comment by jordimontana82** [comment]
@BetimBeja Indeed, there is no implementation to handle Alternate Keys at the minute.

It would need to also handle EntityReferences where you can pass the alternate key instead of the Id.

**Comment by FixRM** [comment]
@BetimBeja,

Can you please give a sample of using Alternative Keys in unit tests?

**Comment by BetimBeja** [comment]
Hello @FixRM ,
one sample of using Alternate Keys in unit tests can be found [here](https://github.com/BetimBeja/fake-xrm-easy/blob/f0239fd5aeac576893aa928896d9ed33a9bc2734/FakeXrmEasy.Tests.Shared/FakeContextTests/FakeContextTestDelete.cs#L143-L172). I actually implemented one unit test for RetrieveRequest, UpdateRequest and DeleteRequest.
I will ask someone from my new team to implement the UpsertRequestExecutor and issue a PR, because it is the message which benefits most from alternate keys.

**Comment by FixRM** [comment]
@BetimBeja , thank you for your answer. The problem was is `SetFieldValue` as I forget to add `using FakeXrmEasy.Extensions; `. But after looking in the example more carefully I found that I thought that Alternate Keys work in different manner... I can't find a doc for v9 but hare is one for d365: https://docs.microsoft.com/en-us/previous-versions/dynamicscrm-2016/administering-dynamics-365/dn949335(v=crm.8). Key has is's own name and I think it is used to lookup id using selected columns. Any way it was "test first" I'll check it out soon :)

**Comment by jordimontana82** [comment]
Thanks guys, any questions let me know. @BetimBeja 's example looks fine, what's missing @FixRM  ?

**Comment by FixRM** [comment]
@jordimontana82, @BetimBeja , everything works great, I was wrong about how does alternative keys work. The only thing to consider is `FakeXrmEasy.XrmFakedContext.GetRecordUniqueId(EntityReference record)` is crashing with NullReferenceException if key attribute doesn't contain value or key value can't be found. Is not critical at all but real context behavior is different.

**Comment by jordimontana82** [comment]
Hi @FixRM , @BetimBeja , I think this PR was merged already and it seems to be checking for presence of keys in the GetRecordUniqueId method, so going to close this issue, If any issues, please let me know and I'll reopen :)

https://github.com/jordimontana82/fake-xrm-easy/blob/d70d68e70ca65e408bf1b61f70b7c88f76bd692e/FakeXrmEasy.Shared/XrmFakedContext.Crud.cs#L44-L51

**Comment by wingzeroaa** [comment]
Hi @BetimBeja 

Could you please also make the Associate Request working as well?
Because I am using the Associate Request to link two records, with Alternative Keys.
It is working in Dynamics 365, but not in fake-xrm-easy 

Regards,
Zhenyu
