### ISSUE TITLE
Test not updating Quote Status

### ISSUE THREAD

**Issue by LeeJP1983** [jordimontana82/fake-xrm-easy#348]
Hello,

I'm using Visual Studio 2017 and Dynamics 365 v9.  I've setup FakeXRMEasy.9 but I cannot seem to validate my plugin. It seems like the plugin is not getting called, because when I tried debugging the test it won't step into the plugin.

Here is the basic plugin:
```
public class ActivateQuoteOnSave : Plugin
    {
        public ActivateQuoteOnSave()
            : base(typeof(ActivateQuoteOnSave))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<Plugin.LocalPluginContext>>(40, "Update", "quote", new Action<Plugin.LocalPluginContext>(this.ExecuteActivateQuoteOnSave)));
        }

        protected void ExecuteActivateQuoteOnSave(Plugin.LocalPluginContext localContext)
        {
            //if the activate when saved flag was set then activate the quote now.
            if (localContext.Target.GetValue<bool>("fine_activatewhensaved", false))
            {
                SetStateRequest setStateRequest = new SetStateRequest();
                setStateRequest.State = new OptionSetValue(1);
                setStateRequest.Status = new OptionSetValue(2);
                setStateRequest.EntityMoniker = localContext.Target.ToEntityReference();
                localContext.OrganizationService.Execute(setStateRequest);
            }
        }
    }
```
Essentially, a check box is checked and on save the quote is activated.

Here is my test, which I created by following the Your First Test example.
```
public class ActivateQuoteOnSaveTest
    {
        [TestMethod]
        public void WhenActivateQuoteOnSavePluginIsExecutedQuoteIsActivated()
        {
            var fakeContext = new XrmFakedContext();
            fakeContext.ProxyTypesAssembly = Assembly.GetAssembly(typeof(Quote));

            var quote = new Quote() { Id = Guid.NewGuid() };
            fakeContext.Initialize(new List<Entity>() { quote });

            var service = fakeContext.GetOrganizationService();

            var quoteToUpdate = new Quote() { Id = quote.Id };
            quoteToUpdate.fine_ActivateWhenSaved = true;
            service.Update(quoteToUpdate);

            var updatedQuoteStatus = fakeContext.CreateQuery<Quote>().Where(e => e.Id == quote.Id).Select(a => a.StateCode).FirstOrDefault();

            Assert.AreEqual(QuoteState.Active, updatedQuoteStatus);
        }
    }
```

When it gets to the Assert, it fails:
`Message: Assert.AreEqual failed. Expected:<Active>. Actual:<Draft>. `

I've also tried using ExecutePluginWith<ActivateQuoteOnSave>(inputs, outputs) but same result.

**Comment by BetimBeja** [comment]
Hello @LeeJP1983 
in order to unit test your plugin you have to setup the context where your plugin gets executed for example by calling `ExecutePluginWithTarget<ActivateQuoteOnSave>(quoteToUpdate,"Update")` and not by directly calling service.Update.

I hope you understood the way you should write your unit test, if not please write back so i can rewrite your example test so you can understand how it works.

Best regards,
@BetimBeja

**Comment by jordimontana82** [comment]
Hi @LeeJP1983 

In addition, as you're using a base plugin class and not a plugin that implements IPlugin directly, you'll need to pass the MessageName and Step properties into the plugin context when calling ExecutePluginWith.

Example:

     var plugCtx = fakeContext.GetDefaultPluginContext();
     plugCtx.MessageName = "Update";
     plugCtx.Stage = 40;
     ExecutePluginWith<ActivateQuoteOnSave>(plugCtx)

**Comment by LeeJP1983** [comment]
Thanks @BetimBeja and @jordimontana82,

I did just that but no change:

```
public void WhenActivateQuoteOnSavePluginIsExecutedQuoteIsActivated()
        {
            var fakeContext = new XrmFakedContext();
            fakeContext.ProxyTypesAssembly = Assembly.GetExecutingAssembly();

            var quote = new Quote() { Id = Guid.NewGuid() };

            ParameterCollection inputParameters = new ParameterCollection();
            inputParameters.Add("Target", quote);
            inputParameters.Add("fine_activatewhensaved", true);

            ParameterCollection outputParameters = new ParameterCollection();
            var stateCode = quote.StateCode;
            outputParameters.Add("statecode", stateCode);

            var pluginContext = fakeContext.GetDefaultPluginContext();
            pluginContext.MessageName = "Update";
            pluginContext.Stage = 40;
            pluginContext.InputParameters = inputParameters;
            pluginContext.OutputParameters = outputParameters;
            fakeContext.ExecutePluginWith<ActivateQuoteOnSave>(pluginContext);

            Assert.AreEqual(QuoteState.Active, stateCode);
        }
```
Message: Assert.AreEqual failed. Expected:<Active>. Actual:<(null)>

I feel that there is something fundamental that I am missing.

**Comment by LeeJP1983** [comment]
I made some modification:

```
        public void WhenActivateQuoteOnSavePluginIsExecutedQuoteIsActivated()
        {
            var fakeContext = new XrmFakedContext();
            fakeContext.ProxyTypesAssembly = Assembly.GetExecutingAssembly();

            var quote = new Quote() { Id = Guid.NewGuid(), fine_ActivateWhenSaved = true };

            ParameterCollection inputParameters = new ParameterCollection();
            inputParameters.Add("Target", quote);

            var pluginContext = fakeContext.GetDefaultPluginContext();
            pluginContext.MessageName = "Update";
            pluginContext.Stage = 40;
            pluginContext.InputParameters = inputParameters;
            fakeContext.ExecutePluginWith<ActivateQuoteOnSave>(pluginContext);

            Assert.AreEqual(QuoteState.Active, quote.StateCode);
        }
```
This now allows me to step into my plugin, but when it reaches the Execute command it throws. Output:

Test Name:	WhenActivateQuoteOnSavePluginIsExecutedQuoteIsActivated
Test FullName:	CRM_unittest.ActivateQuoteOnSaveTest.WhenActivateQuoteOnSavePluginIsExecutedQuoteIsActivated
Test Source:	D:\crmdev\CRM_unittest\ActivateQuoteOnSaveTest.cs : line 16
Test Outcome:	Failed
Test Duration:	0:05:24.2919722

> 
> Result StackTrace:	
> at FakeXrmEasy.XrmFakedContext.UpdateEntity(Entity e)
>    at FakeXrmEasy.XrmFakedContext.<>c__DisplayClass45_0.<FakeUpdate>b__1(Entity e)
>    at FakeItEasy.Configuration.BuildableCallRule.Apply(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\BuildableCallRule.cs:line 103
>    at FakeItEasy.Core.FakeManager.FakeItEasy.Core.IFakeCallProcessor.Process(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 144
>    at Castle.DynamicProxy.AbstractInvocation.Proceed() in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\RuleBuilder.cs:line 0
>    at FakeXrmEasy.FakeMessageExecutors.SetStateRequestExecutor.Execute(OrganizationRequest request, XrmFakedContext ctx)
>    at FakeXrmEasy.XrmFakedContext.<>c__DisplayClass139_0.<FakeExecute>b__1(OrganizationRequest req)
>    at FakeItEasy.Configuration.RuleBuilder.ReturnValueConfiguration`1.<>c__DisplayClass16_0.<ReturnsLazily>b__0(IInterceptedFakeObjectCall x) in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\RuleBuilder.cs:line 215
>    at FakeItEasy.Configuration.BuildableCallRule.Apply(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\BuildableCallRule.cs:line 109
>    at FakeItEasy.Core.FakeManager.FakeItEasy.Core.IFakeCallProcessor.Process(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 144
>    at Castle.DynamicProxy.AbstractInvocation.Proceed() in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\RuleBuilder.cs:line 0
>    at Castle.Proxies.ObjectProxy_4.Execute(OrganizationRequest request)
>    at Fine.CRM2011.TecplotProcesses.ActivateQuoteOnSave.ExecuteActivateQuoteOnSave(LocalPluginContext localContext) in D:\crmdev\fine\Fine.CRM2011.TecplotProcesses\ActivateQuoteOnSave.cs:line 30
>    at Fine.CRM2011.TecplotProcesses.Plugin.Execute(IServiceProvider serviceProvider) in D:\crmdev\fine\Fine.CRM2011.TecplotProcesses\Plugin.cs:line 207
>    at FakeXrmEasy.XrmFakedContext.<>c__DisplayClass171_0.<ExecutePluginWith>b__1(IServiceProvider provider)
>    at FakeItEasy.Configuration.BuildableCallRule.Apply(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\BuildableCallRule.cs:line 103
>    at FakeItEasy.Core.FakeManager.FakeItEasy.Core.IFakeCallProcessor.Process(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 144
>    at Castle.DynamicProxy.AbstractInvocation.Proceed() in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\RuleBuilder.cs:line 0
>    at FakeXrmEasy.XrmFakedContext.ExecutePluginWith(XrmFakedPluginExecutionContext ctx, IPlugin instance)
>    at FakeXrmEasy.XrmFakedContext.ExecutePluginWith[T](XrmFakedPluginExecutionContext ctx)
>    at CRM_unittest.ActivateQuoteOnSaveTest.WhenActivateQuoteOnSavePluginIsExecutedQuoteIsActivated() in D:\crmdev\CRM_unittest\ActivateQuoteOnSaveTest.cs:line 30
> Result Message:	
> Test method CRM_unittest.ActivateQuoteOnSaveTest.WhenActivateQuoteOnSavePluginIsExecutedQuoteIsActivated threw exception: 
> System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: quote with Id 7c07e24b-b910-42f2-a187-7d457857195e Does Not Exist
> Result StandardOutput:	
> Entered Fine.CRM2011.TecplotProcesses.ActivateQuoteOnSave.Execute(), Correlation Id: 00000000-0000-0000-0000-000000000000, Initiating User: 31b593da-40c2-481f-a670-45dbc34f2028
> Fine.CRM2011.TecplotProcesses.ActivateQuoteOnSave is firing for Entity: quote, Message: Update, Correlation Id: 00000000-0000-0000-0000-000000000000, Initiating User: 31b593da-40c2-481f-a670-45dbc34f2028
> Exception: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: quote with Id 7c07e24b-b910-42f2-a187-7d457857195e Does Not Exist (Fault Detail is equal to Exception details: 
> ErrorCode: 0x0
> Message: 
> TimeStamp: 0001-01-01T08:00:00.0000000Z
> --
> )., Correlation Id: 00000000-0000-0000-0000-000000000000, Initiating User: 31b593da-40c2-481f-a670-45dbc34f2028
> Exiting Fine.CRM2011.TecplotProcesses.ActivateQuoteOnSave.Execute(), Correlation Id: 00000000-0000-0000-0000-000000000000, Initiating User: 31b593da-40c2-481f-a670-45dbc34f2028

**Comment by LeeJP1983** [comment]
Thanks @BetimBeja,

I was finally able to get it working with that.  It wasn't clear going through the Get Started guide that this needed to be done. The Your First Test and How to Test a Plugin sections are quite different.

**Comment by jordimontana82** [comment]
Thx Betim and Lee.

Basically, any data that is needed by your code needs to be initialised via fakeContext.Initialize(list of entities).

Will close this is issue now.
