### ISSUE TITLE
QualifyLeadRequest should update statuscode to Qualified, instead of Open

### ISSUE THREAD

**Issue by jordimontana82** [jordimontana82/fake-xrm-easy#352]
var qualifyReq = new QualifyLeadRequest { 
       CreateAccount = true, CreateContact = true, 
       CreateOpportunity = true, 
       LeadId = lead.ToEntityReference(), 
       Status = new OptionSetValue((int)LeadStatusCode.Qualified), 
    }; 

    var result = service.Execute(qualifyReq); 

result has response and "created entities " but statecode in lead doesn't changed and is still Open. Normally, Statecode is Qualified

Looks like it might be related to [this](https://github.com/jordimontana82/fake-xrm-easy/blob/master/FakeXrmEasy.Shared/FakeMessageExecutors/QualifyLeadRequestExecutor.cs#L101) (guessing it should assign the option set value, not the integer value directly).

@SejoslawMobile  I think you introduced this message... did you have any similar issues?

**Comment by BetimBeja** [comment]
Hello @jordimontana82,
I have written a [test](https://github.com/BetimBeja/fake-xrm-easy/blob/4c6b10d703c9ade4b289e8f8fe799564815e6478/FakeXrmEasy.Tests.Shared/FakeContextTests/QualifyLeadTests/QualifyLeadTests.cs#L143-L172) for the status of the qualified lead after the message is executed and actually it fails with an invalid cast exception.
Will submit a PR to fix the problem with your proposed solution.

Best regards,
@BetimBeja

**Comment by jordimontana82** [comment]
Again, thanks a mill for your effort on this Betim. Much appreciated
