### ISSUE TITLE
ReturnTotalRecordCount is not respected for QueryByAttribute

### ISSUE THREAD

**Issue by FixRM** [jordimontana82/fake-xrm-easy#361]
https://github.com/jordimontana82/fake-xrm-easy/blob/64acb1357dd63f8cc02b195f9b212af3015438f6/FakeXrmEasy.Shared/XrmFakedContext.cs#L402

Hello,

Thanks for the great testing tool! It looks like PageInfo.ReturnTotalRecordCount setting is not respected for QueryByAttribute and FetchExpression queries. I'll try to fix it myself later but I'm kind of new in this repo so not really sure how long it will take.

**Comment by jordimontana82** [comment]
Thx Artem!

Looks like it could be better resolved in the [RetrieveMultiple fake message executor](https://github.com/jordimontana82/fake-xrm-easy/blob/master/FakeXrmEasy.Shared/FakeMessageExecutors/RetrieveMultipleRequestExecutor.cs#L86-L111) as it is doing other stuff with the page info currently there.

**Comment by FixRM** [comment]
Hello @jordimontana82,

I find out that I have to make changes in both places, as RetrieveMultiple fake message executor doesn't handle ReturnTotalRecordCount calculations for some reason. Actually, the comment in XrmFakedContext.cs says that it was:
> //refactored from RetrieveMultipleExecutor

That do you think? I believe that common logic should be in one place.

**Comment by jordimontana82** [comment]
Yep thx for pointing that out
