### ISSUE TITLE
Fake Organisation Context Projection -> Destroys underlying data source

### ISSUE THREAD

**Issue by VanPuyveldeKevin** [jordimontana82/fake-xrm-easy#362]
Long story short … when selecting data from the fake organisation context, the underlying data being queried is completely destroyed. Only what was selected actually remains. 
That's crippling to the rest of the tested application of course when a second selection is done on that particular data source, for example with a different filter or just to get other attributes.
Since nothing remains, there's nothing to get, thus all subsequent logic fails, so the tests all fail.

**TEST CASE**
Strangely enough … this version actually works fine. You'll immediately see why I indicate this as being 'strange'.
![image](https://user-images.githubusercontent.com/19588107/48977985-443e3e00-f0a5-11e8-8850-3a128402f214.png)

**NOTE** this test. Basically, reality (After all … you won't really be counting the attributes for real eh).
Same debug session, as you can see. However, I commented out the '.First()' line which counted the 'original' number of attributes. Of course, the number is still 11, as VS remembers it here (grey).

**SYMPTOM:** The 'XyzSet', being the datasource, is completely broken here. I selected the id, only the id is now left in the datasource.
In fact, it causes subsequent selections to completely bomb since there's nothing left in them.
![image](https://user-images.githubusercontent.com/19588107/48977991-5b7d2b80-f0a5-11e8-8207-5f1971336820.png)

Also see this version. The one I requested first to do the count is unscathed. The second item, which I didn't touch yet, is broken. Only the id is left basically. This was also an object with 11 attributes.
![image](https://user-images.githubusercontent.com/19588107/48977999-6c2da180-f0a5-11e8-8258-ff199cc0b2e1.png)

As I see it, enumerating the queryable is what destroys the data. While building it, we're still good to go. 
And for some reason, if the queryable was somehow already queried, we're also good.

Also of note … if I drag my execution point back to the 'using new Context(service)' point and thus construct a new context, the datasource has it's 11 attributes back until selection/projection of data occurs and everything breaks again.
But this does indicate it doesn't destroy the initial data (given to the fake plugin context via 'this.FakeContext.Initialize(this.DataToInitialize);'.

Also ... just in case you're wondering. This is not default quote/quote detail. They're 2 custom entities.

**Comment by jordimontana82** [comment]
Hi @VanPuyveldeKevin 

Thx for raising this.

Could you try checking if the faked context still retains the data by querying it like:

    var ctx = new XrmFakedContext()
    ctx.CreateQuery<QuoteDetail>().ToList() 

If the data is still there (which I believe that will be the case as FakeXrmEasy is always cloning instances of every entity before returning them so nothing should be destroyed) then it might be a CRM LINQ caching issue.

I had issues in the past with CRM LINQ where if you run the exact same query with the same where condition within the same using block is going to always return the results from the first query only. So try putting them in different using blocks.

**Comment by VanPuyveldeKevin** [comment]
I actually mention it briefly in my first post that dragging the cursor back to the using 'init' results in the correct data being loaded into the context again.
Basically, that means if I close the using and create a new context in another using, we see the originally instantiated data again and another selection is possible on that data.

That is ... until a selection is done and the data is gone again in that context. 

Seeing as the data in the context itself 'disappears', it doesn't matter which 'where' clause is used for the 'second or subsequent retrieves' though (if I inspect the objects via the debugger, we can clearly see both objects in the test dataset were left with only their id, the selected attribute).
Also ... the 'tests' selecting 'xSet.First()' work w/o a 'where clause' at all, so that pretty much indicates what I just mentioned.

Now ... is it just me or is creating a whole new OrganizationContext for each request not exactly 'optimal'?

**Comment by jordimontana82** [comment]
Just to confirm, the data in your context XrmServiceContext disappears after the first query, however the data in FakeXrmEasy's In-Memory context remains, correct?  

You can check that by executing after the first query:

    ctx.CreateQuery<QuoteDetail>().ToList()

**Comment by VanPuyveldeKevin** [comment]
Yup, the faked context retains it's values. 

If I follow the execution path I can see the QuoteSet inside the 'using' losing it's values.
If I then query the faked context when I return in the unit test scope, then I find the full object.

![image](https://user-images.githubusercontent.com/19588107/49096488-f07d5180-f26a-11e8-8b2f-e53214860979.png)

**Comment by jordimontana82** [comment]
So then I'm afraid that's a existing caching behavior with the CRM SDK and there's very little we can do from a FakeXrmEasy's perspective as I suspected.

Either use 2 different usings (which shouldn't be an issue because the SDK manages the connection pool), or else please raise it with the vendor (MS)

**Comment by eNeRGy164** [comment]
Sadly, that is how XRM works.

Also the reason I avoid the linq functionality.

**Comment by jordimontana82** [comment]
LINQ is ok.... once you know the limitations it has :)

**Comment by jordimontana82** [comment]
Closing this issue now
