### ISSUE TITLE
FakeXrmEasy Mock IOrganization.Retrieve and Retrieve Multiple

### ISSUE THREAD

**Issue by chetanshetty1387** [jordimontana82/fake-xrm-easy#365]
Hi,

I want to mock retrieve and retrieve multiple but I am unable to do that. Below is the Query expression which has been used in plugin and which I am trying to mock

**QueryExpression doaQuery = new QueryExpression()
{
EntityName = gcct_delegationofauthority.EntityLogicalName,
ColumnSet = new ColumnSet("gcct_name", "gcct_region", "gcct_country", "transactioncurrencyid", "gcct_repairgas", "gcct_repairdiesel", "gcct_repairelectric", "gcct_rental", "gcct_refund", "gcct_consequentialexpense", "gcct_vehiclepayment", "gcct_maxfordparticipation", "gcct_daysbeyondroclosedate", "gcct_unlimitedtime", "gcct_maxtimeinmonthsfordgas", "gcct_maxtimeinmonthsforddiesel", "gcct_maxtimeinmonthsfordelectric", "gcct_unlimitedmileage", "gcct_maxmileagefordgas", "gcct_maxmileageforddiesel", "gcct_maxmileagefordelectric", "gcct_maxtimeinmonthslincoln", "gcct_maxmileagelincoln"),
LinkEntities =
{
new LinkEntity
{
LinkToEntityName = gcct_userdelegationofauthority.EntityLogicalName,
LinkFromEntityName = gcct_delegationofauthority.EntityLogicalName,
LinkToAttributeName = "gcct_delegationlevel",
LinkFromAttributeName = "gcct_delegationofauthorityid",
JoinOperator = JoinOperator.Inner,
LinkCriteria = new FilterExpression()
{
FilterOperator = LogicalOperator.And,
Conditions =
{
new ConditionExpression("gcct_user", ConditionOperator.EqualUserId),
new ConditionExpression("gcct_region", ConditionOperator.Equal, this.KnownPartsDelay.gcct_Region.Id),
this.KnownPartsDelay.gcct_Country == null ? new ConditionExpression("gcct_country", ConditionOperator.Null) : new ConditionExpression("gcct_country", ConditionOperator.Equal, this.KnownPartsDelay.gcct_Country.Id)
}
}
}
}
};
EntityCollection doaec = OrganizationService.RetrieveMultiple(doaQuery);**

Here in condition equaluserid operator has been used and every time I am getting count as zero in entity collection even if I am using fakeplugincontext.initiatinguserid or Userid.
If I remove new ConditionExpression("gcct_user", ConditionOperator.EqualUserId) then I am getting count as one in entitycollection.

Jordi could you please help me here on how to mock retrieve and retrieve multiple.

Thanks,
Chetan

**Comment by BetimBeja** [comment]
Hello Chetan,
probably since you are having problems with ConditionOperator.EqualUserId, you might be facing the same problem as the one solved in issue #358, or precisely this [answer](https://github.com/jordimontana82/fake-xrm-easy/issues/358#issuecomment-438732037).
If the problem you are facing is the same then we can consider this a duplicate, otherwise provide some more info and we might be able to help. Also if you can provide your test case as I did in the solution to issue #358 it would be easier to understand what the problem is.

Best regards,
Betim.

**Comment by jordimontana82** [comment]
Looks like that is the issue, thx Betim!

**Comment by chetanshetty1387** [comment]
It worked guys.
Thanks a lot Betim and Jordi for your quick help.
