### ISSUE TITLE
Mock Retrieve in FakeXrmEasy

### ISSUE THREAD

**Issue by chetanshetty1387** [jordimontana82/fake-xrm-easy#366]
Hi,

I am creating a mock user in UT and setting same user as owner of the account entity.

As owner is of type entity reference, I am setting Name property in owner reference as "System" that is because in plugin there is a if condition which checks "account.owner.name='SYSTEM'". To execute if loop I am setting owner name as "SYSTEM"

Below is the plugin code

            **_this.AssignRecordToTeam(this.TargetEntity.ToEntityReference(), this.GetRecordOwner(false));
            Account account = OrganizationService.Retrieve(TargetEntity.LogicalName, TargetEntity.Id, new ColumnSet(new string[] { "gcct_region", "ownerid" })).ToEntity<Account>();
            this.Trace("account");
            if (account.OwnerId != null && account.OwnerId.Name != null && account.OwnerId.Name.ToUpper() == "SYSTEM")_**

The problem here is in AssignRecordToTeam function Name, the owner reference become null that is because they are creating new entity reference of owner and while retrieving account with column as owner, Name is null and **if condition** fail to execute.

Is it possible to mock Retrieve request when retrieve executes in plugin so that I can create my own response.
 
Thanks,
Chetan

**Comment by chetanshetty1387** [comment]
Hi Ben,

Thanks for your response.

I tried the way you suggested in UT. Below is the UT code
**SystemUser systemUser = new SystemUser() { Id = Guid.NewGuid(), gcct_PrimaryTeam = new EntityReference(Team.EntityLogicalName, team.Id), DomainName = "user1", Title = "Mr" };                
                Account account = new Account() { Id = Guid.NewGuid(), LogicalName = "account", gcct_Region = new EntityReference(gcct_region.EntityLogicalName, region.Id), OwnerId = new EntityReference(SystemUser.EntityLogicalName, systemUser.Id) };
                account.OwnerId.Name = "SYSTEM";
                
                fakedContext.Initialize(new List<Entity>() { systemUser, account });**

I have set account ownerid Name as "SYSTEM" _account.OwnerId.Name = "SYSTEM";_

But still I am getting ownerid name as null in plugin
 **this.AssignRecordToTeam(this.TargetEntity.ToEntityReference(), this.GetRecordOwner(false));
            Account account = OrganizationService.Retrieve(TargetEntity.LogicalName, TargetEntity.Id, new ColumnSet(new string[] { "gcct_region", "ownerid" })).ToEntity<Account>();
            this.Trace("account");
            if (account.OwnerId != null && account.OwnerId.Name != null && account.OwnerId.Name.ToUpper() == "SYSTEM")
            {**

Please help me if I am doing anything wrong here.

Thanks in advance
Chetan

**Comment by bwmodular** [comment]
Hi Chetan, 
I understand the problem better now.
In a real Dynamics instance, when your query returns an entity reference, the Name attribute is populated:
![image](https://user-images.githubusercontent.com/1889586/49379159-63bd1280-f706-11e8-8a1b-a2d6c29df16b.png)
but in our faked instance, it is not:
![image](https://user-images.githubusercontent.com/1889586/49379175-6fa8d480-f706-11e8-8b61-020f36dc01a4.png)

I'm afraid I don't know how to resolve that - might be one for @jordimontana82 to answer. Sorry for wasting your time...

**Comment by chetanshetty1387** [comment]
Hi Ben,
  
You are correct I am facing the same issue. Dont be sorry atleast you tried helping me out, thats a great thing.Thanks for that. However, If Jordin helps me out from this issue, i will be thankful to him.

Thanks,
Chetan

**Comment by BetimBeja** [comment]
Hello all,
to populate the Name property of EntityReferences the [EntityMetadata.PrimaryNameAttribute](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.metadata.entitymetadata.primarynameattribute?view=dynamics-general-ce-9#Microsoft_Xrm_Sdk_Metadata_EntityMetadata_PrimaryNameAttribute) must be, used but currently it is not being used...

Best regards,
Betim.

**Comment by jordimontana82** [comment]
Thx to everybody to replied to this issue.

Chetan, you can inject that [Name](https://docs.microsoft.com/en-us/previous-versions/dynamicscrm-2016/developers-guide/gg326835%28v%3dcrm.8%29) property of the Entity Reference (it's a public property) before the entity is added to the .Initialize() method and in that way it will be returned when queried. That's the easiest option.

I thought of populating automatically based on metadata and primary name atttribute, but that would mean you then are forced to also inject the metadata every single time (and for most tests, this is not ideal, it's just easier, or at least less time consuming in my opinion, to do it via the Name property of the Entity Reference.

Hope this helps!

Closing this issue, if still having questions please reopen it.

**Comment by chetanshetty1387** [comment]
Hi Ben/Jordi,

@bwmodular  @jordimontana82 - Thanks for your response.

@jordimontana82  @bwmodular - The problem here is Account record is assigned to new owner at runtime in plugin as you can see in my first comment
`_this.AssignRecordToTeam(this.TargetEntity.ToEntityReference(), this.GetRecordOwner(false));_
 
Account account = OrganizationService.Retrieve(TargetEntity.LogicalName, TargetEntity.Id, new ColumnSet(new string[] { "gcct_region", "ownerid" })).ToEntity<Account>();
        this.Trace("account");
        if (account.OwnerId != null && account.OwnerId.Name != null && account.OwnerId.Name.ToUpper() == "SYSTEM")`

AssignRecordToTeam function  - it will take the data from one of the field in team and assign it to that user

When assigned to new user during that time Name property is null in entity reference and while retrieving account owner I am getting Name property as null.

Let me know if you need more info.

Thanks,
Chetan

**Comment by jordimontana82** [comment]
@chetanshetty1387 Is the Name property of this entity reference null (this.TargetEntity.ToEntityReference()) before passing it to your function (this.AssignRecordToTeam)? Could you also post what that function is doing? Is it an update message?

**Comment by BetimBeja** [comment]
I believe that Entity.ToEntityReference() always leaves the Name property null. 
In order to correctly create the EntityReferences in the context we must use EntityMetadata.PrimaryNameAttribute to fill the Name property (or leave it null if the EntityMetadata is missing).

**Comment by BetimBeja** [comment]
@chetanshetty1387 
Also the [AssignRequestExecutor](https://github.com/jordimontana82/fake-xrm-easy/blob/7d5c2951e7f760ad97c3463f9f22da0e792e7512/FakeXrmEasy.Shared/FakeMessageExecutors/AssignRequestExecutor.cs#L47) directly assigns the passed entity reference to the ownerid attribute, instead of retrieving the referenced systemuser entity and creating an EntityReference with the Name property correctly populated (as I think you are assuming).
Best regards,
Betim.

**Comment by jordimontana82** [comment]
If there is any injected metadata then yeah, we could as part of the Create and Update messages, or else leave it null if there was no metadata.

**Comment by BetimBeja** [comment]
I had some free time today and did some work to replace the `ToEntityReference` and `new EntityReference`  with an extension method on Entity `ToEntityReference(this Entity entity, XrmFakedContext context)` which handles the Name property (and the KeyAttributes property), and after some testing I realized that the task is big.
And we should handle the references when we update the actual entity if we want to behave in the correct way, ex: If we have an account with a primary contact, and we update the contact Name, when we retrieve the account then the Name property on Account["primarycontactid"] should be the new value and not the old value.
I can issue a PR with the changes up until now but I am sure I didn't solve all the edge cases.

**Comment by chetanshetty1387** [comment]
Hi All,

I am pasting the code for the function GetrecordOwner and AssignRecordToTeam
public EntityReference GetRecordOwner(bool isEmployee)
        {
            if (this.PrimaryTeam == null)
            {
                return this.UserEntityReference;
            }

            TracingService.Trace("Set OWner as team" + this.PrimaryTeam.Name);

            TracingService.Trace("Set Owner as team5-");
            if (isEmployee && this.PrimaryTeam.Attributes.Contains("gcct_canownemployeerecord") && this.PrimaryTeam.Attributes.Contains("gcct_employeerecordownerteam"))
            {
                if (this.PrimaryTeam.gcct_CanOwnEmployeeRecord.Value)
                {
                    return this.PrimaryTeam.ToEntityReference();
                }
                else
                {
                    return this.PrimaryTeam.gcct_EmployeeRecordOwnerTeam;
                }
            }
            else
            {
                // Ownership behavior
                if (!this.PrimaryTeam.Attributes.Contains("gcct_recordownershipbehavior") || this.PrimaryTeam.gcct_RecordOwnershipBehavior.Value == (int)RecordOwnershipBehavior.TeamOwned)
                {
                    TracingService.Trace("Owner is Team");
                    return this.PrimaryTeam.ToEntityReference();
                }
            }

            return this.UserEntityReference;
        }
-----------------------------------------------------------------------------------------------------------
  protected void AssignRecordToTeam(EntityReference target, EntityReference ownerTeam)
        {
            var request = new Microsoft.Crm.Sdk.Messages.AssignRequest
            {
                Assignee = ownerTeam,
                Target = target,
            };
            OrganizationService.Execute(request);
        }

Converting to .toEntityReference is giving problem which is setting Name as null.

Let me know guys if you have solution for this.

Thanks,
Chetan

**Comment by jordimontana82** [comment]
@chetanshetty1387  The latest version should return .Name populated if there was entity metadata populated and a PrimaryAttributeName field set when retrieving any entity. The .ToEntityReference() is a separate issue, I think this is by desing of CRM SDK and so you'll need to set the .Name property manually in that case.

Closing this issue.

**Comment by chetanshetty1387** [comment]
Thanks @jordimontana82.
