### ISSUE TITLE
PluginContext.IsolationMode and IsInTransaction are not taken into account

### ISSUE THREAD

**Issue by iggsn** [jordimontana82/fake-xrm-easy#377]
Looks like the current XrmFakedContext is not taking the two Properties into account.
I think the values should be PrePopulated in the "GetDefaultPluginContext()" method and also added to the method "PopulateExecutionContextPropertiesFromFakedContext()".

Am I right? If I have not overseen anything, I could add that.

**Comment by jordimontana82** [comment]
Thanks for this Lars, PR merged now
