### ISSUE TITLE
Send Email from template request is not supported

### ISSUE THREAD

**Issue by chetanshetty1387** [jordimontana82/fake-xrm-easy#379]
Hi Jordi,

I am getting below error in plugin when SendEmailFromTemplate request is executed.
**_Microsoft.Xrm.Sdk.InvalidPluginExecutionException: 'Exception: The organization request type 'Microsoft.Crm.Sdk.Messages.SendEmailFromTemplateRequest' is not yet supported... but we DO love pull requests so please feel free to submit one! :). This functionality is not available yet. Please consider contributing to the following Git project https://github.com/jordimontana82/fake-xrm-easy by cloning the repository and issuing a pull request.'_** 

Is above request is not supported in FakeXrmEasy?

Thanks,
Chetan

**Comment by BetimBeja** [comment]
Hello @chetanshetty1387 ,
for the currently implemented request types you can check [FakeMessageExecutors](https://github.com/jordimontana82/fake-xrm-easy/tree/master/FakeXrmEasy.Shared/FakeMessageExecutors) as specified on the Readme file. Currently **SendEmailFromTemplate** is not implemented.

Also the exception you are receiving is the clever message that @jordimontana82 created to invite users to contribute to the project.

Best regards,
Betim.

**Comment by chetanshetty1387** [comment]
Thanks @BetimBeja
