### ISSUE TITLE
Query translation raises NullReferenceException if a query orders by a field which wasn't initialized

### ISSUE THREAD

**Issue by jordimontana82** [jordimontana82/fake-xrm-easy#38]

**Comment by jordimontana82** [comment]
It can be reproduced by executing a LINQ query with an orderby like c.FirstName when there FirstName wasn't initialised in the context.

**Comment by daryllabar** [comment]
I'm getting a similar error that I assume is related when attempting to execute this:
``` csharp

var service = new XrmFakedContext { ProxyTypesAssembly = Assembly.GetAssembly(typeof(CrmContext)) }.GetFakedOrganizationService();
var id = service.Create(new Contact { LastName = "Mcdonald" });

using (var context = new CrmContext(service))
{
    var contacts = (from c in context.ContactSet
                            where c.FirstName == name || c.LastName == name
                            select new Contact {Id = c.Id, FirstName = c.FirstName, LastName = c.LastName}).ToList();
}
```

Message is: The attribute firstname does not exist on this entity.

>    at FakeXrmEasy.OrganizationFaults.OrganizationServiceFaultQueryBuilderNoAttributeException.Throw(String sMissingAttributeName)
>    at FakeXrmEasy.Extensions.EntityExtensions.ProjectAttributes(Entity e, QueryExpression qe, XrmFakedContext context)
>    at lambda_method(Closure , Entity )
>    at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>    at FakeXrmEasy.FakeMessageExecutors.RetrieveMultipleRequestExecutor.Execute(OrganizationRequest req, XrmFakedContext ctx)
>    at FakeXrmEasy.XrmFakedContext.<>c__DisplayClass53_0.<FakeExecute>b__0(OrganizationRequest req)
>    at FakeItEasy.ReturnValueConfigurationExtensions.<>c__DisplayClassd`2.<ReturnsLazily>b__c(IFakeObjectCall call)
>    at FakeItEasy.Configuration.RuleBuilder.ReturnValueConfiguration`1.<>c__DisplayClass8.<ReturnsLazily>b__7(IInterceptedFakeObjectCall x)
>    at FakeItEasy.Configuration.BuildableCallRule.Apply(IInterceptedFakeObjectCall fakeObjectCall)
>    at FakeItEasy.Core.FakeManager.ApplyRule(CallRuleMetadata rule, IInterceptedFakeObjectCall fakeObjectCall)
>    at FakeItEasy.Core.FakeManager.FakeItEasy.Core.IFakeCallProcessor.Process(IWritableFakeObjectCall fakeObjectCall)
>    at FakeItEasy.Creation.CastleDynamicProxy.CastleDynamicProxyGenerator.ProxyInterceptor.Intercept(IInvocation invocation)
>    at Castle.DynamicProxy.AbstractInvocation.Proceed()
>    at Castle.Proxies.ObjectProxy.Execute(OrganizationRequest request)
>    at Microsoft.Xrm.Sdk.Client.OrganizationServiceContext.Execute(OrganizationRequest request)
>    at Microsoft.Xrm.Sdk.Linq.QueryProvider.RetrieveEntityCollection(OrganizationRequest request, NavigationSource source)
>    at Microsoft.Xrm.Sdk.Linq.QueryProvider.Execute(QueryExpression qe, Boolean throwIfSequenceIsEmpty, Boolean throwIfSequenceNotSingle, Projection projection, NavigationSource source, List`1 linkLookups, String& pagingCookie, Boolean& moreRecords)
>    at Microsoft.Xrm.Sdk.Linq.QueryProvider.Execute[TElement](QueryExpression qe, Boolean throwIfSequenceIsEmpty, Boolean throwIfSequenceNotSingle, Projection projection, NavigationSource source, List`1 linkLookups)
>    at Microsoft.Xrm.Sdk.Linq.QueryProvider.Execute[TElement](Expression expression)
>    at Microsoft.Xrm.Sdk.Linq.QueryProvider.GetEnumerator[TElement](Expression expression)
>    at Microsoft.Xrm.Sdk.Linq.Query`1.GetEnumerator()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>    at Example.MsTest.UnitTest1.MakeNameMatchCase(IOrganizationService service, String name) in C:\Users\dlabar\Documents\GitHub\XrmUnitTest\Example.MsTest\UnitTest1.cs:line 134
>    at Example.MsTest.UnitTest1.MakeNameMatchCase_NameIsMcdonald_Should_UpdateToMcDonald_Fake() in C:\Users\dlabar\Documents\GitHub\XrmUnitTest\Example.MsTest\UnitTest1.cs:line 94

**Comment by jordimontana82** [comment]
Right, I´ll have a look...
