### ISSUE TITLE
FetchXml execution should take returntotalrecordcount into account

### ISSUE THREAD

**Issue by jordimontana82** [jordimontana82/fake-xrm-easy#380]
Some final tweak that was probably missed in #361

**Comment by BetimBeja** [comment]
Hello @jordimontana82 ,
I pointed out that this was needed but Artem [said](https://github.com/jordimontana82/fake-xrm-easy/pull/368#issuecomment-443747085) he would do it in another PR.
Probably he is busy with other work, as most of us.

Best regards,
Betim.

**Comment by jordimontana82** [comment]
No worries, I'll push some changes soon...  thx for pointing out! : )

**Comment by FixRM** [comment]
Hello, @jordimontana82 and @BetimBeja,

I think it's already done but we should have some tests for sure
