### ISSUE TITLE
FakeContext not initialize properly issue

### ISSUE THREAD

**Issue by amwayDarshana** [jordimontana82/fake-xrm-easy#382]
I have successfully called to my custom code activity in dynamics CRM with three entity parameters.
But my question is inside  the plugin code there are other entities have been using that is not passing as parameters. And when _orgService.Retrive those entities it gives object reference null exception. 

Could you please help me to solve this problem.

CustomWF code.
  [Input("Service Contract")]
        [RequiredArgument]
        [ReferenceTarget("dsr_servicecontract")]
        public InArgument<EntityReference> ServiceContract { get; set; }

        [Input("Durable")]
        [RequiredArgument]
        [ReferenceTarget("dsr_durable")]
        public InArgument<EntityReference> Durable { get; set; }

        [Input("Business Unit")]
        [RequiredArgument]
        [ReferenceTarget("businessunit")]
        public InArgument<EntityReference> BusinessUnit { get; set; }

        private IOrganizationService _orgService;
        private ITracingService _tracingService;

        protected override void Execute(CodeActivityContext activityContext)
        {
            //Extract the tracing service for use in debugging sandboxed plug-ins.
            _tracingService = activityContext.GetExtension<ITracingService>();

            IWorkflowContext context = activityContext.GetExtension<IWorkflowContext>();
            IOrganizationServiceFactory serviceFactory = activityContext.GetExtension<IOrganizationServiceFactory>();

            // Use the context service to create an instance of IOrganizationService.
            _orgService = serviceFactory.CreateOrganizationService(context.InitiatingUserId);
            _tracingService.Trace("Starting");
            try
            {
                var serviceContract = ServiceContract.Get(activityContext);
                var sc = _orgService.Retrieve("dsr_servicecontract",serviceContract.Id, new ColumnSet(true));
                
                _tracingService.Trace($"ServiceContract {serviceContract.Id}");
                var durableRef = Durable.Get(activityContext);
                var durable = _orgService.Retrieve("dsr_durable", durableRef.Id, new ColumnSet(true));
                
                _tracingService.Trace($"Durable {durable.Id}" );
                var buRef = BusinessUnit.Get(activityContext);
                var businessUnit = _orgService.Retrieve("businessunit", buRef.Id, new ColumnSet(true));
                _tracingService.Trace($"BusinessUnit: { businessUnit.Id}");
                var sku = _orgService.Retrieve("dsr_sku", durable.GetAttributeValue<EntityReference>("dsr_skuid").Id,
                    new ColumnSet(true));
                _tracingService.Trace("SKU {0}", sku.Id);

                var marketRule = GetMarketRule(sku, businessUnit);
                _tracingService.Trace("MarketRule {0}", marketRule.Id);
                sc.Attributes["dsr_scduration"] = marketRule["dsr_servicecontractlength"];
                _orgService.Update(sc);
                //_tracingService.Trace("End Date Set on Service Contract");
            }
            catch (Exception ex)
            {
                _tracingService.Trace("EXCEPTION " + ex.ToString());
                throw;
            }
        }
and this is my test method.
   [TestMethod]
        public void Should_Update_Service_Contract_enddate_action() {

            var fakedContext = new XrmFakedContext();
            var wfContext = fakedContext.GetDefaultWorkflowContext();
            // var inputs = new Dictionary<string, object>();
            wfContext.MessageName = "Update";

            var _durable = new Entity("dsr_durable");
            _durable.Id = new Guid("058E52B5-754C-E711-9400-00155D71EABC");
            _durable.LogicalName = dsr_durable.EntityLogicalName;
            _durable["dsr_name"] = "Atmosphere Sky ATS";
            _durable["dsr_SerialNumber"] = "1111112000000";
            _durable["dsr_durableId"] = Guid.NewGuid();
            _durable["statecode"] = dsr_durableState.Active;
            _durable["dsr_durableId"] = Guid.NewGuid();
            _durable["dsr_SKUID"] = new EntityReference(dsr_sku.EntityLogicalName, new Guid("E1DB14A3-2776-E811-812F-E0071B6AE252"));

            var _serviceContract = new Entity("dsr_servicecontract");
            _serviceContract.Id = Guid.NewGuid(); ;
            _serviceContract.LogicalName = dsr_servicecontract.EntityLogicalName;
            _serviceContract["dsr_SerialNumber"] = "1111112000000";
            _serviceContract["dsr_StartDate"] = DateTime.Now;
            _serviceContract["dsr_SCDuration"] = 90;

            var _BUnit = new Entity("BusinessUnit");
            _BUnit.Id = new Guid("80061f80-7a8b-e711-8111-5065f38b9151");
            _BUnit.LogicalName = BusinessUnit.EntityLogicalName;
            _BUnit["Name"] = "Korea";
            _BUnit["dsr_countrycode"] = "JP";
            _BUnit["dsr_connectidenabled"] = true;

            var _sku = new Entity("dsr_sku");
            _sku.Id = new Guid("3C6AAA73-C33C-E711-810C-5065F38B9151");
            _sku.LogicalName = dsr_sku.EntityLogicalName;
            _sku["dsr_name"] = "ATS Sky Replacement HEPA Filter - ANA";
            _sku["dsr_SKUValue"] = "120540";
            _sku["statecode"] = dsr_skuState.Active;
            _sku["statuscode"] = new OptionSetValue(1);

            var _market_rule = new dsr_marketrule();
            _market_rule.Id = new Guid("892B4320-CA18-E811-8122-5065F38B5101");
            _market_rule.LogicalName = dsr_marketrule.EntityLogicalName;
            _market_rule["dsr_name"] = "ANA Standard SKY Warranty Rule";
            _market_rule["dsr_SKUid"] = new EntityReference(dsr_sku.EntityLogicalName, new Guid("3C6AAA73-C33C-E711-810C-5065F38B9151"));
            _market_rule["dsr_businessunitid"] = new EntityReference(BusinessUnit.EntityLogicalName, new Guid("80061f80-7a8b-e711-8111-5065f38b9151"));
            _market_rule["statuscode"] = new OptionSetValue(1);
            _market_rule["dsr_servicecontractlength"] = 730;

            fakedContext.Initialize(new List<Entity>()
            {
                _durable,_serviceContract,_BUnit,_sku,_market_rule
            });

            var inputs = new Dictionary<string, object>()
            {
                { "ServiceContract" , _serviceContract.ToEntityReference()},
                { "Durable" , _durable.ToEntityReference()},
                { "BusinessUnit" , _BUnit.ToEntityReference()},               

            };
            
            var result = fakedContext.ExecuteCodeActivity<ServiceContractEndDateAction>(inputs);

            Assert.AreEqual(result["dsr_scduration"], _market_rule["dsr_servicecontractlength"]);

        }
 

In here dsr_durable, dsr_serviceContract and BusinessUnit can be accessed from testing debug. but dsr_sku cannot. it gives null reference exception. 

![image](https://user-images.githubusercontent.com/42367701/51667816-c42c4a00-1ffb-11e9-8cd5-452034efa0e9.png)

**Comment by amwayDarshana** [comment]
Hello Betim,

dsr_durable entity has a foreign key field called dsr_SKUID. That s why its was initialize in dsr_durable entity.
But dsr_sku has separately added to the fakedContext. 
here is the code . 

   `   var _sku = new Entity("dsr_sku");
            _sku.Id = new Guid("3C6AAA73-C33C-E711-810C-5065F38B9151");
            _sku.LogicalName = dsr_sku.EntityLogicalName;
            _sku["dsr_name"] = "ATS Sky Replacement HEPA Filter - ANA";
            _sku["dsr_SKUValue"] = "120540";
            _sku["statecode"] = dsr_skuState.Active;
            _sku["statuscode"] = new OptionSetValue(1);


            var _market_rule = new dsr_marketrule();
            _market_rule.Id = new Guid("892B4320-CA18-E811-8122-5065F38B5101");
            _market_rule.LogicalName = dsr_marketrule.EntityLogicalName;
            _market_rule["dsr_name"] = "ANA Standard SKY Warranty Rule";
            _market_rule["dsr_SKUid"] = new EntityReference(dsr_sku.EntityLogicalName, new Guid("3C6AAA73-C33C-E711-810C-5065F38B9151"));
            _market_rule["dsr_businessunitid"] = new EntityReference(BusinessUnit.EntityLogicalName, new Guid("80061f80-7a8b-e711-8111-5065f38b9151"));
            _market_rule["statuscode"] = new OptionSetValue(1);
            _market_rule["dsr_servicecontractlength"] = 730;


            fakedContext.Initialize(new List<Entity>()
            {
                _durable,_serviceContract,_BUnit,_sku,_market_rule
            });`

**Comment by BetimBeja** [comment]
Hello @amwayDarshana ,
in the CRM is your field for `dsr_durable` entity called `dsr_skuid` or `dsr_SKUID`?
Because as I mentioned the entity fields are case sensitive and  `dsr_skuid` is different than `dsr_SKUID`, so either change you initialization code or change your plugin code to match the character casing (use the same casing as in your CRM entity metadata, otherwise your test will pass but you plugin will fail in the CRM).
Best regards,
Betim.

**Comment by amwayDarshana** [comment]
Yes I checked that , but it s not helping actually. The problem is inside actual plugin code he cannot find dsr_sku entity inside the fakeContext.

  var sku = _orgService.Retrieve("dsr_sku", durable.GetAttributeValue<EntityReference>("dsr_skuid").Id,
                    new ColumnSet(true));

_orgService is unable to find dsr_sku form fakeContext then leads to {"Object reference not set to an instance of an object."}

![image](https://user-images.githubusercontent.com/42367701/51674137-d3ff5a80-200a-11e9-9b38-b417e5240397.png)


Regards
Hash

Mocking is not happening properly on dsr_sky entity.

**Comment by BetimBeja** [comment]
Hello,
`durable.GetAttributeValue("dsr_skuid")` is returning null because you are initializing your `dsr_durable` entity with: 
```
_durable["dsr_SKUID"] = new EntityReference(dsr_sku.EntityLogicalName, new Guid("E1DB14A3-2776-E811-812F-E0071B6AE252"));```
change it to:
```
_durable["dsr_skuid"] = new EntityReference(dsr_sku.EntityLogicalName, new Guid("E1DB14A3-2776-E811-812F-E0071B6AE252"));```
and your error will not happen in this line... 
Regards,
Betim.

**Comment by BetimBeja** [comment]
@amwayDarshana can you please close the issue?

**Comment by amwayDarshana** [comment]
@BetimBeja thank you so much for your help as well as @jordimontana82 . 
My issue was case sensitivity mismatch and I fixed it .
