### ISSUE TITLE
Aggregated FetchXml Query returns an incorrect result in case a lookup or customer field is used in the fetchxml as "groupby" attribute

### ISSUE THREAD

**Issue by khorozhansky** [jordimontana82/fake-xrm-easy#383]
Aggregated FetchXml Query returns an incorrect result in case a lookup or customer field is used in the fetchxml as "groupby" attribute. For instance, the query below 

`<fetch no-lock='true' aggregate='true'>
  <entity name='account'>
    <attribute name='parentaccountid' alias='pa' groupby='true' />
    <attribute name='accountid' alias='Qt' aggregate='count' />
    <order alias='Qt' descending='true' />
  </entity>
</fetch>`

always returns one entity record and simply does not take "group by" attribute into consideration.

**Comment by BetimBeja** [comment]
Hello Pavel,
I have found the bug that causes this and will submit a PR later on...
I hope @jordimontana82 won't mind for all the load I am putting on him with the reviews 😃 
Best regards,
Betim.

**Comment by khorozhansky** [comment]
Thank you Betim!

**Comment by jordimontana82** [comment]
Sorry guys for not getting back to you, and @BetimBeja please reviewing them, it helps a lot so it's greatly appreciated :)
