### ISSUE TITLE
Entity.get is not working.

### ISSUE THREAD

**Issue by amwayDarshana** [jordimontana82/fake-xrm-easy#386]
I am passing Dynamics CRM BusinessUnit to my custom code activity. 
And I encountered and error on BusinessUnit.Get(activityContext); 
This is taking id but it does not take name ,

Hope you get my question , please refer the screenshot below.

![image](https://user-images.githubusercontent.com/42367701/51835756-5fddf300-2339-11e9-9faa-d070ef3111c8.png)

Appreciate your help.

This is my test method.

 [TestMethod]
        public void Should_Test_ProductSkuChangeServiceContractRemoveExtensionAction()
        {
            var fakedContext = new XrmFakedContext();
            var wfContext = fakedContext.GetDefaultWorkflowContext();
            wfContext.MessageName = "Update";

            var _durable = new Entity("dsr_durable");
            _durable.Id = new Guid("058E52B5-754C-E711-9400-00155D71EABC");
            _durable.LogicalName = dsr_durable.EntityLogicalName;
            _durable["dsr_name"] = "Atmosphere Sky ATS";
            _durable["dsr_SerialNumber"] = "1111112000000";
            _durable["dsr_durableId"] = Guid.NewGuid();
            _durable["statecode"] = dsr_durableState.Active;
            _durable["dsr_skuid"] = new EntityReference(dsr_sku.EntityLogicalName, new Guid("3C6AAA73-C33C-E711-810C-5065F38B9151"));
            _durable["dsr_relatedbusinessunit"] = new EntityReference(BusinessUnit.EntityLogicalName, new Guid("80061f80-7a8b-e711-8111-5065f38b9151"));

            var _BUnit = new Entity("businessunit");
            _BUnit.Id = new Guid("80061f80-7a8b-e711-8111-5065f38b9151");
            _BUnit.LogicalName = BusinessUnit.EntityLogicalName;
            _BUnit["Name"] = "Japan";
            _BUnit["dsr_countrycode"] = "JP";
            _BUnit["dsr_connectidenabled"] = true;
            _BUnit["parentbusinessunitid"] = new EntityReference(BusinessUnit.EntityLogicalName, new Guid("1D39BB4C-268C-E711-8111-5065F38B9151"));

            var _serviceContract = new Entity("dsr_servicecontract");
            _serviceContract.Id = Guid.NewGuid(); ;
            _serviceContract.LogicalName = dsr_servicecontract.EntityLogicalName;
            _serviceContract["dsr_SerialNumber"] = "1111112000000";
            _serviceContract["dsr_StartDate"] = DateTime.Now;
            _serviceContract["dsr_SCDuration"] = 90;

            fakedContext.Initialize(new List<Entity>()
            {
                _durable,_BUnit,_serviceContract
            });

            var inputs = new Dictionary<string, object>()
            {
                { "Durable" , _durable.ToEntityReference()},
                { "BusinessUnit" , _BUnit.ToEntityReference()},
            };

            var result = fakedContext.ExecuteCodeActivity<ProductSkuChangeServiceContractRemoveExtensionAction>(inputs);

            var tasks = (from t in fakedContext.CreateQuery<dsr_durable>()
                         select t).ToList();

            Assert.IsTrue(tasks.Count == 1);

            Assert.IsNotNull(result);

        }

**Comment by BetimBeja** [comment]
Hello @amwayDarshana ,
your problem stands in the following piece of code
```
var inputs = new Dictionary<string, object>()
        {
            { "Durable" , _durable.ToEntityReference()},
            { "BusinessUnit" , _BUnit.ToEntityReference()},
        };
```
Calling `.ToEntityReference()` creates an EntityReference with the same LogicalName and Id as the Entity, and makes you lose the Name in your parameter...
Best regards,
Betim.

**Comment by amwayDarshana** [comment]
without  "BusinessUnit" , _BUnit.ToEntityReference() 
it gives an exception.
The values provided for the root activity's arguments did not satisfy the root activity's requirements:

Do you have any solutions for that?

**Comment by BetimBeja** [comment]
Hello Darshana,
as I mentioned when you do `_durable.ToEntityReference()` you lose the name Property, which has been discussed in issue #366 . What you can do is the following:
```
EntityReference durableReference = _durable.ToEntityReference();
durableReference.Name =   (string)_durable["dsr_name"];
EntityReference bUnitReference = _BUnit.ToEntityReference();
bUnitReference.Name =  (string)_BUnit["Name"];

 var inputs = new Dictionary<string, object>()
        {
            { "Durable", durableReference },
            { "BusinessUnit", bUnitReference },
        };
```

Probably it is better to ask @jordimontana82 for a little change on how context entity references are created so they have the name property properly set like in PR #369 which might solve this issue in most cases.

Best regards,
Betim.

**Comment by amwayDarshana** [comment]
I will check this and let you know

**Comment by amwayDarshana** [comment]
Yes this works , Thank you so much for the help.

**Comment by BetimBeja** [comment]
> Yes this works , Thank you so much for the help.

Please close the issue. 
Also I always suggest [StackOverflow](https://stackoverflow.com/tags/fakexrmeasy) for how-to questions. Let's use GitHub as a bug report/feature request portal, and more important please submit a PR if you can improve something yourself.

**Comment by jordimontana82** [comment]
Thanks @BetimBeja @amwayDarshana  I'm closing this now as the issue was resolved.
