### ISSUE TITLE
Workflow Query Problem

### ISSUE THREAD

**Issue by davidosso** [jordimontana82/fake-xrm-easy#389]
In production the query at getStageId_CRM does give us the correct results, but in this unit test is not giving the correct result ( it should not find anything ). With the debugger we are seing an incorrect result execution for the query under FakeXrmEasy. Below is the unit test which does replicate the issue we are having, could you please help us with the issue ? Thanks in advance!
`

        using FakeXrmEasy;
        using Microsoft.Xrm.Sdk;
        using PlugIn.Opportunity;
        using Supervielle.GlobalComponents; 
        using System;
        using System.Collections.Generic; 
        using System.Diagnostics; 
        using Xunit; 
        using Microsoft.Xrm.Sdk.Query;
        using System.Linq;
        namespace PluginTest
        {  
        public class tst_Helper_SetBpf
        {
        private XrmFakedContext context;
        private XrmFakedPluginExecutionContext executionContext;
        private IOrganizationService service;
        private ITracingService tracing;

        private static Entity BPF1 = new Entity("workflow", new Guid("11111111-1111-1111-1111-111111111111"))
        {
            ["name"] = "BPF1",
        };

        private static Entity BPF2 = new Entity("workflow", new Guid("11111111-2222-2222-2222-222222222222"))
        {
            ["name"] = "BPF2",
        };

        private static Entity BPF3 = new Entity("workflow", new Guid("11111111-3333-3333-3333-333333333333"))
        {
            ["name"] = "BPF3",
        };

        public tst_Helper_SetBpf()
        {
            context = new XrmFakedContext();
            executionContext = context.GetDefaultPluginContext();
            service = context.GetOrganizationService();
            tracing = context.GetFakeTracingService();

            context.Initialize(new List<Entity> {
                                                    // BPF
                                                    BPF1,BPF2,BPF3
                                                });
        }

        [Fact] //(Skip = "Fake Xrm Easy query execution wrong here")]
        public void getStageCrm_NoEncuentraProcessStage()
        {
            #region Context

            Entity processStageBPF1 = new Entity("processstage", Guid.NewGuid())
            {

                ["stagename"] = "STAGE1",
                ["processid"] = BPF1.ToEntityReference()
            };

            service.Create(processStageBPF1);

            Entity processStageBPF2 = new Entity("processstage", Guid.NewGuid())
            {

                ["stagename"] = "STAGE2",
                ["processid"] = BPF2.ToEntityReference()
            };

            service.Create(processStageBPF2);

            Entity processStageBPF3 = new Entity("processstage", Guid.NewGuid())
            {

                ["stagename"] = "STAGE3",
                ["processid"] = BPF3.ToEntityReference()
            };

            service.Create(processStageBPF3);

            Guid guidFound = Guid.Empty;

            #endregion

            #region Execution

            Exception exception = Record.Exception(() => (guidFound = getStageId_CRM(BPF3.ToEntityReference(), processStageBPF1.Id, service, tracing)));

            #endregion

            #region Assert

            Assert.NotNull(exception);
            Assert.IsType<InvalidPluginExecutionException>(exception);
            Assert.Equal("Stage not found", exception.Message);

            #endregion
        }

        private static Guid getStageId_CRM(EntityReference TargetBPF, Guid OriginStage, IOrganizationService service,
            ITracingService tracing)
        {

            QueryExpression q = new QueryExpression("processstage");
            {
                

            };
            q.ColumnSet = new ColumnSet(true);

            q.Criteria.AddCondition("processid", ConditionOperator.Equal, TargetBPF.Id);

            LinkEntity linked = new LinkEntity
            {
                LinkFromEntityName = "processstage",
                LinkFromAttributeName = "stagename",

                LinkToEntityName = "processstage",
                LinkToAttributeName = "stagename",

                JoinOperator = Microsoft.Xrm.Sdk.Query.JoinOperator.Inner,
                EntityAlias = "TARGET",

                Columns = new ColumnSet(true)
            };

            linked.LinkCriteria.AddCondition("processstageid", ConditionOperator.Equal, OriginStage);

            q.LinkEntities.Add(linked);

            EntityCollection respone = service.RetrieveMultiple(q);

            if (respone.Entities.Count == 0)
            {
                throw new InvalidPluginExecutionException("stage not found");
            }

            return respone.Entities.First<Entity>().Id;
        }
    }}

`

**Comment by BetimBeja** [comment]
Hello @davidosso,
after doing some tests with your problem I found out that actually, because of a bug, you can do grouping only on EntityReference or Guid fields. And if you try other types then you get a Cross Join result because both fields would return Guid.Empty as Key.
I will submit a PR to fix this soon.
Best regards,
Betim.

**Comment by jordimontana82** [comment]
This is interesting, I've personally always joined queries using primary key / foreign keys (that's why KeySelector always returned a Guid) but wasn't aware you could also join on other attribute types. Nice!

I'll take a look at @BetimBeja  's PR

Thanks both

**Comment by davidosso** [comment]
Another question related to this if I should apply this in version 1.49.0 how would you recommend me to do  the patch? Thanks in advance!
