### ISSUE TITLE
Null valued attribute is returned in Attributes collection in a different way that CRM returns

### ISSUE THREAD

**Issue by teppolainio** [jordimontana82/fake-xrm-easy#39]
Consider following initialization:
`var contact = new Contact {`
`  FirstName = null,`
`  LastName = "asdf"`
`}`
`var fakedContext = new XrmFakedContext();`
`fakedContext.Initialize( new List<Entity>{ contact });`

Now when I try to retrieve that contact using something like:
`QueryByAttribute query = new QueryByAttribute("contact");`
`query.ColumnSet = new ColumnSet("firstname", "lastname");`
`var results = service_.RetrieveMultiple(query);`

I get one contact record which attributes collection contains:
- "firstname": null
- "lastname": "asdf"

When I execute following code agains real Dynamics CRM web service endpoint I get one contact record which attributes collection contains:
- "lastname": "asdf"

So problem here is that fake-xrm-easy implementation puts incorrectly field names into Entity.Attributes collection also for fields which values are null.

**Comment by jordimontana82** [comment]
Thanks for raising this .

Does the same happen with a QueryExpression?

**Comment by teppolainio** [comment]
Yes, same behaviour seems to happen with QueryExpression.
