### ISSUE TITLE
Possible problem with nested filters

### ISSUE THREAD

**Issue by nealrobben** [jordimontana82/fake-xrm-easy#391]
Hello,

I am trying to write tests for some of my code and I think I may have run into a problem while using nested filters.

A simplified version of my actual code has been created to demonstrate the problem: https://github.com/nealrobben/FakeXrmEasy_PossibleBugInNestedFilters

In my program, there are 2 Entities: Person and Employment. An employment is linked to a person and has a startdate/enddate.

On this start/enddate I'm trying to do a query in the form of ((ConditionA && ConditionB) || (ConditionC && ConditionD))

When I start nesting filters, I get an error when running my test saying:
XrmFakedContext.FindReflectedAttributeType: Attribute startdate not found for type Console.Person

The part of my query where I am filtering is the following:

`                        LinkCriteria =
                        {
                            Filters =
                            {
                                //The following code works with a nested filter to set up a query with a condition in the form of: ((A && B) || (C && D))
                                //As soon as you comment out the nested conditions everything works fine
                                //If you run the code with them enabled you get an error: XrmFakedContext.FindReflectedAttributeType: Attribute startdate not found for type Console.Person
                                //It looks like because of the nesting, somehow the framework looks for the attribute on the wrong type? (On person, while the actual attribute is on Employment)
                                new FilterExpression(LogicalOperator.Or)
                                {
                                    Filters =
                                    {
                                        new FilterExpression(LogicalOperator.And)
                                        {
                                            Conditions =
                                            {
                                                new ConditionExpression(Employment.AttributeLogicalNames.StartDate,ConditionOperator.NotNull),
                                                new ConditionExpression(Employment.AttributeLogicalNames.EndDate,ConditionOperator.Null)
                                            }
                                        },
                                        new FilterExpression(LogicalOperator.And)
                                        {
                                            Conditions =
                                            {
                                                new ConditionExpression(Employment.AttributeLogicalNames.StartDate,ConditionOperator.Null),
                                                new ConditionExpression(Employment.AttributeLogicalNames.EndDate,ConditionOperator.NotNull)
                                            }
                                        }
                                    }
                                }
                            }`

The file with the demo code can be found [here] .(https://github.com/nealrobben/FakeXrmEasy_PossibleBugInNestedFilters/blob/master/PossibleBugInNestedFilters/Console.Tests/DemoTests.cs) (It is the test at the bottom)

I have been googling this issue while creating the demo project and it seems there are other ways to write queries with nested filters.

So I am not sure if the problem is with the way FakeXrmEasy runs the query, or maybe my query itself is wrong.

Your input on this would be very much appreciated.

   Kind regards,
      Neal

**Comment by BetimBeja** [comment]
Hello @nealrobben ,
I have identified one possible cause of this problem, but haven't tested if it creates other side effects... you can check yourself the proposed solution in the comments in the following commit d3a7b85e5dfb56ce9449782808bec9899d9d2609.
I will issue a PR soon for this issue.
Best regards,
Betim.

**Comment by jordimontana82** [comment]
Hi @nealrobben .

Thx for raising this.... did you try running that query against a CRM environment and which CRM version? Do you get the desired results there with that query?

**Comment by BetimBeja** [comment]
I executed a similar query against the latest CRM online and it is working correctly. 😄

**Comment by nealrobben** [comment]
Hello @jordimontana82 

Because of this exception in my unit test I started to doubt the correctness of my query (Like I said I was not sure whether my query or FakeXrmEasy caused the problem).

So I tested my query extensively against a 2016 on-premise version of CRM and the correct results seem to be returned in all cases.

**Comment by BetimBeja** [comment]
Hello @nealrobben ,
finally I found the way to fix this without causing a regression (actually I fixed d3a7b85e5dfb56ce9449782808bec9899d9d2609 in the correct way). All what is left now is for Jordi to review the PR.

Best regards,
Betim.
