### ISSUE TITLE
System.Exception: Couldnt find reflected type for entityName

### ISSUE THREAD

**Issue by aslanovsergey** [jordimontana82/fake-xrm-easy#394]
Hello,

Please suggest me how I can solve next issue: I have early bound classes in two assemblies one in application code when I use these classes to simplify my development and the second is testing project with FakeXrm where I also have some additional early bound classes to simulate related entities in tests. 

When I run my tests I get `System.Exception: Couldnt find reflected type for entityName`

Here is what i tried to assign to ProxyTypesAssembly  property
```
fakedContext = new XrmFakedContext();
fakedContext.ProxyTypesAssembly = Assembly.GetExecutingAssembly();
```
and
`fakedContext.ProxyTypesAssembly = Assembly.GetCallingAssembly();`

when I use `Assembly.GetExecutingAssembly();` it complains about classes in application assembly and when `Assembly.GetCallingAssembly();` about classes in test assembly.

Is it possible to configure to use early bound classes from two assemblies?

**Comment by BetimBeja** [comment]
Hello @aslanovsergey ,
I think the only possible solution to your problem is to include the early bound classes needed for the tests in the assembly used for application code.
Best regards,
Betim.

**Comment by jordimontana82** [comment]
Hi @aslanovsergey  What version of FakeXrmEasy are you on?

There was a PR merged that changed the ProxyTypesAssembly from a single assembly to a list of assemblies so in theory you could provide them yourself using 

    Assembly.GetAssembly(typeof (T)).  

Just call it 2 times for 2 types from the 2 different assemblies and them pass them as a list to the ProxyTypesAssembly (assuming you have the version that supports that....

https://github.com/jordimontana82/fake-xrm-easy/blob/master/FakeXrmEasy.Shared/XrmFakedContext.cs#L48-L59

**Comment by jordimontana82** [comment]
It's actually a private list.... feel free to add another property that exposes a setter that accepts a list :)

We love PRs! :)

**Comment by BetimBeja** [comment]
Actually I just found out that you can call  [XrmFakedContext.EnableProxyTypes](  https://github.com/jordimontana82/fake-xrm-easy/blob/03af3b4cea94c7186cc293acf6efad63cbc8995a/FakeXrmEasy.Shared/XrmFakedContext.cs#L165) for both your assemblies to achieve what you want.
Probably the naming wasn't perfect here, but since Jordi pointed out that it was a private list I did a reference hunt and found the solution.
Best regards,
Betim.

**Comment by jordimontana82** [comment]
Great, thx Betim! So @aslanovsergey so can use that property to pass in the list of assemblies.

Closing this now, if you still have issues let me know.

**Comment by aslanovsergey** [comment]
Thanks @BetimBeja, this helps a lot!
