### ISSUE TITLE
The attribute "" does not exist on this entity on Retrieve

### ISSUE THREAD

**Issue by koener1985** [jordimontana82/fake-xrm-easy#399]
[CrmTest.zip](https://github.com/jordimontana82/fake-xrm-easy/files/2907306/CrmTest.zip)

When metadata is set with InitializeMetadata() the following method 
service.Retrieve("account", guid, new ColumnSet("statecode"));

fails with: 
The attribute statecode does not exist on this entity on Retrieve

A sample is attached.

**Comment by BetimBeja** [comment]
Hello @koener1985 ,
I didn't go into details on why you have that problem but changing your `GetAttributeMetadataForAccount` function to:
```
   private AttributeMetadata[] GetAttributeMetadataForAccount()
        {
            return new AttributeMetadata[]
            {
                new PicklistAttributeMetadata()
                {
                    LogicalName = "customertypecode"
                },
                new StringAttributeMetadata()
                {
                    LogicalName = "accountnumber"
                },
                new StateAttributeMetadata()
                {
                    LogicalName = "statecode"
                }
            };
        }
```

Makes the test pass for your example. Most probably the `statecode` attribute is expecting the type to be `StateAttributeMetadata` but I didn't step through the code.

Best regards,
Betim.

**Comment by jordimontana82** [comment]
@koener1985 agree. I've always used the concrete metadata classes in my tests rather than the base class so worth trying.

**Comment by koener1985** [comment]
Thanks, this solves the problem!

**Comment by FixRM** [comment]
Run into the same problem today. What I am doing wrong?

```C#
            // Set up metadata
            EntityMetadata ud_participant = new EntityMetadata()
            {
                LogicalName = "ud_participant",
            };
            AttributeMetadata ud_contactid = new AttributeMetadata
            {
                LogicalName = "ud_contactid",
            };

            ud_participant.SetFieldValue("_attributes", new AttributeMetadata[] { ud_contactid });

            XrmFakedContext fakedContext = new XrmFakedContext();
            fakedContext.InitializeMetadata(ud_participant);
```

**Comment by FixRM** [comment]
Solved! Must use StringAttributeMetadata
