### ISSUE TITLE
Hierarchical Condition Operators in QueryExpresssion Condition

### ISSUE THREAD

**Issue by jshah14** [jordimontana82/fake-xrm-easy#402]
Is there any way by which we can test hierarchical condition operators(Below, Above, AboveEqual, BelowEqual) using FakeXrmEasy ?

**Comment by jordimontana82** [comment]
Hi @jshah14 

Hierachy operators are not yet implemented. This is in the readme, under roadmap section, but [here's](https://github.com/jordimontana82/fake-xrm-easy/blob/master/FakeXrmEasy.Tests.Shared/FakeContextTests/FetchXml/ConditionOperatorTests.cs#L19-L110) a shortcut to the current list.

If you would like to add support for these please do let us know. Maybe a Draft Pull Request would be a nice idea just to get community feedback early.

Cheers
