### ISSUE TITLE
The entity logical name is not valid

### ISSUE THREAD

**Issue by suleimanali** [jordimontana82/fake-xrm-easy#406]
Having issues with testing a workflow. Its throwing an exception "The entity logical name [EntityName] is not valid".

Here's the code snippet:
![FakeXrmTestMethod](https://user-images.githubusercontent.com/10378908/54554377-abe90380-498a-11e9-87e4-b0f093e61b40.PNG)

![FakeXrmEntityLogicalName](https://user-images.githubusercontent.com/10378908/54554390-b2777b00-498a-11e9-97a5-2d799c1cddca.PNG)

**Comment by BetimBeja** [comment]
Hello @suleimanali,
most probably you are querying the `IOrganizationService` for `ca_configuration` but you are not initializing your context with the necessary data. Also any other entity assumed to be existing for your particular test case should be initialized.
```csharp
var xrmFakedContext = new XrmFakedContext();
xrmFakedContext.Initialize(entity);
```
This suggested change should fix your problem.

Best regards,
Betim.

**Comment by suleimanali** [comment]
Thank you very much @BetimBeja.
It worked perfectly.
