### ISSUE TITLE
Cannot use the ConditionOperator.In Operator for Guid

### ISSUE THREAD

**Issue by aboodh95** [jordimontana82/fake-xrm-easy#416]
Hi,

In case you are using FilterExpression and you want to filter base on records Ids, normal case you have to pass an array of string contain the Ids (string and not Guid) but while testing my code i was getting the error `The binary operator Equal is not defined for the types 'System.Guid' and 'System.String'`

**Comment by aboodh95** [comment]
any help with it

**Comment by BetimBeja** [comment]
Hello @aboodh95,
usually it is easier for us to understand the problem if you give us some Unit Tests to demonstrate the problem. As I understood your problem is that the real service accepts strings or GUIDs as values in the `ConditionOperator.In` operator but FakeXrmEasy only allows GUIDs.

Best regards,
Betim.

**Comment by aboodh95** [comment]
Yes,
In case i did like that for the real service 
`FilterExpression filter = new FilterExpression();
filter.AddCondition(ets_ReadingResult.Fields.ets_MonitoringPointType, ConditionOperator.In, types.Select(x => x.Id).ToArray());`

i will get this error
`Unhandled Exception: System.ServiceModel.FaultException: The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize parameter http://schemas.microsoft.com/xrm/2011/Contracts/Services:query. The InnerException message was 'Error in line 1 position 8215. Element 'http://schemas.microsoft.com/2003/10/Serialization/Arrays:anyType' contains data from a type that maps to the name 'System:Guid[]'. The deserializer has no knowledge of any type that maps to this name. Consider changing the implementation of the ResolveName method on your DataContractResolver to return a non-null value for name 'Guid[]' and namespace 'System'.'.  Please see InnerException for more details.`

and to solve it i have to make the array from type string and not Guid, the FakeXrmEasy is not accepting the array of type string and it's asking for Guid array

**Comment by BetimBeja** [comment]
Now I see the problem, I have been passing multiple values not as an array so it was working with strings as well as with GUIDs or a combination of them. FakeXrmEasy expects GUIDs, probably we should convert values to strings so the behaviour will be similar to the real Organization Service but I think that there would be a performance impact in doing so.

Best regards,
Betim.

**Comment by aboodh95** [comment]
In case this is the behavior of the real Organization Service, why you are expecting performance impact

**Comment by BetimBeja** [comment]
Hello @aboodh95,
I think there must be a better way to do this than doing string comparisons.
Also in the mean time I think you can do a slight modification to your condition so it can work on both the real Organization Service and FakeXrmEasy and that is casting your array to `object[]` in the following way:
```csharp
FilterExpression filter = new FilterExpression();
filter.AddCondition(ets_ReadingResult.Fields.ets_MonitoringPointType, ConditionOperator.In, types.Select(x => x.Id).Cast<object>().ToArray());
```
Best regards,
Betim.
