### ISSUE TITLE
OrganizationServiceFaultQueryBuilderNoAttributeException when updating from FakeXrmEasy.2015 to FakexrmEasy.9

### ISSUE THREAD

**Issue by bwmodular** [jordimontana82/fake-xrm-easy#417]
As part of a migration from 2015 online to D365 v9, I've just updated our test packages from the 2015 to the v9 version of FakeXrmEasy.

Several hundred tests still passing, but a small number are failing with a 'The attribute _attributename_ does not exist on this entity.' I've reverted back to the 2015 version to check and the tests all pass ok, so it's definitely the update.

Anything obvious I should check before I dig too deeply into this myself?

**Comment by jordimontana82** [comment]
Hi Ben, 

Could you please one of example of a unit test that is failing? Was the version of the package the same between 2015 and v9?

**Comment by bwmodular** [comment]
Hi Jordi,
I wish I could easily isolate a single test to share here, but this particular test project is quite complex in that the tests are driven by SpecFlow, so there's lots of code in the specflow step definitions for each of the clauses in the feature file.
I'm trying to work out what's different about these tests - I think it might be that the plugin queries the metadata using a RetrieveEntityRequest so there's some complex setup which initialises the metadata using the InitializeMetadata method, although it's not the RetrieveEntityRequest which is failing, but a regular RetrieveMultiple request...

That might be a red herring though...

I can see that the records are being created with the attribute specified, but the RetrieveMultiple is failing with the 'attrubutename does not exist on this entity' message.

**Comment by bwmodular** [comment]
PS Oh, yes, same version of FakeXrmEasy between 2015 and v9...

**Comment by bwmodular** [comment]
Hi again @jordimontana82, as my tests are still working with the  2015 version I'm going to deprioritise this change. The workflows in question will have to be rewritten to use Azure Functions anyway as part of our upgrade so I think I'll rewrite the code and then rewrite the tests from the ground up and see then whether I can establish what the problem is if it still exists. Closing the issue as I won't be working on this just now and I can't give you enough information to resolve the issue.

**Comment by jordimontana82** [comment]
No worries, and sorry, I've been a bit hectic in the last couple of weeks and specially this one with the next d365saturday in Kiev, among other things, so will take a look early next week.

In the meantime, I'm assuming you installed also the latest crmsdk bits in the unit test project and there are no binding redirects or similar?

If you have some time, a single unit test exampel would help a lot.

Cheers
