### ISSUE TITLE
An Exception is thrown when attempting to create an Association using a Self-Referential relationship

### ISSUE THREAD

**Issue by beady** [jordimontana82/fake-xrm-easy#418]
I have an entity that relates to itself, but when I attempt to create an instance of the N:N relationship to itself, an exception is thrown regarding a duplicate key.

[stacktrace-fakexrmeasy-nn-self-referential.txt](https://github.com/jordimontana82/fake-xrm-easy/files/3190510/stacktrace-fakexrmeasy-nn-self-referential.txt)

I have attached the stack trace, and also attached is a quick test to demonstrate the issue , along with a test with a succeeding associate message, where two different entities are linked.

[FakeXrmEasyMetadataTests.cs.txt](https://github.com/jordimontana82/fake-xrm-easy/files/3190525/FakeXrmEasyMetadataTests.cs.txt)

**Comment by BetimBeja** [comment]
Hello @beady,
I issued a PR with the fix for your problem. I slightly changed your proposed unit tests though, to make them compatible with all versions of FakeXrmEasy, and to make the tests behave like the latest version of the CRM. You can see my PR for more details if you like.
Best regards,
Betim Beja.

**Comment by beady** [comment]
Hi @BetimBeja 
Thanks for the fast turnaround on the issue.
Looking at your pull request was enlightening as to what the issue actually was. 

I am not so familiar with GitHub, and the processes for submitting PRs myself, but I have made a couple of changes to the PR you made. 

Namely, I changed the FakedRelationship class to look for the clash itself, when returning the Attribute names, so we don't have to "think" about setting additional postfixes on the names (as this seems like a little bit of code smell, especially as these postfixes are also magic values used within the Fake Associate Message Handler too). As such I have removed the changes from the Associate Message Handler, and adjusted the test, including renaming it to match a more typical test name (also, removed the second example test, as that was purely to demonstrate to myself that the functionality I was expecting worked)

The changes I have made appear to pass all the tests. Could you provide guidance on how I can pass this on to you, or the project more directly?

Thanks,
Dominic

**Comment by BetimBeja** [comment]
Hello Dominic ,
you can read my [article](https://t.co/ZMiEJampsy) on LinkedIn on how I co-authored PR #378 and please do the same for PR #419.

Best regards,
Betim.

**Comment by jordimontana82** [comment]
Added some comments in this PR #419

**Comment by BetimBeja** [comment]
Hello Jordi,
I can't seem to find the comments in PR #419 :(
Best regards,
Betim.

**Comment by jordimontana82** [comment]
Sorry, didn't submit it yet, it should be there now

**Comment by BetimBeja** [comment]
Hello Jordi,
I have already improved the PR as requested, can you add a Waiting PR Merge tag, and remove the waiting reply one?
Best regards,
Betim.
