### ISSUE TITLE
Using GetOrganizationService() to instantiate custom context

### ISSUE THREAD

**Issue by katymariehughes** [jordimontana82/fake-xrm-easy#423]
Hi! I have a CRMContext which wraps OrganizationServiceContext methods like CreateQuery()

`
public class CRMContext : OrganizationServiceContext 
{
public CRMContext(IOrganizationService service) : base(service) {
}
}`

I am constructing it with my XrmFakedContext's GetOrganizationService(), the context is initialized successfully with an item, but my CRMContext wrapper can't retrieve anything. If I try and add the item via my CRMContext, it throws an exception because it already exists. Is there something I should be doing instead?

Thanks!

**Comment by BetimBeja** [comment]
Hello @katymariehughes ,
I did a small test and it is passing, maybe you get what is missing in your tests from this sample one:

```csharp
[Fact]
public void TestContext()
{
    var context = new XrmFakedContext();
    context.EnableProxyTypes(Assembly.GetExecutingAssembly());
    var contact = new Crm.Contact()
    {
        Id = Guid.NewGuid()
    };

    context.Initialize(contact);

    var serviceContext = new CRMContext(context.GetOrganizationService());
    var result = from c in serviceContext.CreateQuery<Crm.Contact>()
                       select c;

    Assert.True(result.ToList().Any());
}
```

Best regards,
Betim.

**Comment by katymariehughes** [comment]
Hi Betim, thanks for such a quick response!

That's so bizarre. The first test using a class that is in the same file passes, the second, using CRMContext which lives in another project fails. CRMContext looks identical to TestCRMContext, just with a ton of methods removed. 

``` csharp
public class TestCRMContext : OrganizationServiceContext
{
    public TestCRMContext(IOrganizationService service) : base(service) { }

    public IQueryable<Contact> ContactSet => CreateQuery<Contact>();
}


[TestClass]
public class PreApplicationEmails
{
    private static Guid Id = new Guid("c409bd0a-0f36-4915-9f84-22ab82312b05");

    public CRMContext Context { get; private set; }
    
    [TestMethod]
    public void InitializedTestCRMContext_ContainsData()
    {
        var fakedContext = new XrmFakedContext();
        fakedContext.EnableProxyTypes(Assembly.GetAssembly(typeof(Contact)));
        var contact = new Contact()
        {
            Id = Guid.NewGuid(),
            FirstName = "Test"
        };

        fakedContext.Initialize(contact);

        TestCRMContext context = new TestCRMContext(fakedContext.GetOrganizationService());
        Contact retrievedContact = context.ContactSet.First();

        Assert.IsNotNull(retrievedContact);
        Assert.IsTrue(retrievedContact.FirstName == "Test");
    }

    [TestMethod]
    public void InitializedCRMContext_ContainsData()
    {
        var fakedContext = new XrmFakedContext();
        fakedContext.EnableProxyTypes(Assembly.GetAssembly(typeof(Contact)));
        var contact = new Contact()
        {
            Id = Guid.NewGuid(),
            FirstName = "Test"
        };

        fakedContext.Initialize(contact);

        CRMContext context = new CRMContext(fakedContext.GetOrganizationService());
        Contact retrievedContact = context.ContactSet.First(); // Sequence contains no elements

        Assert.IsNotNull(retrievedContact);
        Assert.IsTrue(retrievedContact.FirstName == "Test");
    }
}

**Comment by BetimBeja** [comment]
My best guess is that the Contact entity has been defined in the other assembly as well so in your second test the contact and the ContactSet refer to two different Contact entities so there are no records in ContactSet.
Basically you should reference your other assembly's Contact in your test.
I don't know if I was clear enough.
Best regards,
Betim.

**Comment by katymariehughes** [comment]
My solution structure is

```
Planning.Domain
    CRMContext.cs
    /Entities
        Contact.cs

Planning.Tests
    ContextTests.cs (where I have the two above tests for now)
```

both CRMContext and Contact have the same namespace 'Planning.Domain'. Preferably I would have had the context in my Planning.Data project, but I needed to have them in the same namespace for the proxy types to work with my DI container in my web project? At least that's the only fix that worked for me..

In my tests I am doing GetAssembly(typeof(Planning.Domain.Contact)); , always referring to the Planning.Domain namespace, there are no other Contact entities around

CRMContext is the context that CrmSvcUtil.exe generates, it has the following attribute, not sure if that makes a difference? Thank you so much for your help
```
[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssembly()]
namespace Planning.Domain {

**Comment by jordimontana82** [comment]
Hi Katy,

If you wrap your context inside a using statement and make queries inside the using block does that make any difference?

Also, if there is only one Proxy Types Assembly in theory there is no need to use it explicitly (i.e. when you call .Initialize() with some entities it should be set internally automatically.

I'm assuming your Planning.Tests project has a reference to Planning.Domain and Planning.Tests doesn't have any other generated proxy types assembly?

**Comment by jordimontana82** [comment]
@katymariehughes  any luck trying the using statement above?
