### ISSUE TITLE
OrganizationServiceFault ErrorCode is always 0

### ISSUE THREAD

**Issue by malachyoc** [jordimontana82/fake-xrm-easy#424]
At the moment most FaultExceptions do not appear to be setting the ErrorCode when they are being thrown.
  
Well know exceptions should have their ErrorCode set as this is often checked to determine how to proceed.  

I am mainly think of ones like: 0x80040217 "The specified object was not found" and so on.

**Comment by jordimontana82** [comment]
Nice feedback thx!

Yep, that might be useful all right. Right now most fault exceptions just return a default exception cause from a unit testing perspective was just enough to Assert if the logic throws or not a exception, but adding it might add extra feedback.

**Comment by jordimontana82** [comment]
Merged the fix for 424 and moved to #475
