### ISSUE TITLE
ConditionOperator.EqualUserOrUserTeams Not Implemented

### ISSUE THREAD

**Issue by davidosso** [jordimontana82/fake-xrm-easy#426]
Hello, 
I have seen that this ConditionOperator is not implemented but how can I inject an implementarion in fake-xrm-easy at runtime ?

Thanks in advance for your answers!

**Comment by BetimBeja** [comment]
Hello @davidosso,
I think the only way to inject an implementation of this operator in FakeXrmEasy is issuing a PR with the implementation.

Best regards,
Betim.

**Comment by jordimontana82** [comment]
Hi @davidosso ,

At the minute you can override many default messages at runtime, the a condition expression is so deep in the framework that you would need to replace the entire RetrieveMultiple message (not ideal) or else fork the project and add it via  PR as @BetimBeja  was suggesting.

That's going to be the easiest thing to do

**Comment by jordimontana82** [comment]
Closing this one, feel free to raise a PR if you'd like to! :)
