### ISSUE TITLE
Ambiguous reference to Microsoft.Xrm.Tooling.Connector

### ISSUE THREAD

**Issue by teppolainio** [jordimontana82/fake-xrm-easy#432]
I added a reference to NuGet package FakeXrmEasy.2016 version 1.54.0. This package requires `Microsoft.CrmSdk.XrmTooling.CoreAssembly (>= 8.0.0 && < 8.2.0)` as dependency. NuGet pulled Microsoft.CrmSdk.XrmTooling.CoreAssembly version 8.0.0 into the project.

When project was compiled there was warning about reference to Microsoft.CrmSdk.XrmTooling.CoreAssembly not being resolved correctly. After changing build log level to detailed I got following piece of information:
> Considered "bin\Debug\Microsoft.Xrm.Tooling.Connector.dll",
> 1>  			but its name "Microsoft.Xrm.Tooling.Connector, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
> 1>  			didn't match the expected name "Microsoft.Xrm.Tooling.Connector, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35".
> 1>          Considered "bin\Debug\Microsoft.Xrm.Tooling.Connector.exe", but it didn't exist.
> 1>      Required by "FakeXrmEasy, Version=1.54.0.0, Culture=neutral, PublicKeyToken=d91a65dda907a34f, processorArchitecture=MSIL".

This was resolved by changing unit test project app.config in following fashion:
Original after Microsoft.Xrm.Tooling.Connector was installed from NuGet
```
<dependentAssembly>
  <assemblyIdentity name="Microsoft.Xrm.Tooling.Connector" publicKeyToken="31bf3856ad364e35" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-2.0.0.0" newVersion="2.0.0.0" />
</dependentAssembly>
```

Manually changed binding from 2.1.0.0 to 2.0.0.0.
```
<dependentAssembly>
  <assemblyIdentity name="Microsoft.Xrm.Tooling.Connector" publicKeyToken="31bf3856ad364e35" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-2.1.0.0" newVersion="2.0.0.0" />
</dependentAssembly>
```

Could there be some incorrect build time reference to Microsoft.Xrm.Tooling.Connector version 2.1.0.0 instead of version 2.0.0.0 somewhere on FakeXrmEasy codebase? Version 2.0.0.0 is the one pulled out by NuGet dependency.

**Comment by BetimBeja** [comment]
Hello @teppolainio ,
[FakeXrmEasy.2016](https://github.com/jordimontana82/fake-xrm-easy/blob/v1.54.0/FakeXrmEasy.2016/packages.config) is built with [Microsoft.Xrm.Tooling.Connector](https://www.nuget.org/packages/Microsoft.CrmSdk.XrmTooling.CoreAssembly/8.1.0.2) v8.1.0.2 which has an assembly version of 2.1.0.0.
Best regards,
Betim.

**Comment by jordimontana82** [comment]
HI @teppolainio , each FakeXrmEasy project in nuget is compiled against a specific version of the SDK. However there might be minor updates of the SDK which won't necessarily match the compiled version, the solution for those scenarios is to use binding redirects as you already did. 

Hope this helps.
