### ISSUE TITLE
Question: How do I get a target value after it goes through a synchronise plugin?

### ISSUE THREAD

**Issue by ArdantHammer** [jordimontana82/fake-xrm-easy#434]
I am attempting to build a test for a prevalidation plugin on QualifyLead message that has a number of input values such as "target" and "CreateOpportunity". They get changed in the plugin before being passed back out to finish the pipeline. How can I check the value of those input parameters after the plugin has been run?

**Comment by BetimBeja** [comment]
Hello @ArdantHammer,
I think that you can achieve your test by passing the plugin context parameter when you call `ExecutePluginWith`. For example:

```csharp
            var context = new XrmFakedContext();

            var pluginContext = context.GetDefaultPluginContext();
            pluginContext.PrimaryEntityName = "lead";
            pluginContext.MessageName = "QualifyLead";
            pluginContext.Stage = 10;
            var target = new EntityReference("lead", Guid.NewGuid() );
            pluginContext.InputParameters["Target"] = target;

            var entity = new Entity();
            context.ExecutePluginWith<YourPlugin>(pluginContext);

            var modifiedInput = (EntityReference) pluginContext.InputParameters["Target"];

            Assert.NotNull(modifiedInput);
            Assert.NotEqual(target.Id, modifiedInput.Id);
```

Best regards,
Betim.

**Comment by ArdantHammer** [comment]
Duh, that is how I would access that value normally. Not sure why I did not think of that. Thank you very much that worked.
