### ISSUE TITLE
How to mock RetrieveProcessInstancesRequest/RetrieveProcessInstancesResponse classes using FakeXrmEasy framework in unit testing for plugin

### ISSUE THREAD

**Issue by Venkateshpilla08** [jordimontana82/fake-xrm-easy#436]
Hi All,
Currently I am preparing unit test cases for plugins and I am unable to Mock the below classes using FakeXrmEasy framework.
RetrieveProcessInstancesRequest procOpp2Req = new RetrieveProcessInstancesRequest
{
EntityId = caseId,
EntityLogicalName = "incident"
};
RetrieveProcessInstancesResponse procResp = (RetrieveProcessInstancesResponse)pluginBase.service.Execute(procOpp2Req);

**Observation:**
While executing the plugin using FakeXrmEasy it is throwing below exception

Exception: The organization request type 'Microsoft.Crm.Sdk.Messages.RetrieveProcessInstancesRequest' is not yet supported... but we DO love pull requests so please feel free to submit one! :). This functionality is not available yet. Please consider contributing to the following Git project https://github.com/jordimontana82/fake-xrm-easy by cloning the repository and issuing a pull request.

Could you please suggest me how to mock the above mentioned request and response classes using FakeXrmEasy. Wanted to do it with out creating wrapper classes.

Regards,
Venkatesh

**Comment by BetimBeja** [comment]
Hello @Venkateshpilla08 ,
please refer to the newly added [wiki](https://github.com/jordimontana82/fake-xrm-easy/wiki/Mock-an-OrganizationRequest) on how to mock the response.

Best regards,
Betim.

**Comment by jordimontana82** [comment]
Closing this one @Venkateshpilla08 (thx @BetimBeja  for updating the wiki)

**Comment by priya2chauhan-git** [comment]
@Venkateshpilla08 @jordimontana82  is this issue is fixed ?, as i am facing the same issue
The organization request type 'Microsoft.Crm.Sdk.Messages.RetrieveProcessInstancesRequest' is not yet supported.

**Comment by bwmodular** [comment]
@priya2chauhan-git please read the comment by @BetimBeja above to see how to implement your own mock, or see this article for other examples:
http://www.bwmodular.org/blog/mocking-unimplemented-organisation-requests-in-fakexrmeasy
