### ISSUE TITLE
When retrieve is invoked with an existing entity and only one column throws exception

### ISSUE THREAD

**Issue by ArdantHammer** [jordimontana82/fake-xrm-easy#437]
I have struggling with this issue for some time in my code. I searched and found the unit test that tests this functionality.  In the  test class FakeXrmEasyTestRetrieve => When_retrieve_is_invoked_with_an_existing_entity_and_only_one_column_only_that_one_is_retrieved

It works when you run the test. After comparing my code to the test and not finding any difference I changed the single column being searched in the test and it too failed throwing a Key not found in dictionary exception. So what am I missing? 

````
 [TestMethod]
        public void When_retrieve_is_invoked_with_an_existing_entity_and_only_one_column_only_that_one_is_retrieved()
 
```       {
            var context = new XrmFakedContext();

            //Initialize the context with a single entity
            var guid = Guid.NewGuid();
            var entity = new Entity("account") { Id = guid };
            entity["title"] = "Sample text";
            entity["name"] = "Test account";
            entity["createdon"] = DateTime.UtcNow;

            var data = new List<Entity>() { entity }.AsQueryable();
            context.Initialize(data);

            var service = context.GetFakedOrganizationService();

            var result = service.Retrieve("account", guid, new ColumnSet(new string[] { "title" }));
            Assert.AreEqual(result.Id, data.FirstOrDefault().Id);
            Assert.IsTrue(result.Attributes.Count == 1);
            Assert.AreEqual(result["name"], "Test account");
        }`

**Comment by durgaprasadkatari** [comment]
Hi,

You need to specify the "name" column in the service.retrieve
columnset("title","name")

Thanks,
Durgaprasad.

**Comment by ArdantHammer** [comment]
Thank you, you are correct. Although for the purpose of my test the last line should be 
`Assert.AreEqual(result["title"], "Sample text");`
Unfortunately, that means there is still something wrong with my original code. Thanks again.

**Comment by ArdantHammer** [comment]
Issue ended up being the fact that I initialized Entity Metadata for the incident without including the title attribute. 
Should have had:
```
EntityMetadata e = new EntityMetadata() { LogicalName = "incident" };
e.SetSealedPropertyValue("ObjectTypeCode", 112);
e.SetSealedPropertyValue("Attributes", new AttributeMetadata[] { new StringAttributeMetadata("title") {LogicalName = "title" } });
fakedContext.InitializeMetadata(e);
```

Instead of:

```
EntityMetadata e = new EntityMetadata() { LogicalName = "incident" };
e.SetSealedPropertyValue("ObjectTypeCode", 112);
fakedContext.InitializeMetadata(e);
```

Didn't realize they would rely on one another....lesson learned.
