### ISSUE TITLE
Support for version depending Requests

### ISSUE THREAD

**Issue by ccellar** [jordimontana82/fake-xrm-easy#44]
I've just stumpled upon the fact that at the moment there is no support for `ExecuteTransactionRequest`. I've then looked into the project to see, how I could implement the missing message executor for this request.

Have already thought about how version specific requests, like `ExecuteTransactionRequest` should be added? This specific message for example does only exist for CRM 2016 and therefore it would not make sense to place it in the shared project. 

~~Could we for example add a `Xrm2016FakedContext` to the 2016 project which inherits the `XrmFakedContext` and adds (for example) version specific messages?~~

I just wanted to make sure that there are no conflicting plans regarding this topic. 

**edit**
*I have just seen that you already have compilation symbols in place. I will use them.*

**Comment by jordimontana82** [comment]
Hi @ccellar 

Exactly! thx a mill for the pull request :+1:  :)
