### ISSUE TITLE
which package we should use for dynamics 365,fakexrmeasy.D365 or fakexrmeasy 9.0

### ISSUE THREAD

**Issue by ajaydandage** [jordimontana82/fake-xrm-easy#441]
Hi,

I am currently using fakexrmeasy.D365 and it only supports crm sdk dll >9.0.0.0, but my plugins are developed using 9.0 sdk dll, and not able to use fakexrmeasy.D365
What's your recommendations, shall we use fakexrmeasy 9.0?

**Comment by jordimontana82** [comment]
hi @ajaydandage , for 9.0 sdk you'll need to use package FakeXrmEasy.9.

I've updated the README to make it easier to understand.

Any other questions let us know.
