### ISSUE TITLE
Associate Request exception "Couldn't find reflected type for [relationship name]"

### ISSUE THREAD

**Issue by ajitthescorpion** [jordimontana82/fake-xrm-easy#446]
Hi @jordimontana82,
I am retrieving N:N relationship and using Associate method in my plugin code. In unit test case, I need to fake both of them i.e. to retrieve record from N:N relationship and Associate request.
Attached  is the unit test code. In the last line of the code, _service.execute(request), I am getting exception: "System.Exception: 'Couldnt find reflected type for dxc_revenuescheduleline_dxc_rate'". Please guide me. Appreciate your help on this.
[ErrorDetails (17).txt](https://github.com/jordimontana82/fake-xrm-easy/files/3537680/ErrorDetails.17.txt)

Thanks,
Ajit

**Comment by BetimBeja** [comment]
Hello,
I am inlining your unit test just for clarity:
```csharp
_context = new XrmFakedContext
{
    ProxyTypesAssembly = Assembly.GetAssembly(typeof(dxc_revenuescheduleline))
};
_entityList = InitialiseTestEntities();
           
_context.Initialize(_entityList);
_service = _context.GetOrganizationService();

_context.AddRelationship("dxc_revenuescheduleline_dxc_rate_association", 
    new XrmFakedRelationship
    {
        IntersectEntity = "dxc_revenuescheduleline_dxc_rate",
        Entity1LogicalName = dxc_rate.EntityLogicalName,
        Entity1Attribute = "dxc_rateid",
        Entity2LogicalName = dxc_revenuescheduleline.EntityLogicalName,
        Entity2Attribute = "dxc_revenueschedulelineid"
    });

var request = new AssociateRequest()
{
    Target = _entityList[2].ToEntityReference(),
    RelatedEntities = new EntityReferenceCollection()
    {
        new EntityReference(dxc_revenuescheduleline.EntityLogicalName, _entityList[6].Id),
    },
    Relationship = new Relationship("dxc_revenuescheduleline_dxc_rate_association")
};
_service.Execute(request);
```
I think that your early bound entities assembly does not contain the definition of your intersect entity  `dxc_revenuescheduleline_dxc_rate` and that might be the cause of your exception.

Best regards,
Betim Beja.

**Comment by ajitthescorpion** [comment]
Many thanks Betim for your response. I just included the intermediate entity in the early bound entities assembly and it worked :) 

Regards,
Ajit
