### ISSUE TITLE
InitializeMetadata issue when passing the EarlyBound Assembly

### ISSUE THREAD

**Issue by jorgeolive** [jordimontana82/fake-xrm-easy#452]
Hello, Jordi:

I am facing the following problem when initializing the metadata from my EB entities assembly: 

**"System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.Xrm.Client, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'**
"

Stack trace:

  | Name | Value | Type
-- | -- | -- | --
  | StackTrace | "   at FakeXrmEasy.Metadata.MetadataGenerator.CreateAttributeMetadata(Type propertyType)\r\n   at FakeXrmEasy.Metadata.MetadataGenerator.FromEarlyBoundEntities(Assembly earlyBoundEntitiesAssembly)\r\n   at FakeXrmEasy.XrmFakedContext.InitializeMetadata(Assembly earlyBoundEntitiesAssembly)\r\n   at Crm.AppData.EntityCreator.Tests.CrmApplicationTests.<ProperlyFormedFormData_TheCrmApplicationReturnsSuccessResponse>d__0.MoveNext() in C:\\Users\\j.olive\\source\\repos\\CrmServices\\CrmServices\\Crm.AppData.EntityCreator.Tests\\CrmApplicationTests.cs:line 23" | string

I am using net framework 4.6.2 with FakeXrmEasy 365. I let your package add all D365 Sdk references so everything vanilla mostly.  EarlyBound entities were generated with EBG from XrmToolBox. 

Any idea of what is going wrong?

Thank you,
Jorge.

**Comment by xairrick** [comment]
That library (Microsoft.Xrm.Client) was deprecated and removed from the SDK.  The last version that had it was 7.1.    You might be able to pull that DLL out of 7.1 and and include it in your test project.

It's referenced on one line in the MetadataGenerator.cs file when testing for a CrmEntityReference (which I don't think is used anymore).   I forked a copy of it and commented it out.

**Comment by jordimontana82** [comment]
Microsoft.Xrm.Client is not really needed, plus it's deprecated now. CrmEntityReference was generated using that namespace by a contributor but really we shouldn't use it anymore. In fact, is going definitely away in v2.x ;)
