### ISSUE TITLE
XrmFakedContext.FindReflectedAttributeType: Attribute not found for type

### ISSUE THREAD

**Issue by romangobrey** [jordimontana82/fake-xrm-easy#468]
Hi,

I'm using early-bound types and getting the "**XrmFakedContext.FindReflectedAttributeType: Attribute not found for type**" error. With late-bound types it works perfectly.
Can somebody point here what I am doing wrong?
**An exception is thrown at service.RetrieveMultiple(query) call.**

I'm using:
**Crm Sdk Assemblies: v8.2.0.2
FakeXrmEasy.365: v1.55.0
FakeItEasy: v3.2.0**

My library is targeting .Net **v.4.5.2**

The code is below
Thanks!

```
using System;
using System.Reflection;
using FakeXrmEasy;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;
using Microsoft.Xrm.Sdk.Query;
using NUnit.Framework;

[assembly: ProxyTypesAssembly]

namespace UnitTestProject1
{
	public static class Constants
	{
		public const string ContactEntityName = "contact";
		public const string ContactNameField = "Name";
		public const string ContactNameValue = "Contact1";
	}

	[EntityLogicalName(Constants.ContactEntityName)]
	public class ContactEntity : Entity
	{
		public ContactEntity() : base(Constants.ContactEntityName)
		{
		}

		public string Name
		{
			get => GetAttributeValue<string>(Constants.ContactNameField);
			set => SetAttributeValue(Constants.ContactNameField, value);
		}
	}

	[TestFixture]
	public class UnitTest1
	{
		[Test]
		public void TestMethod1()
		{
			var context = new XrmFakedContext();
			context.Initialize(new[]
			{
				new ContactEntity {Id = Guid.NewGuid(), Name = Constants.ContactNameValue}
			});
			context.ProxyTypesAssembly = Assembly.GetAssembly(typeof(ContactEntity));

			var query = new QueryExpression("contact");
			query.Criteria.AddCondition(Constants.ContactNameField, ConditionOperator.Equal, Constants.ContactNameValue);

			var service = context.GetOrganizationService();
			var result = service.RetrieveMultiple(query);
		}
	}
}
```

**Comment by BetimBeja** [comment]
Hello @romangobrey ,
your early bound entity is missing the attribute logical name in the Name property, without that there is no way for the framework to know the attributes.
I would suggest you generate your early bound entities with a tool, please check **Early Bound Generator** or **Albanian Early Bound** in **XrmToolBox**.
Best regards,
Betim.

**Comment by romangobrey** [comment]
Thanks @BetimBeja,
That worked!

**Comment by BetimBeja** [comment]
Hello Roman,
I am glad it worked.
Can you please close the issue?
Best regards,
Betim.
