### ISSUE TITLE
Register Plugins with Pre- & Post-Image(s)

### ISSUE THREAD

**Issue by psengeis** [jordimontana82/fake-xrm-easy#471]
Hello,
I found this repository few days ago and I'm totally impressed! **Great work!**

Do you have any plans for adding some features concerning integration-tests for plugins?
I would really like to test if my plugins are working in combination (without infinite looping).

Example:
Synchronizing some value(s) from contact to a referenced entity and all of the other contacts that also has the same reference.

Therefore i have to compare the old values (PreImage) with the new data (PostImage) to not make endless updates between them.

```
public void UpdatePerson(ICrmContext context, contact postImage, contact preImage)
{
	if (preImage.JobTitle != postImage.JobTitle)
	{
		new_person updatePerson = new new_person()
		{
			Id = postImage.new_personid.Id
			new_jobtitle = postImage.JobTitle
		};

		context.CrmService.Update(updatePerson);
	}
}
```
I saw the Item #183  which helpes a lot with integration tests, but unfortunatly executing plugins results in null references because of no images.

Best way would be to extend the function "RegisterPluginStep" von the context with an additional parameter for images (Name, ProcessingStepImageType - already existing in code, attributes).

Thanks very much!

**Comment by jordimontana82** [comment]
Thanks @psengeis  !

I'll move this to the issue you mentioned... it might be easier to track from the one place...
