### ISSUE TITLE
 `context.RegisterPluginStep("Create")` not triggered by `context.GetOrganizationService().Create`

### ISSUE THREAD

**Issue by skfd** [jordimontana82/fake-xrm-easy#480]
Hello!
I'm trying to test the context specifics of the plugin by simulation Create and Delete event for an entity. But my plugin step is not triggered.

```cs
var accountToDelete = new Entity(AccountDefinition.EntityName, Guid.NewGuid())
    {
        [AccountDefinition.Columns.Name] = "Deleted company"
    };
context.GetOrganizationService().Create(accountToDelete);
context.RegisterPluginStep<MyPlugin>(
    "Delete", ProcessingStepStage.Postoperation);
context.GetOrganizationService().Delete(
    accountToDelete.ToEntityReference().LogicalName, accountToDelete.ToEntityReference().Id);
```

**Comment by BetimBeja** [comment]
Hello @skfd,
are you using [Pipeline Simulation](https://github.com/jordimontana82/fake-xrm-easy/blob/a19cfdb8b48ec97bb32259e9b7428400e6d0c287/FakeXrmEasy.Shared/XrmFakedContext.Pipeline.cs#L12)?

Best regards,
Betim.

**Comment by skfd** [comment]
I got stuck on #546 but looks like everything changed, so I'm closing

**Comment by jordimontana82** [comment]
@skfd  Yep,This should be working in v2/v3 versions, you can even combine it to automatically read plugin registration attributes now.

Feel free to give it a go there, here's a comprehensive new docs site , highly recommended the upgrading guide from v1.x.

https://dynamicsvalue.github.io/fake-xrm-easy-docs/quickstart/plugins/pipeline/

https://dynamicsvalue.github.io/fake-xrm-easy-docs/quickstart/plugins/pipeline/automatic-registration/

Highly recommended the migration guide in 6 steps on this link:

https://dynamicsvalue.github.io/fake-xrm-easy-docs/quickstart/migrating-from-1x/
