### ISSUE TITLE
Random CallerId when using XrmRealContext

### ISSUE THREAD

**Issue by Dremor** [jordimontana82/fake-xrm-easy#488]
Hi.

I have a plugin that retrieve the systemuser that call it. I'm trying to use a XrmRealContext in order to test it against a real CRM instance, but I get an error as the provided caller ID doesn't exist in the CRM.

After some investigation, it looks like the CallerID that XrmRealContext gives is the random one generated by the underlying XrmFakedContext, which cause my problem.

Is there a way to get the real CallerID from XrmRealContext, instead of the fake one ?

Best regards.

**Comment by Dremor** [comment]
Ok, I managed to get it like that (Dynamics 9.x Online):

```csharp
            CrmServiceClient service = (CrmServiceClient)context.GetOrganizationService();
            Guid currentUserId = service.GetMyCrmUserId();
            context.CallerId = new EntityReference("systemuser", currentUserId);
```

**Comment by jordimontana82** [comment]
Hi @Dremor , the callerId property was introduced to easily mock the impersonation in fake messages, but was not envisaged to use with XrmRealContext. To retrieve the current user Id is better to call WhoAmIRequest, the callerId (in the context of an OrganizationServiceProxy or OrganizationWebProxyClient) is meant to be used to override the the current user (that is for impersonation).

https://docs.microsoft.com/es-es/dotnet/api/microsoft.xrm.sdk.client.organizationserviceproxy.callerid?view=dynamics-general-ce-9#Microsoft_Xrm_Sdk_Client_OrganizationServiceProxy_CallerId

**Comment by Dremor** [comment]
That would probably be better, but I'm stuck with a lot of legacy code that just access the callerid for whatever reason. Still, it would be better, in order to take care of these case, to not provide random callerId.

**Comment by jordimontana82** [comment]
Which code? 

XrmFakedContext gives a default value to prepopulate properties like CreatedBy and ModifiedBy. If there is some code that needs to specifically impersonate a user, it would be best to set the CallerId to whatever Guid you need before doing anything else (usually as soon as you instantiate it). 

Now, in v2.x XrmRealContext won't inherit from XrmFakedContext anymore, they'll share  a few methods from a common interface, but that's it, meaning that, XrmRealContext won't inherit some side effects from XrmFakedContext too, if that helps.

I'm closing this specific issue, if you still have questions please reopen.

**Comment by Dremor** [comment]
Is there a way to test the new version ?

**Comment by jordimontana82** [comment]
I'm still in the middle of many changes (including adding porting the framework to .net core), so is not yet published, but once it is I'll post a note into this repo. As long as you're watching it you'll get a notification :)
