### ISSUE TITLE
Can't extend FakedService with Fake It Easy testing functionalities

### ISSUE THREAD

**Issue by hsouth95** [jordimontana82/fake-xrm-easy#49]
When using extensions like A.CallTo(..), I can't seem to get it to work with the FakedService. For example when trying to verify that FakedService.Retrieve(..) was called Repeated.Exactly.Once, I never pass this as it does not register against the correct IOrganizationService. What is the correct way of doing this?

**Comment by jordimontana82** [comment]
Could you post a unit test of what you are trying to do please?

**Comment by hsouth95** [comment]
Is this enough or would like the setup of the FakedContext too?
```
[TestMethod]
        public void UpdateCurrentParentAccountChangesNothing()
        {
            // Arrange
            this.parentAccount["statuscode"] = new OptionSetValue((int)StatusCode.Current);

            // Act
            this.context.ExecutePluginWith<UpdateAccount>(this.pluginContext);

            // Assert
            var account = (from a in this.context.CreateQuery("account")
                           where a.Id == this.parentAccount.Id
                           select a).FirstOrDefault();

            A.CallTo(() => this.service.Update(A<Entity>.Ignored)).MustNotHaveHappened();
            Assert.IsNotNull(account);
            Assert.IsTrue(account.GetAttributeValue<OptionSetValue>("statuscode").Value == (int)StatusCode.Current);
        }
```

**Comment by jordimontana82** [comment]
Ok, I know what you mean know :)

At the minute those extensions are managed internally by the framework. They are not exposed, cause the intent of framework is to have these mocks already done adn to write unit tests pretty much like if you were writing CRM customizations. 

For example, there is a mock already for the Update message.

So, I suppose in that example, if what you need is to make sure the account attribute wasn't updated, it would be enough with these 2 asserts you had:

        Assert.IsNotNull(account);
        Assert.IsTrue(account.GetAttributeValue<OptionSetValue>("statuscode").Value == (int)StatusCode.Current);

**Comment by jordimontana82** [comment]
Another thing, I saw you are keeping an instance of the context outside your unit test? This is not ideal, because the context keeps you entities in memory, a unit test execution could affect other tests if you share the same instance. Better to instantiate a context per test, so that the tests will be repeatable.

**Comment by hsouth95** [comment]
Thank you for your response! That makes sense however it does prevent us from achieving the code coverage that we want. I will keep that in mind. I'm not used to unit testing, so thank you for the advice.

**Comment by jordimontana82** [comment]
You're very welcome :+1:

**Comment by jordimontana82** [comment]
@hsouth95 maybe is a bit too late for this... but never say never!

As other users requested this, now the service is a singleton instance so, you could things like this from now on:

A.CallTo(() => this.service.Create(A<Entity>.Ignored)).MustNotHaveHappened();
