### ISSUE TITLE
How to use configurations with a mocked plugin class

### ISSUE THREAD

**Issue by LeeJP1983** [jordimontana82/fake-xrm-easy#494]
Hello,

I have a plugin helper class that inherits from IPlugin, then all of my plugin classes inherit from this plugin helper. I have need to send a secure configuration to a new plugin and I am attempting to unittest this. This new plugin makes a lot of calls to an external web service, which I created an internal method to handle. I need to mock the plugin so that I can mock this method, and not actually send the web requests.

I can get each of these to work individually, but when I try to combine them I am running into issues. I don't see a way to pass configurations in when I use ExecutePluginWith(). And I don't see a way to provide a mocked plugin when using ExecutePluginWithConfigurations<>(), except for the obsolete method. The obsolete method doesn't seem to call the proper constructor anyways.

Any help setting up configurations with a mocked plugin would be great.

Thanks,
Jerimiah

**Comment by BetimBeja** [comment]
Hello,
you can create your own instance of the plugin (you use the constructor with the configurations) and use one of the methods like [ExecutePluginWith](https://github.com/jordimontana82/fake-xrm-easy/blob/5531248d7e9dc2a112b17735e0bf5939e974d342/FakeXrmEasy.Shared/IXrmFakedContext.cs#L126) to run your test.

Best regards,
Betim.

**Comment by LeeJP1983** [comment]
Oh, of course, how could I have not seen that. I got too far into the weeds.

Thanks Betim!
