### ISSUE TITLE
PrimaryEntityName return ""

### ISSUE THREAD

**Issue by phuocle** [jordimontana82/fake-xrm-easy#50]
My plugin code here

`public void Execute(IServiceProvider serviceProvider)
        {
            var context = (IPluginExecutionContext)serviceProvider.GetService(typeof(IPluginExecutionContext));
            if (context == null) throw new InvalidPluginExecutionException("Initialize IPluginExecutionContext fail.");
            var serviceFactory = (IOrganizationServiceFactory)serviceProvider.GetService(typeof(IOrganizationServiceFactory));
            if (serviceFactory == null) throw new InvalidPluginExecutionException("Initialize IOrganizationServiceFactory fail.");
            var service = serviceFactory.CreateOrganizationService(context.UserId);
            if (service == null) throw new InvalidPluginExecutionException("Initialize IOrganizationService fail.");
            var tracing = (ITracingService)serviceProvider.GetService(typeof(ITracingService));
            if (tracing == null) throw new InvalidPluginExecutionException("Initialize ITracingService fail.");
            if (context.PrimaryEntityName.ToLower() != "Account".ToLower()) throw new InvalidPluginExecutionException("PrimaryEntityName does not equals Account");
            if (context.MessageName.ToLower() != "Create".ToLower()) throw new InvalidPluginExecutionException("MessageName does not equals Create");
            if (context.Stage != 20) throw new InvalidPluginExecutionException("Stage does not equals PreOperation");
            ExecutePlugin(context, service, tracing);
        }`

My Test

`public void Test1()
        {
            var context = new XrmFakedContext();
            var pluginContext = context.GetDefaultPluginContext();
            pluginContext.PrimaryEntityName = "Account";
            pluginContext.MessageName = "Create";
            pluginContext.Stage = 20;
            var entity = new Entity();
            context.ExecutePluginWith<PreAccountCreate>(pluginContext);
            Assert.True(true);
        }`

I assigned PrimaryEntityName = "Account" but in the context it return ""

Messagename and Stage OK

Thanks

**Comment by jordimontana82** [comment]
Hi @phuocle ,

Thanks a mill. It looks like we missed to implement PrimaryEntityName and SecondaryEntityName [here](https://github.com/jordimontana82/fake-xrm-easy/blob/8f2a900f16e487f98933a6c041032c2dd5cdd709/FakeXrmEasy.Shared/XrmFakedContext.Plugins.cs#L41-L51)

Would you mind creating a fork, making the appropiate changes, and submit a PR?

Thanks!

**Comment by jordimontana82** [comment]
The [other option](https://github.com/jordimontana82/fake-xrm-easy/blob/8f2a900f16e487f98933a6c041032c2dd5cdd709/FakeXrmEasy.Shared/XrmFakedContext.Plugins.cs#L55-L62) would be to pass a target to your plugin, and it should default the Primary entity name to the Entity's logical name.

**Comment by jordimontana82** [comment]
Hey @phuocle 

I fixed that. There could be other properties which might be need to be passed in the same way.  If you need more of them, you can use associated commit as an example. Feel free to add them and submit a pull request :+1:
