### ISSUE TITLE
Tune in to see What's coming in FakeXrmEasy v2

### ISSUE THREAD

**Issue by jordimontana82** [jordimontana82/fake-xrm-easy#504]
This sunday I'll be doing a session of what I've been working on in the last couple of months:

FakeXrmEasy v2 will run on .net core 3.1.

This is a free online event on Teams on Sunday at 10 AM UTC.

Feel free to tune in!

https://www.365portal.org/events/event/?id=c02ceafe-2678-ea11-a811-000d3a86d7a8

https://bit.ly/ProDevOnlineSun

**Comment by jordimontana82** [comment]
Also, please feel free to fill in this survey to tailor the session content:

https://forms.gle/xgeKjj6XNZm29yoCA

**Comment by jordimontana82** [comment]
Few hours left for the PowerNerdFest only and just a few more than 24hrs left for FakeXrmEasy v2 session... !   Looking forward seeing you there! 

@BetimBeja  @DigitalFlow @rbnswartz @teppolainio @eNeRGy164 @bwmodular  @AleksandrRogov @rajyraman  @vjain90  @sergeytunnik @phuocle @mivra @camelCaseDave

**Comment by teppolainio** [comment]
Thanks for the ping! I'll see if I can make it on Sunday.

**Comment by jordimontana82** [comment]
Just in case you couldn't make it....

Here's a link with a new repo which has slides + link to recorded session as well as the sample app I used in the demo... 

https://github.com/DynamicsValue/power-platform-dev-saturday

**Comment by jordimontana82** [comment]
Closing this one, if you have any questions / feedback on the demo please do let me know.
