### ISSUE TITLE
Privilegeobjecttypecode does not exist in the metadata error

### ISSUE THREAD

**Issue by marcster** [jordimontana82/fake-xrm-easy#512]
I am trying to write unit tests around security roles and privileges. I am using a fetchxml query which includes the privilegesobjecttypecodea entity and am getting the “entity does not exist error”.  Is there a way to get around this error?

**Comment by jordimontana82** [comment]
If that error is because crmsvcutil doesn't generate such entity, could try injecting some dummy metadata for that entity first, and then using late bound?

https://github.com/jordimontana82/fake-xrm-easy/blob/5531248d7e9dc2a112b17735e0bf5939e974d342/FakeXrmEasy.Tests.Shared/FakeContextTests/RetrieveMultiple/RetrieveMultipleTests.cs#L492-L516

**Comment by marcster** [comment]
Thanks for the suggestion Jordi but still unable to access the privilegeobjecttypecode entity in this way as I get an entity not found error. I’m thinking this is a “special” entity.

**Comment by jordimontana82** [comment]
Could you please paste a sample unit test to reproduce so?

**Comment by marcster** [comment]
From your example, I did this:

var privilegeObject = new EntityMetadata() { LogicalName = "privilegeobjecttypecodes" };

        privilegeObject.SetSealedPropertyValue("objecttypecode", "contact");  errors here

            privilegeObject.SetSealedPropertyValue("privilegeid", new Guid("93cafd0d-dbe1-4cb9-bb7b-e9f3a0c0464a"));
     privilegeObject.SetSealedPropertyValue("solutionid", new Guid());
          _xrmContext.InitializeMetadata(privilegeObject);

So I hope this is what you meant for me to do.

**Comment by jordimontana82** [comment]
Hi @marcster 

I've added a sample here querying that entity using late bound and no metadata., which proves it works fine with late bound as well.

Hope this helps.

https://github.com/jordimontana82/fake-xrm-easy/blob/master/FakeXrmEasy.Tests.Shared/Issues/Issue512.cs#L34-L46

**Comment by marcster** [comment]
Hi @jordimontana82. Thanks for the quick turnaround and the code sample. I think my requirement is slightly different and so I will see if I can use your suggestion to get it working.
