### ISSUE TITLE
FakeXrmEasy.9 1.57.1 not installing correctly

### ISSUE THREAD

**Issue by bwmodular** [jordimontana82/fake-xrm-easy#515]
I can't help feeling that I'm doing something stupid, but I can't figure it out.
New project in Visual Studio 2019 - v 16.6.5

Try and install the latest version (1.57.1) of FaxeXrmEasy.9.
It does not error, and some dependencies, such as FakeItEasy, get installed, but FakeXrmEasy does not:

![image](https://user-images.githubusercontent.com/1889586/88799285-255b4d80-d19e-11ea-85a5-03782c97899d.png)

Downgrade to version 1.57.0 and it installs fine:

![image](https://user-images.githubusercontent.com/1889586/88799330-373cf080-d19e-11ea-855e-d53dec4a6a8c.png)

Restarting Visual Studio does not help.

Package Manager console doesn't indicate any problems:
_Successfully installed 'FakeXrmEasy.9 1.57.1' to Plugins.UnitTests
Removing package 'FakeItEasy.3.2.0' from folder 'C:\...\packages'
Removed package 'FakeItEasy.3.2.0' from folder 'C:\...\packages'
Removing package 'FakeXrmEasy.9.1.57.0' from folder 'C:\...\packages'
Removed package 'FakeXrmEasy.9.1.57.0' from folder 'C:\...\packages'
Executing nuget actions took 6.45 sec_

**Comment by jordimontana82** [comment]
Hi Ben,

What is the .net target version you're using?  v9 is using [.net 4.6.2 as the new baseline](https://github.com/jordimontana82/fake-xrm-easy/commit/9f790bb3834a7c5d72528390f4056c8d2ae02583)

**Comment by bwmodular** [comment]
Hi Jordi,
of course you are right. My project was targeting 4.5.2. All working fine now. Strange that it fails so quietly though. I'd expect the NuGet package manager to at least tell me that it can't install FakeXrmEasy....
Thanks as ever,
Ben

**Comment by jordimontana82** [comment]
You're welcome, yeah I agree the nuget package installer is not very explicit about these issues alright....

Closing this one now.
