### ISSUE TITLE
Can we update the Microsoft.CrmSdk.XrmTooling.CoreAssembly to utilise version 9.1.0.13

### ISSUE THREAD

**Issue by agouzaliInteractive** [jordimontana82/fake-xrm-easy#518]
Can we update the Microsoft.CrmSdk.XrmTooling.CoreAssembly to utilise version 9.1.0.13 or above? 

I'm having difficulty on connecting to the XrmRealContext using client secret as the username and password is not supported anymore when MFA is turned on.

**Comment by jordimontana82** [comment]
You can update the the XrmTooling package and then apply a binding redirect if needed.
