### ISSUE TITLE
Easy way to set initial state of entities and relations

### ISSUE THREAD

**Issue by gaui** [jordimontana82/fake-xrm-easy#526]
I am wondering if there is some easy way to set the initial state of entities and data. I have a lot of entities and relations, and it's a lot of work to set up the state before running the tests. Is there some easier way to set up the initial state?

**Comment by jordimontana82** [comment]
Hi @gaui 

I usually setup only the minimum set of entities / relationship for each scenario, and define them as properties of the test class, and update the attributes needed for each test only.

That keeps unit tests reasonably small and easy to mantain.

**Comment by gaui** [comment]
Yeah I know, that's what I do currently. But I was thinking more of like loading some kind of JSON documents defining the entities and deserializing that to Entity objects. Which I can then store in files in Git. I'm not really sure what would be ideal, but I think the current way is really time-consuming because we have a lot of different entities (state) that have to be set up for each test-case. 🤔

**Comment by gaui** [comment]
Maybe this is not related to this project and should be another project. But if the data follows standards/schemas from CDS, then this could maybe be a part of this project.

**Comment by jordimontana82** [comment]
This has been raised a number of times and it's out of scope of this project. The issue with reading from files is that you loose the goodies of rename / refactor, plus reading from disk will make tests run 100x slower.  I prefer having the data for each class / unit of work in code, in that way I could easily update / remove / change it along with its logic.

Setting up these entities (doesn't have to be hundreds, it's usually almost always < 10 records) doesn't take that much time compared to implementing the actual logic (in my own experience).  If you have too many records needed maybe the logic under test is too big, and it could be broken down?

Now, if you still want to do it, you could use an external tool / project to [serialize / deserialize entities first](https://github.com/albanian-xrm/Xrm-Entity-Serializer) like the one by @BetimBeja 's
