### ISSUE TITLE
`PipelineSimulation` does not support plugin with `unsecureSettings, secureSettings` arguments

### ISSUE THREAD

**Issue by skfd** [jordimontana82/fake-xrm-easy#546]
**Is this a bug really?**
I'd say it's a bug because I use PipelineSimulation as expected, registering my plugin (that only has full constructur with arguments). The registration succeeds, but execution crashes nastily because plugin does not satisfy `new()` constraint.

**Describe the bug**
Code with `PipelineSimulation` crashes with obscure error instead of explicitly throwing "we have no support for Plugins that depend on SecureConfiguration/UnsecureConfiguration configuration yet"

**To Reproduce**
Here is a minimal plugin. I'm sure lots of people use `UnsecureSettings` feature.
```csharp
public abstract class PluginBase : IPlugin
{
    protected readonly string UnsecureSettings;
    protected readonly string SecureSettings;

    protected PluginBase(string unsecureSettings, string secureSettings)
    {
        UnsecureSettings = unsecureSettings;
        SecureSettings = secureSettings;
    }
}
```

**Expected behavior**
* For now throw explicit expection "we have no support for Plugins that depend on SecureConfiguration/UnsecureConfiguration configuration yet"
* For future, support this feature. Plugin should be registered with optional cofigurations

** FakeXrmEasy and Dynamics 365 / CRM version **
FakeXrmEasy 1.57.1

**Comment by jordimontana82** [comment]
Thanks for raising this. Pipeline is being redeveloped in v2 so I'll take this into account.

**Comment by jordimontana82** [comment]
@skfd also closing as per https://github.com/jordimontana82/fake-xrm-easy/issues/480#issuecomment-1507609668
