### ISSUE TITLE
Images for NuGet package

### ISSUE THREAD

**Issue by jordimontana82** [jordimontana82/fake-xrm-easy#55]
Hi guys @DigitalFlow , @crisfervil, @kmjones77 

I was spending some time on a logo for the NuGet package.

Which one of these would you prefer? : )

Logo 1: 
![fakexrmeasy](https://cloud.githubusercontent.com/assets/3968950/14409791/8c55e264-ff1d-11e5-9563-77bbe53cc76b.png)

Logo 2:
![fakexrmeasy2](https://cloud.githubusercontent.com/assets/3968950/14409792/92a525e4-ff1d-11e5-8e88-779983cb35c7.png)

Logo3:
![fakexrmeasy3](https://cloud.githubusercontent.com/assets/3968950/14409793/963e6d14-ff1d-11e5-957e-93b8c433c1e4.png)

It's a pitty only PNG files of 64x64 can be uploaded cause the SVG version look way better than these ones! : (

**Comment by jordimontana82** [comment]
These are the SVG equivalents: 

![Logo 1](http://dynamicsvalue.com/images/fakexrmeasy.svg) 
![Logo 2](http://dynamicsvalue.com/images/fakexrmeasy2.svg) 
![Logo 3](http://dynamicsvalue.com/images/fakexrmeasy3.svg)

**Comment by DigitalFlow** [comment]
Hey Jordi,

I like version 1 best colourwise, although I prefer the text of version3. A mixture of them would look be my favorite.

Kind regards 
Florian

**Comment by jordimontana82** [comment]
Cool, a mix of both would be my favourite too : )

Kind regards.
