### ISSUE TITLE
ConditionOperator.LessThan is throwing error "Specified Cast is not valid" for DateTimeField

### ISSUE THREAD

**Issue by pavansarma93** [jordimontana82/fake-xrm-easy#571]
I am trying for the below code and I encountered the error saying **"Specified Cast is not valid"** , The error is on the **DateTime field** , This is a valid condition because it is giving the data required when executing on plugin. However the Unit test is failing. Hope this would be fixed soon.

````
[TestMethod]
        public void TestMethod1()
        {
            XrmFakedContext fakeContext = new XrmFakedContext();
            IOrganizationService service = fakeContext.GetOrganizationService();
```

            Entity account = new Entity("account",Guid.NewGuid());
            account["createdon"] = DateTime.Now.AddDays(-1).ToShortDateString();

            fakeContext.Initialize(new List<Entity>() {
            account
            });

            QueryExpression query = new QueryExpression("account");
            query.Criteria.AddCondition("createdon", ConditionOperator.LessThan, DateTime.Now.ToShortDateString());

            var result = service.RetrieveMultiple(query);



        }`

**Comment by jordimontana82** [comment]
HI @pavansarma93 ,

Did you try initialising the account record with the actual DateTime value instead of the string? Do you get the same error?

**Comment by pavansarma93** [comment]
@jordimontana82 : That's a very quick response. yeah after that it fixed. Thank you so much. Just a request if possible in your blogs can you add the examples for a late bound plugin with all standard operations (retrieve, retrievemultiple, create etc.). Because there are no resources out there.

**Comment by jordimontana82** [comment]
Thanks, yes, we're upgrading the website actually, so a brand new docs site will be available.
