### ISSUE TITLE
The specified service type is not supported when using Microsoft.Xrm.Sdk.PluginTelemetry.

### ISSUE THREAD

**Issue by TaneliPeussa** [jordimontana82/fake-xrm-easy#583]
I've added  _using Microsoft.Xrm.Sdk.PluginTelemetry;_ and _ILogger logger = (ILogger)serviceProvider.GetService(typeof(ILogger));_ to my plug-in in order to log into Applicaton Insights.

If I update my plug-in unit test project to use the latest **Microsoft.CrmSdk.CoreAssemblies** (9.0.2.42) I'll get _FakeXrmEasy.PullRequestException: Exception: The specified service type is not supported._  I'm using **FakeXrmEasy.9** (1.57.1). 

Is there any workaround for this?

**Comment by BetimBeja** [comment]
There is already PR ##561 which should solve this problem.
Be sure to follow @jordimontana82  on the Dataverse Summit [here](https://events.powercommunity.com/sessions/new-fakexrmeasy-architecture-overview-and-roadmap/) for the latest news and the state of the project 😄

**Comment by TaneliPeussa** [comment]
Thank you @BetimBeja.
