### ISSUE TITLE
ExecutePluginWith<T>(...) has no parameter for MessageName - need to use obselete method ExecutePluginWithTargetAndPreEntityImages<T>(...)

### ISSUE THREAD

**Issue by thomas-schiller** [jordimontana82/fake-xrm-easy#597]
My PostUpdate plugin uses a preImage. 
I need to set the PreImage for my plugin execution. I don't see any possiblity to pass an PreImage AND set the message name to "Update" (always default--> "Create")

Hence I am forced to use the obsolete method "ExecutePluginWithTargetAndPreEntityImages". The obsolete warning tells me to use "ExecutePluginWith", but I don't find any possiblity to set the message name.
Am I wrong?

**Comment by jordimontana82** [comment]
Hi Thomas,

It is indeed possible. You can use the GetDefaultPluginContext method to retrieve a default context and override whatever is needed before passing it into the ExecutePluginWith<T> method, including setting any PreEntityImages you want as well as the message name:

https://github.com/jordimontana82/fake-xrm-easy/blob/486c7ff0bd4c78262a9a5c1cd77056d9571fe4de/FakeXrmEasy.Shared/XrmFakedContext.Plugins.cs#L23-L32

Also, you might want to take a look at the later version cause v1.x is deprecated and will stop receiving updates soon....

https://dynamicsvalue.github.io/fake-xrm-easy-docs/quickstart/migrating-from-1x/

Feel free to ping me if you still have questions.

**Comment by jordimontana82** [comment]
I'm also adding a sample using that approach, not necessarily for PreEntityImages but other InputParameters, although it should work as well:

https://dynamicsvalue.github.io/fake-xrm-easy-docs/quickstart/plugins/overview/
