### ISSUE TITLE
`type argument 'FakeXrmEasyUpdatePluginCrash.MyPlugin' violates the constraint of type parameter 'T'.`

### ISSUE THREAD

**Issue by skfd** [jordimontana82/fake-xrm-easy#604]
**Describe the bug**
Pipeline update message test crashes with `violates the constraint of type parameter 'T'.` message. Works OK for create message.

**To Reproduce**
[repo with repro](https://github.com/skfd/FakeXrmEasyUpdatePluginCrash/blob/master/Tests/Class1.cs)

** FakeXrmEasy and Dynamics 365 / CRM version **
FakeXrmEasy 2.3.0

**Comment by jordimontana82** [comment]
Hi from London!

I saw you're using a plugin with secure / insecure configs. Can you try with a parameterless constructor to confirm please?

I've raised this issue to keep track of it anyway:

https://github.com/DynamicsValue/fake-xrm-easy/issues/103

We use that other repo for the new versions, so I'll close this issue and we can follow it up from that other issue please?

Thank you!

**Comment by skfd** [comment]
omg, that actually fixed an issue! thanks! I'm not actually using secure/insecure configs in my current project, but `pac plugin init` template has them by default.

**Comment by jordimontana82** [comment]
Glad FakeXrmEasy is able to help spotting these issues... ! :smile: 

I'll keep the new issue anyway cause it'll be handy, I'm surprised it wasn't flagged before!
