### ISSUE TITLE
Feature: FetchXml and Aggregate

### ISSUE THREAD

**Issue by phuocle** [jordimontana82/fake-xrm-easy#61]
CRM only support **aggregate by FetchXml**.

`RetrieveMultipleRequestExecutor.Execute` convert `FetchXml` to `TranslateFetchXmlToQueryExpression` then `TranslateQueryExpressionToLinq`

**aggregate by FetchXml** gone

Please support this FetchXml query.

Thanks

**Comment by jordimontana82** [comment]
Hi @phuocle 

FetchXml implementation is still in progress and aggregations are not yet supported indeed. My idea was to calculate aggregations using LINQ from the set of entities returned by the QueryExpression execution.

So, 3 steps

1) TranslateFetchXmlToQueryExpression
2) Execute the query 
3) If FetchXml had aggregations, aggregate them using Linq based on the results you got from step 2

Steps 1 and 2 are already implemented. Would you like to have a look at step 3?

**Comment by jordimontana82** [comment]
Hi @phuocle 

Do you need any help on this? I'm just putting my focus on developing the [client side version of FakeXrmEasy](https://github.com/jordimontana82/fake-xrm-easy-js) right now but I will revisit this once we have a preview

**Comment by slahn** [comment]
I'm looking at a possible solution for this in the [fetch-aggregates branch in slahn/fake-xrm-easy](/slahn/fake-xrm-easy/tree/fetch-aggregates).

I currently handle very simple count-aggregations only. Going to work on date grouping, the remaining aggregations, and ordering in the next few days.

I would appreciate feedback on the direction I'm taking, as well as help with writing tests.

**Comment by slahn** [comment]
I have cleaned up the code a bit, and added naive implementations of all groupings/aggregates.

I need help writing good tests that cover corner cases of CRMs behavior when using aggregates. For example, how are nulls handled in different aggregates, and in groupings?

I also havn't implemented ordering yet. When using aggregates, ordering should be done after aggregation, not before.

**Comment by jordimontana82** [comment]
Thanks @slahn , I'll have a look asap.

**Comment by slahn** [comment]
Looking at this now - getting close to something useable.
There are a lot of small corner case errors with the current FetchXml support though. Do you want me to open issues for each of these, or should I just correct them (and the tests) in my feature branch?

**Comment by jordimontana82** [comment]
No worries.  I started with FetchXml a couple of weeks ago so... it is possible indeed :)   I'm for example adding support for date time filters, which are not there yet.

Please do raise any bugs as issues if you find them.

Re order by, yeah, they should be done after group by. We already have an attribute comparer for OrderBy's which was used in QueryExpressions, maybe you can use that. 

Re tests and aggregations, maybe we can starte with the [ones from MSDN](https://msdn.microsoft.com/en-GB/library/gg309565.aspx) maybe? 

Thanks a lot for your contributions btw.

**Comment by jordimontana82** [comment]
Hi @slahn 

I've updated the README with the list of condition operators still in progress. Did you find any other issues?

**Comment by jordimontana82** [comment]
@slahn how are you?

I've been adding quite a lot of enhancements to FetchXml and I was wondering... is the aggregation something you are still looking at?

**Comment by crisfervil** [comment]
Looking forward to have this available :)

**Comment by jordimontana82** [comment]
Just merged @slahn 's fork. It is available in the last version of the package.

If you find any edge cases / aggregate functions not covered yet please add the unit tests to reproduce them [here](https://github.com/jordimontana82/fake-xrm-easy/blob/master/FakeXrmEasy.Tests.Shared/FakeContextTests/FetchXml/AggregateTests.cs) ;)

**Comment by jordimontana82** [comment]
Closing this one, we might raise separate issues if we found anything re aggregation
