### ISSUE TITLE
Call for FakeXrmEasy.Js contributors / feedback

### ISSUE THREAD

**Issue by jordimontana82** [jordimontana82/fake-xrm-easy#66]
Hi guys @DigitalFlow , @crisfervil, @kmjones77

I started working on a [client-side version](https://github.com/jordimontana82/fake-xrm-easy-js) of FakeXrmEasy to mock Web API calls automatically.

Would be great if I could get some feedback of the proposed architecture.

I've put a lot of detail into the README but please do not hesitate to tell me if there is anything which could be better explained or clarified.

Thanks a mill!

**Comment by DigitalFlow** [comment]
Sounds like a nice idea.
I'm wondering however, how this would be integrated in a CI.
Would you have to host a node.js server for running the tests in your CI builds?

**Comment by jordimontana82** [comment]
That's a good point.

We could try to install node via Nuget restore? If that works it'll be ideal....

There are packages for Node.js and npm:

https://www.nuget.org/packages/Node.js/
https://www.nuget.org/packages/Npm/

**Comment by jordimontana82** [comment]
@DigitalFlow it's been a long time since this was raised :) 

Catching up with old issues first after the christmas break ...  I've replaced the idea of using edge.js on fake xrm easy (js) some time ago, since edge didn't have much support and it was also a pain in the ass cause it needed a specific precompiled version, which means one usually would have to use a tool like nvm to run the code against a specific version.

Now that dependency has been removed completely and it runs purely in typescript.

I'd love your feedback @DigitalFlow  and also @camelCaseDave 

Closing this one, feel free to reach out to the other repo :)

**Comment by DigitalFlow** [comment]
Hey @jordimontana82,

glad to hear from you again, it has been quite a while :)

I'll take a look, sounds like a good approach and switching to TypeScript is a good thing to me, I love it :).

Kind Regards
