### ISSUE TITLE
How to pass in Default Code Activity Context?

### ISSUE THREAD

**Issue by krishire** [jordimontana82/fake-xrm-easy#69]
I'm struggling to pass a default Code Activity Context from my unit test case method.
Please help me with an example of how to pass a mocked Code Activty context while making an ExecuteCodeActivity<CodeActivity>(PrimaryEntity, inputs) call.
In my code activity, I'm trying to get the context.IntitiatingUserId, which is failing with  null object exception.

**Comment by jordimontana82** [comment]
Hi @krishire 

There is a new version in Nuget where you can pass a custom workflow context now 

    XrmFakedWorkflowContext

In a similar way as you did with plugins.

Cheers,
