### ISSUE TITLE
OrganisationServiceContext.SaveChanges() and .AddRelatedObject()

### ISSUE THREAD

**Issue by jordimontana82** [jordimontana82/fake-xrm-easy#78]
There is an issue where the .AddRelatedObject() method is not properly sending a CreateRequest for the entity you want to associate.

This will need further investigation. In the meantime, the workaround is to use the fake service reference directly instead (.Create() + .Associate()).

CRM LINQ queries should be fine though.

**Comment by bacon1986** [comment]
I've had a quick look at the code and haven't been able to confirm this but I have a suspicion it may be related to the returned value of CreateRequestExecutor.Execute.
As the method returns an empty CreateResponse object without the id of the newly created entity populated it's possible that the OrganisationServiceContext doesn't have the id to then be able to go on and make the association.
I have no idea how you'd fix this though as the class is sealed and the id property doesn't have a setter.
Thanks
Simon

**Comment by jordimontana82** [comment]
Thx @bacon1986 

I already tried that passing the Id in my local branch and same result...  unfortunately. I'll keep digging.

Even thou sealed, you could set the id via a ParameterCollection like the response returned from a RetrieveMultiple. It's messy, but works :)

**Comment by bacon1986** [comment]
Cool.
Adding that sets the ID in the returned array from ctx.SaveChanges() which is a good start :)
I'm going to have to do a create via an execute request to an actual org service and see what that returns.

**Comment by bacon1986** [comment]
I think I've fixed it. I'll submit a pull request in a bit.
