### ISSUE TITLE
XrmFakedContext.Metadata.cs is missing

### ISSUE THREAD

**Issue by DigitalFlow** [jordimontana82/fake-xrm-easy#8]
Hello Jordi,

thanks for your great work.
I'd like to contribute and add support for passing secure and unsecure configurations to plugin executions.
I just checked out the project, but it seems as if the XrmFakedContext.Metadata.cs file is missing from the project, so I can't build it right now.
Can you check in that file?

Kind Regards

**Comment by jordimontana82** [comment]
Hi @DigitalFlow ,
Thanks a mill for your feedback. It is much appreciated.

I've just checked in that file which was missing... it is a job in progress... but at least it is building now and the 117 tests are passing. 

Also the  I've also updated a reference in the FakeXrmEasy.Tests project cause now XUnit test runners are installed at the solution level, and not as a extension, like before.

Regards,

**Comment by jordimontana82** [comment]
If you want to extend it, it would be amazing. Feel free to fork the project and send a pull request! :)

I would personally see that feature handy as a new method with the 2 configurations , similar to the ExecutePluginWith<T> method, like this:

    public IPlugin ExecutePluginWithConfigurations<T>(ParameterCollection inputParameters,
                                     ParameterCollection outputParameters,
                                     EntityImageCollection preEntityImages,
                                     EntityImageCollection postEntityImages,
                                     string unsecureConfig,
                                     string secureConfig,
                           ) where T : IPlugin, new()
    {
    }

What do you think?

**Comment by DigitalFlow** [comment]
Hi @jordimontana82,

That was exactly what I imagined as new method for accepting the configurations.
I'll implement it and send a Pull Request.

**Comment by jordimontana82** [comment]
Cool!
