### ISSUE TITLE
CreateRequest and new RelatedEntities

### ISSUE THREAD

**Issue by mivra** [jordimontana82/fake-xrm-easy#80]
Hello,
I think I've found a bug in the `CreateRequest`. It may be connected with issue #78. During the creation process relationships can be added, but in case those related entities are not existing in the CRM yet, it should also get created. At least this is the behavior of genuine OrganizationService.
We have a code like this which creates Order and its OrderDetails in one request. Currently, FakeXrmEase does not create OrderDetail records in the 'fake database' and also ID of the main created Order is empty GUID.

```csharp
var orderItems = new EntityCollection(order.OrderItems.Cast<Entity>().ToList());

// Add related order items so it can be created in one request
order.SalesOrder.RelatedEntities.Add(new Relationship
{
	PrimaryEntityRole = EntityRole.Referenced, 
	SchemaName = "order_details"
}, orderItems);

var request = new CreateRequest
{
	Target = order.SalesOrder
};

var response = (CreateResponse)crmService.Execute(request);
```
How difficult it would be to support this scenario?

Thanks,
Michal

**Comment by jordimontana82** [comment]
Hi @mivra 

Thanks for raising this. Could post the entire unit test to see how the "order" instance is created?

It might be related to the fact you need to provide the Relationship info, like .AddRelationship(), before you can actually call .Create.

@bacon1986 what do you think?

**Comment by bacon1986** [comment]
I've set up a similar unit test and without defining the relationship first it throws an exception "Relationship order_details does not exist in the metadata cache"

Before the fix for #78 it wouldn't have created the RelatedEntities at-all so it's possible that you're using a version before 1.15.5

**Comment by jordimontana82** [comment]
Hi @mivra ,

You were right, @bacon1986  there were 2 small issues when trying to use the .RelatedEntities for 1 to many relationships:

1) Id's were not generated automatically cause the .AddEntity only adds an entity (with logical name and id) to the Dictionary. This has been refactored and a new CreateEntity introduced, refactored from the .Create messasge, which generates a new Guid if empty

2) Entities were associated using the AssociateRequest, but that was for N:N relationships only cause it was always creating entities in the IntersectTable. For this example, the relationship in the .RelatedEntities was 1:N so this shouldn't be required. So, I extended the XrmFakedRelationship to cater for 1:N relationships too, like SalesOrder -> SalesOrderDetail, via a new property: RelationshipType.

@mivra  There are new unit tests you can use as an example.

The only thing I'm not sure 100% is that if an AssociateRequest can be used for 1:N or N:1 relationships in CRM. I've always used EntityReferences for that :)

**Comment by mivra** [comment]
I can confirm the fix is working after the relationship is registered. Thank you @jordimontana82 for amazing work!

**Comment by jordimontana82** [comment]
You're very welcome @mivra !

Glad it helps! 

Also, the very best thing you can do for this project is: spread the word!  : )
