### ISSUE TITLE
Add code coverage metrics

### ISSUE THREAD

**Issue by jordimontana82** [jordimontana82/fake-xrm-easy#86]
Hi Florian, 

How are you?

I extended your awesome fake script last week to add code coverage metrics. Hope you like them! :)

@DigitalFlow

**Comment by DigitalFlow** [comment]
Hey Jordi,

I'm fine, how about you?
Had a look onto the code coverage metrics, nice stuff!

Kind Regards,
Florian

**Comment by jordimontana82** [comment]
I'm good thx! 

Glad you like them ;)
