### ISSUE TITLE
What extensions would you like for integration testing???

### ISSUE THREAD

**Issue by jordimontana82** [jordimontana82/fake-xrm-easy#88]
Ok so.... placeholder for brainstorming useful extension methods of the IOrganizationService you would like to have for integration testing, like:

```
//Waits until a systemjob with name wfName is triggered for a record with id gRecordId of an entity with name sEntityName 
WaitForWorkflow(string wfName, string sEntityName, Guid gRecordId)
```

**Comment by DigitalFlow** [comment]
Thought about it a little bit, maybe it could prove useful to be able to deploy your latest CI plugin assembly to your testing organization before running the integration tests.
The OrganizationService definetly supports this.

**Comment by jordimontana82** [comment]
Thx for your feedback @DigitalFlow .

Indeed, it would be nice. There are powershell scripts out there which are doing that right now already tho (i.e. https://xrmciframework.codeplex.com/).

The aim of the integration package would be to add extension methods to the post-deployment phase.  So, after you have deployed a bunch of assemblies, entities, and workflows, .... a package you would use in an automated integration testing phase after deployment.

Ex:

Build -> Unit Tests -> Deploy -> **Integration Tests**

**Comment by jordimontana82** [comment]
The good thing is that we could use FakeXrmEasy to unit test the Integration testing package.... that's gonna be cool! : D

**Comment by crisfervil** [comment]
Maybe can be helpful to have a CrmAssert class, that helps checking values after an action is performed in the server, like creating a record. 

For example:
``` cs
var accountRecord = new Entity("account");
var accountId = service.Create(accountRecord);
CrmAssert.Exist("account",new {name="Acme", ownerid=new EntityReference(myUserId)});
```

**Comment by jordimontana82** [comment]
@crisfervil  Like that! Maybe we could also have the strong typed version, i.e.:

    CrmAssert.Exists<Account>(new Account() {name="Acme", ownerid=new EntityReference(myUserId)});


Or an equivalent one passing a LINQ query?

    var query = ctx.CreateQuery<Account>().Where(a => a.Name == "acme");
    CrmAssert.Exists(() => query).AtLeastOne();

**Comment by Nehmiabm** [comment]
What happened to this thread? I was looking for Integration Test framework with setup and tear-down

**Comment by jordimontana82** [comment]
Hi @Nehmiabm,

There is the XrmRealContext there which basically implements the same interface as XrmFakedContext but it connects directly against a CRM/365 instance.

However, there is no setup / tear-down methods there to initialize / clean up records, so at the minute you have to implement them on your own for each test. 

One possibility could be to track the Create / Update / Delete messages and automatically perform a tear-down of all the records that were setup + modified / created / deleted as part of the execution. However, depending on data dependencies it might not be a trivial task.

What are your thoughts?

**Comment by Nehmiabm** [comment]
Thank you for your response @jordimontana82 

I was actually looking for a generic and easier way of Setup and Tear-Down. For example, beginning transaction on Setup (Initialization) and manually rolling back on Tear-Down. This can be implemented in a single class and used by all my integration tests so I don't have to worry about cleaning up after all changes. I was actually reading about controlling transactions in CRM and it doesn't seem to be a trivial task. Is it?

**Comment by jordimontana82** [comment]
Ok get you :)

One option might be running that inside ExecuteInTransaction, which is only available for certain versions of CRM. However, I wouldn't be so sure that mimics the same behavior if the code you're testing doesn't use the same message, because the many different messages won't run inside the same transaction unless using that (or inside a plugin context).

Another option might be something like storing all the different operations for create, update, delete and execute them in reverse order (create -> delete,  delete -> create) during tear down. That might be closer if the sut (system under test) doesn't use ExecuteInTransaction, but it considerably more complex.

Another last option is, if using online, you back up the org using online management api and then restore it on each run and there's no need to care for tear down :)

**Comment by Nehmiabm** [comment]
Thanks again for following up @jordimontana82 

I looked into ExecuteInTransaction class and as you stated it's only applicable for CRM version >=2015. (I'm on CRM 2013). Actually even if it was supported, it wouldn't help me much as I'm not accumulating requests and triggering them all at once. I would like to execute commands separately for each entity.

I was looking for a solution not that complex only in the context of Integration Testing. I need your thought on this; If I use Entity Framework 6 on top of CRM Dynamics, in a separate library, I would be able to leverage TransactionScope to begin transaction on Setup and roll back on Tear-Down. I would only configure entity models I often use and I'm only going to leverage this in my Integration Tests only.

What is your thought on this?

**Comment by jordimontana82** [comment]
How would you integrate Entity Framework on top of CRM? By not using IOrganizationService and making connections against the underlying database directly?

**Comment by Nehmiabm** [comment]
Yes I’ll not use IOrganizationService for my Integration Test. I’ll directly communicate with the database through Entity Framework and that will be implemented in a separate class library. I’ll provide a base IntegrationTest class that will provide the transaction handling on setup and tear-down. This implementation will only be for my IntegrationTest

**Comment by DigitalFlow** [comment]
Hi @Nehmiabm,

This sounds like something you really should not do. Database access is hacky and I was also wondering, how you want to achieve that the Dynamics IOrganizationService endpoint (on the server) is in your transaction as well? Sounds impossible to me.

Wouldn't it suffice to access the FakeXrmEasy entity dictionary and delete all records in there in the CRM database as tear down? You would have to check  whether the viability of this approach, but the database sounds like a dead end to me.

**Comment by Nehmiabm** [comment]
Hi @DigitalFlow Thank you for your comment,

The main reason I wanted to work against real OrganizationService instead of fake (In memory) one is because I would like to validate the schema whenever a new field has been added, modified or deleted. If I work in memory I wouldn't be able to detect breaking schema changes hence it's not real integration test.

 I would like to control Setup and Tear-Down easily for Integration Tests. As @jordimontana82 mentioned in one of his comments, I could track operation performed in entities and manually delete/rollback but I was looking for a simple solution like controlling this behavior through Transaction.

That's why I came up with the 'hacky' solution to work directly with the underlying CRM database and controlling the TransactionScope using Isolation Level. For example, using 'READ UNCOMMITTED' Isolation Level would allow the OrganizationService (API) to access the record and I will dispose it on Tear-Down. I admit it's hacky. I was wondering if you have run into a similar kind of situation and how you write your Integration Tests in CRM with Setup and Tear-Down.

Maybe sticking to tracking operations and manually rolling back is the best option I will have to stick with as you suggested.

**Comment by jordimontana82** [comment]
+1 to @DigitalFlow  and that's one of the reasons I asked. Accessing the database directly is unsupported and I wouldn't go down that route to be honest.

@Nehmiabm  you can still check breaking schema changes in unit tests by using strongly typed entities, which I hope you're using, i.e. if you generate strong typed entities as part of your build process from an actual CRM instance, if a field was deleted, it won't be part of your generated assemblies and so your app will fail during build, even before running any unit tests.

I still see issues with the setup / tear down methods in integration test cause there are many points of failure that we don't have in unit tests (ex: what happens if the network goes down while the tear down? or if there is a database lock that produces an exception, .... all these issues will leave your organisation in an inconsistent state). 

So that's why if you really really need integration tests, I would start the test suite by restoring a vanilla crm organisation, then import customizations, then run tests. That is a repeatable process (slow, , very slow, but at least repeatable).

**Comment by jordimontana82** [comment]
In addition @Nehmiabm , when using strong type typed entities (early bound) attributes and types will be checked even in plain text queries , like FetchXml

**Comment by Nehmiabm** [comment]
@jordimontana82 thank you for the detailed input

I never knew about the early bound strongly typed entity generation since our company is still stuck on CRM2013. I see that this is supported for CRM >=2015?

My final question would be does fake-xrm-easy library support to work with these strongly typed generated entities? Would I be able to work with the In memory IOrganizationService, in fake-xrm, while I can still validate the schema changes using the early bound data model? If the answer is yes, that would be amazing.

I guess I am kind of limited by CRM2013 because I can't get access the cool features and tool sets supported by latest versions of CRM.

**Comment by jordimontana82** [comment]
@Nehmiabm  you can use early bound entities since CRM 2011, so that should work for 2013 too.

If you want to have a closer look, please check [this post](https://docs.microsoft.com/en-gb/dynamics365/customer-engagement/developer/org-service/create-early-bound-entity-classes-code-generation-tool)

And yes, when you use strongly typed entities FakeXrmEasy ensures the attributes must exist in the In-Memory IOrganizationService.

**Comment by Nehmiabm** [comment]
@jordimontana82  Thank you very much. I appreciate your follow up and detailed assistance on this.

 I'll check out the links you provided and the documentation. It's time for me to adopt fake-xrm-easy for all my unit tests. :-)
