### ISSUE TITLE
Service fails when queryexpresion uses optionsets are strings

### ISSUE THREAD

**Issue by sarria88** [jordimontana82/fake-xrm-easy#89]
Hi Jordi and thanks for your framework.

I have an issue when using option sets compare to strings within queryExpressions . 
When querying the CRM service these type of queries work as expected but when querying the fake service obtained from your fakecontext there is an error.

The code.
```
            QueryExpression query = new QueryExpression
            {
                EntityName = "dog",
                ColumnSet = new ColumnSet("dogid"),
            };

            query.Criteria.AddCondition("dogname", ConditionOperator.Equal, name);
           //THE NEXT 2 LINES GENERATE THE ERROR. 
            query.Criteria.AddCondition("dogtype", ConditionOperator.In, "919780001", "919780004"); 
            query.Criteria.AddCondition("statecode", ConditionOperator.Equal, "Active");

            return _service.RetrieveMultiple(query);
```

The error.
**Unable to cast object of type 'Microsoft.Xrm.Sdk.OptionSetValue' to type 'System.String'.**

Obviously the error is related to the Option set values for statecode and dogtype being strings in here and if there are changed by numbers or its option set value everything works as expected. 

This code works:
```
            QueryExpression query = new QueryExpression
            {
                EntityName = "epa_licence",
                ColumnSet = new ColumnSet("epa_licenceid"),

            };

            query.Criteria.AddCondition("lema_rootregnumber", ConditionOperator.Equal, rootreg);
            query.Criteria.AddCondition("epa_licencestatus", ConditionOperator.In, 919780001, 919780004); 
            query.Criteria.AddCondition("statecode", ConditionOperator.Equal, 0);

            return _service.RetrieveMultiple(query);
```

May be is not the best way of creating queries agains CRM but the CRM service supports this way of querying so I think your fakeservice should support it also.

Thanks again for your work and patience.

Miguel

**Comment by jordimontana82** [comment]
Just checked in some code which fixes the first line (so being able to use strings as the optionset values), but I'm afraid the second one will be a "won't fix" type of issue, cause it would introduce lots of performance issues and there won't be any much added value by adding it.

    query.Criteria.AddCondition("epa_licencestatus", ConditionOperator.In, "919780001", "919780004");
