### ISSUE TITLE
Bug in Handling of Entity Records

### ISSUE THREAD

**Issue by DigitalFlow** [jordimontana82/fake-xrm-easy#90]
Hey All,

I just discovered, that there is an issue in how FakeXrmEasy is handling the storage and retrieval of entity records (objects).
When retrieving an entity record from FakeXrmEasy, we get the plain reference to the object that is stored in FakeXrmEasy's memory context.
This is an issue, since value changes on those retrieved objects lead to updates in FakeXrmEasys's memory context, even without update.

An example for this is the following:
``` C#
        [Test]
        public void Should_Not_Change_Context_Objects_Without_Update()
        {
            var entityId = Guid.NewGuid();
            var context = new XrmFakedContext();
            var service = context.GetFakedOrganizationService();

            context.Initialize(new[] {
                new Entity ("account", entityId)
                {
                    Attributes = new AttributeCollection
                    {
                        { "accountname", "Adventure Works" }
                    }
                }
            });

            var firstRetrieve = service.Retrieve("account", entityId, new ColumnSet(true));
            var secondRetrieve = service.Retrieve("account", entityId, new ColumnSet(true));

            firstRetrieve["accountname"] = "Updated locally";

            Assert.AreEqual("Updated locally", firstRetrieve["accountname"]);
            Assert.AreEqual("Adventure Works", secondRetrieve["accountname"]);
        }
```

We would assume, that secondRetrieve's accountName is still "Adventure Works".
The test however fails with the following message:
```
  String lengths are both 15. Strings differ at index 0.
  Expected: "Adventure Works"
  But was:  "Updated locally"
  -----------^
```

We have to change this and probably return in some way a deep copy of the stored object on every retrieval, so that there are no side effects when changing retrieved objects without update.
Shallow copies would not suffice, as changes to money properties would show the same side effect issue again.

When doing the change, we have to take special care for Plugin Executions, since the current behaviour is the reason why PrePlugins properly update their values to the context.
Maybe we should introduce a Stage Property for Plugin Execution, so that we know when we're in a Plugin that is simulated as Pre and have to send an Update on the Entity after the execution is done.

What do you think of that?

Kind Regards,
Florian

**Comment by jordimontana82** [comment]
Hey Florian!

Thx for spotting this.... I had a similar issue when doing the joins and that was sorted by doing a clone of the entity record.

This could be resolved the same way.

**Comment by jordimontana82** [comment]
Hey Florian.

Added a fix for this. It's a pitty the neither the Entity, nor EntityReference nor OptionSetValue nor Money classes have a copy constructors, so I had to do it from scratch pretty much.

**Comment by DigitalFlow** [comment]
Hey Jordi,

great job, thanks a lot! :smile:

Kind Regards,
Florian

**Comment by jordimontana82** [comment]
Just one thing I noticed.... 

We'll be deprecating at some stage the GetFakedOrganizationService method in favor of the GetOrganizationService method instead, so I changed the GetFakedOrganizationService call in your test by .GetOrganizationService.

This is because now we have **XrmFakedContext** and **XrmRealContext** implementations, and the first one really uses the GetFakedOrganisationService only, whereas that naming convention for XrmRealContext didn't make much sense... 😄

So..  we'll be consolidating the 2 implementations into the one GetOrganizationService method instead.

**Comment by DigitalFlow** [comment]
Sounds great, thanks for adjusting 👍

**Comment by jordimontana82** [comment]
No prob!
