### ISSUE TITLE
Cloning object while retrieving fails

### ISSUE THREAD

**Issue by DigitalFlow** [jordimontana82/fake-xrm-easy#93]
Hey Jordi,

The following Query triggers an Exception:
```C#
var mail = crmContext.CreateQuery<Email>()
    .Where(e => e.RegardingObjectId.Id == QuoteOne.Id)
    .ToList();
```

Here is the exception detail:
```C#
System.Exception : 
Attribute type not supported when trying to clone attribute 'Microsoft.Xrm.Sdk.EntityCollection'
```

My guess would be that this is failing for the activity parties.
We should ensure to handle those, too.

Kind Regards,
Florian

**Comment by jordimontana82** [comment]
Oh, thx for spotting this... 

That's interesting... RegardingObjectId should be an EntityReference attribute which in theory is handled by the CloneAttributes method

    /// <summary>
		/// Unique identifier of the object with which the appointment is associated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		public Microsoft.Xrm.Sdk.EntityReference RegardingObjectId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("regardingobjectid");
			}
			set
			{
				this.OnPropertyChanging("RegardingObjectId");
				this.SetAttributeValue("regardingobjectid", value);
				this.OnPropertyChanged("RegardingObjectId");
			}
		}


Could you post submit a full test to reproduce this, please?

**Comment by DigitalFlow** [comment]
Hey Jordi,

this is not about the RegardingObjectId, but about the From or To properties, which are represented by EntityCollections.
I'll submit a full test shortly.

Kind Regards,
Florian

**Comment by jordimontana82** [comment]
Right, ok.

It should be fixed more or less easily by calling the Clone method recursively maybe then.

something like: 

    if(attributeValue.GetType() == typeof(EntityCollection))

        return new EntityCollection(attributeValue.Select( e => e.Clone(e.GetType())).ToList())

**Comment by DigitalFlow** [comment]
Yes, that was the approach that I thought about, too.

**Comment by DigitalFlow** [comment]
Ok, just incorporated the fix as you suggested in #94.
Tests are passing.

**Comment by jordimontana82** [comment]
Awesome! Thx a mill Florian :+1:

**Comment by DigitalFlow** [comment]
You're welcome, glad that this project exists.
Makes a CRM developer's life a lot easier :smile:

**Comment by jordimontana82** [comment]
Thx a mill! 

I merged your 2 PRs. Just moved the RetrieveTests to a different class which had other retrieve tests already...

**Comment by DigitalFlow** [comment]
Awesome! 👍
