### ISSUE TITLE
Exception type is different

### ISSUE THREAD

**Issue by donamk** [jordimontana82/fake-xrm-easy#98]
Hello,

For validation, I made a plugin like this.
Stage = 10 (pre validation)
MessageName = Create

```
// AccountPluguin.cs
...
if (account["name"].Length > 10)
{
    throw new InvalidPluginExecutionException("Error! account name cannot over 10 characters");
}
...

// AccountPluginTests.cs
[Fact]
public void Create_An_Account_With_Long_Name_Should_Throw_Exception()
{
    // Arrange
    var context = new XrmFakedContext();
    context.ProxyTypesAssembly = Assembly.GetAssembly(typeof(Account));
  
    var account = new Account
    {
        Id = Guid.NewGuid(),
        AccountName = "12345678901"
    };
            
    var inputParameters = new ParameterCollection();
    inputParameters.Add("Target", account);

    XrmFakedPluginExecutionContext pluginCtx = context.GetDefaultPluginContext();
    pluginCtx.PrimaryEntityName = "account";
    pluginCtx.Stage = 10;
    pluginCtx.MessageName = "Create";
    pluginCtx.InputParameters = inputParameters;

    // Act
    Exception ex = Assert.Throws<FaultException<OrganizationServiceFault>>(
        () => context.ExecutePluginWithConfigurations<AccountPluguin>(pluginCtx, null, null)
    );
            
    // Assert
    Assert.Equal("Error! account name cannot over 10 characters", ex.Message);       
}  
```

Exception Message:
Assert.Throws() Failure
Expected: `typeof(System.ServiceModel.FaultException<Microsoft.Xrm.Sdk.OrganizationServiceFault>)`
Actual:  `typeof(Microsoft.Xrm.Sdk.InvalidPluginExecutionException)`: Error! account name cannot over 10 characters
...

When I test with CRM not FakeXrmEasy, CRM return `typeof(System.ServiceModel.FaultException<Microsoft.Xrm.Sdk.OrganizationServiceFault>)`

Please test with CRM which type of Error should throw.

Kindly Regards,

**Comment by jordimontana82** [comment]
Hi @donamk ,

Thanks for your issue!

I do think however FakeXrmEasy shouldn't wrap exceptions inside FaultExceptions, and just rethrow the  original exception thrown.

I agree the organization service will return a FaultException when the plugin is triggered, but it will raise an InvalidPluginExecutionException inside the plugin pipeline and that's what we need to test from a unit testing perspective. The FaultException is something returned outside of the scope of your plugin (probably many layers above it).

It makes assertions a bit more clean too... example. You can unit test the same thing with this:

    // Act
    Exception ex = Assert.Throws<InvalidPluginExecutionException>(
        () => context.ExecutePluginWithConfigurations<AccountPluguin>(pluginCtx, null, null)
    );

    // Assert
    Assert.Equal("Error! account name cannot over 10 characters", ex.Message);

**Comment by donamk** [comment]
Thank you @jordimontana82 

I assume XrmFakeEasy is mocking CRM's behaviour so I expected FaultExceptions.

I totally agree with you but I think it would be great this behaviour should be documented :)
Unless may many people may expected FaultExceptions as like me :)

Cheers

**Comment by jordimontana82** [comment]
You're very welcome and thx for your feedback @donamk !

Indeed, the service returns FaultExceptions (some examples [here](https://github.com/jordimontana82/fake-xrm-easy/blob/dcb92b1a9f0fb6101e596efecb34b05941a84828/FakeXrmEasy.Shared/FakeMessageExecutors/ExecuteMultipleRequestExecutor.cs#L24-L29)).

But exceptions raised **inside** a ExecutePlugin or ExecuteCodeActivity are treated differently, cause they simulate an exception thrown inside the plugin pipeline, so they'll be rethrown directly in that case.

Hope this helps.

And yeah, we have to update the documentation and it is something reaaaaally time consuming :)

**Comment by donamk** [comment]
Thank you for providing the detail.
I will keep in mind ExecutePlugin and ExecuteCodeActivity are differetnly behave :)
